// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit.audit_event
    (category, event_type, actor_user_id, actor_role, workspace_id,
     resource_type, resource_id, metadata, before_state, after_state)
VALUES
    ($1::audit.event_category, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id
`

type InsertAuditEventParams struct {
	Column1      AuditEventCategory `json:"column_1"`
	EventType    string             `json:"event_type"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	ActorRole    *string            `json:"actor_role"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Metadata     json.RawMessage    `json:"metadata"`
	BeforeState  []byte             `json:"before_state"`
	AfterState   []byte             `json:"after_state"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.Column1,
		arg.EventType,
		arg.ActorUserID,
		arg.ActorRole,
		arg.WorkspaceID,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.BeforeState,
		arg.AfterState,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const partitionExists = `-- name: PartitionExists :one
SELECT EXISTS(
    SELECT 1 FROM audit.partition_registry WHERE partition_name = $1
)
`

func (q *Queries) PartitionExists(ctx context.Context, partitionName string) (bool, error) {
	row := q.db.QueryRow(ctx, partitionExists, partitionName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const queryAuditEvents = `-- name: QueryAuditEvents :many
SELECT id, category::text, event_type, actor_user_id, actor_role, workspace_id,
       resource_type, resource_id, metadata, occurred_at
FROM audit.audit_event
WHERE ($1::uuid IS NULL OR workspace_id = $1)
  AND ($2::text IS NULL OR category::text = $2)
  AND ($3::text IS NULL OR resource_type = $3)
  AND ($4::text IS NULL OR resource_id = $4)
  AND ($5::timestamptz IS NULL OR occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR occurred_at <= $6)
ORDER BY occurred_at DESC
LIMIT $7 OFFSET $8
`

type QueryAuditEventsParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
	Column4 string    `json:"column_4"`
	Column5 time.Time `json:"column_5"`
	Column6 time.Time `json:"column_6"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type QueryAuditEventsRow struct {
	ID           uuid.UUID       `json:"id"`
	Category     string          `json:"category"`
	EventType    string          `json:"event_type"`
	ActorUserID  pgtype.UUID     `json:"actor_user_id"`
	ActorRole    *string         `json:"actor_role"`
	WorkspaceID  pgtype.UUID     `json:"workspace_id"`
	ResourceType *string         `json:"resource_type"`
	ResourceID   *string         `json:"resource_id"`
	Metadata     json.RawMessage `json:"metadata"`
	OccurredAt   time.Time       `json:"occurred_at"`
}

func (q *Queries) QueryAuditEvents(ctx context.Context, arg QueryAuditEventsParams) ([]QueryAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, queryAuditEvents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryAuditEventsRow
	for rows.Next() {
		var i QueryAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.EventType,
			&i.ActorUserID,
			&i.ActorRole,
			&i.WorkspaceID,
			&i.ResourceType,
			&i.ResourceID,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerPartition = `-- name: RegisterPartition :exec
INSERT INTO audit.partition_registry (partition_name, range_start, range_end)
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type RegisterPartitionParams struct {
	PartitionName string    `json:"partition_name"`
	RangeStart    time.Time `json:"range_start"`
	RangeEnd      time.Time `json:"range_end"`
}

func (q *Queries) RegisterPartition(ctx context.Context, arg RegisterPartitionParams) error {
	_, err := q.db.Exec(ctx, registerPartition, arg.PartitionName, arg.RangeStart, arg.RangeEnd)
	return err
}
