// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiAssistantActionType string

const (
	AiAssistantActionTypeAddMetric         AiAssistantActionType = "add_metric"
	AiAssistantActionTypeModifyFormula     AiAssistantActionType = "modify_formula"
	AiAssistantActionTypeAddDimension      AiAssistantActionType = "add_dimension"
	AiAssistantActionTypeModifyPolicy      AiAssistantActionType = "modify_policy"
	AiAssistantActionTypeAddWorkflow       AiAssistantActionType = "add_workflow"
	AiAssistantActionTypeGenerateMigration AiAssistantActionType = "generate_migration"
)

func (e *AiAssistantActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AiAssistantActionType(s)
	case string:
		*e = AiAssistantActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for AiAssistantActionType: %T", src)
	}
	return nil
}

type NullAiAssistantActionType struct {
	AiAssistantActionType AiAssistantActionType `json:"ai_assistant_action_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if AiAssistantActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAiAssistantActionType) Scan(value interface{}) error {
	if value == nil {
		ns.AiAssistantActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AiAssistantActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAiAssistantActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AiAssistantActionType), nil
}

func (e AiAssistantActionType) Valid() bool {
	switch e {
	case AiAssistantActionTypeAddMetric,
		AiAssistantActionTypeModifyFormula,
		AiAssistantActionTypeAddDimension,
		AiAssistantActionTypeModifyPolicy,
		AiAssistantActionTypeAddWorkflow,
		AiAssistantActionTypeGenerateMigration:
		return true
	}
	return false
}

type AuditEventCategory string

const (
	AuditEventCategoryAuth         AuditEventCategory = "auth"
	AuditEventCategoryDataChange   AuditEventCategory = "data_change"
	AuditEventCategoryModelChange  AuditEventCategory = "model_change"
	AuditEventCategoryPolicyChange AuditEventCategory = "policy_change"
	AuditEventCategoryAdmin        AuditEventCategory = "admin"
	AuditEventCategoryAiAssistant  AuditEventCategory = "ai_assistant"
)

func (e *AuditEventCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEventCategory(s)
	case string:
		*e = AuditEventCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEventCategory: %T", src)
	}
	return nil
}

type NullAuditEventCategory struct {
	AuditEventCategory AuditEventCategory `json:"audit_event_category"`
	Valid              bool               `json:"valid"` // Valid is true if AuditEventCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEventCategory) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEventCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEventCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEventCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEventCategory), nil
}

func (e AuditEventCategory) Valid() bool {
	switch e {
	case AuditEventCategoryAuth,
		AuditEventCategoryDataChange,
		AuditEventCategoryModelChange,
		AuditEventCategoryPolicyChange,
		AuditEventCategoryAdmin,
		AuditEventCategoryAiAssistant:
		return true
	}
	return false
}

type CoreApplicationMode string

const (
	CoreApplicationModePlanning  CoreApplicationMode = "planning"
	CoreApplicationModeCrud      CoreApplicationMode = "crud"
	CoreApplicationModeExecution CoreApplicationMode = "execution"
)

func (e *CoreApplicationMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreApplicationMode(s)
	case string:
		*e = CoreApplicationMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreApplicationMode: %T", src)
	}
	return nil
}

type NullCoreApplicationMode struct {
	CoreApplicationMode CoreApplicationMode `json:"core_application_mode"`
	Valid               bool                `json:"valid"` // Valid is true if CoreApplicationMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreApplicationMode) Scan(value interface{}) error {
	if value == nil {
		ns.CoreApplicationMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreApplicationMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreApplicationMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreApplicationMode), nil
}

func (e CoreApplicationMode) Valid() bool {
	switch e {
	case CoreApplicationModePlanning,
		CoreApplicationModeCrud,
		CoreApplicationModeExecution:
		return true
	}
	return false
}

type CoreApplicationStatus string

const (
	CoreApplicationStatusDraft     CoreApplicationStatus = "draft"
	CoreApplicationStatusPublished CoreApplicationStatus = "published"
	CoreApplicationStatusArchived  CoreApplicationStatus = "archived"
)

func (e *CoreApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreApplicationStatus(s)
	case string:
		*e = CoreApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreApplicationStatus: %T", src)
	}
	return nil
}

type NullCoreApplicationStatus struct {
	CoreApplicationStatus CoreApplicationStatus `json:"core_application_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if CoreApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CoreApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreApplicationStatus), nil
}

func (e CoreApplicationStatus) Valid() bool {
	switch e {
	case CoreApplicationStatusDraft,
		CoreApplicationStatusPublished,
		CoreApplicationStatusArchived:
		return true
	}
	return false
}

type CoreStorageType string

const (
	CoreStorageTypeOltp     CoreStorageType = "oltp"
	CoreStorageTypeColumnar CoreStorageType = "columnar"
	CoreStorageTypeHybrid   CoreStorageType = "hybrid"
)

func (e *CoreStorageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CoreStorageType(s)
	case string:
		*e = CoreStorageType(s)
	default:
		return fmt.Errorf("unsupported scan type for CoreStorageType: %T", src)
	}
	return nil
}

type NullCoreStorageType struct {
	CoreStorageType CoreStorageType `json:"core_storage_type"`
	Valid           bool            `json:"valid"` // Valid is true if CoreStorageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCoreStorageType) Scan(value interface{}) error {
	if value == nil {
		ns.CoreStorageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CoreStorageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCoreStorageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CoreStorageType), nil
}

func (e CoreStorageType) Valid() bool {
	switch e {
	case CoreStorageTypeOltp,
		CoreStorageTypeColumnar,
		CoreStorageTypeHybrid:
		return true
	}
	return false
}

type IdentityUserRole string

const (
	IdentityUserRolePlatformAdmin IdentityUserRole = "platform_admin"
	IdentityUserRoleDeveloper     IdentityUserRole = "developer"
	IdentityUserRoleBusinessAdmin IdentityUserRole = "business_admin"
	IdentityUserRoleBusinessUser  IdentityUserRole = "business_user"
	IdentityUserRoleTenantAdmin   IdentityUserRole = "tenant_admin"
)

func (e *IdentityUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdentityUserRole(s)
	case string:
		*e = IdentityUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for IdentityUserRole: %T", src)
	}
	return nil
}

type NullIdentityUserRole struct {
	IdentityUserRole IdentityUserRole `json:"identity_user_role"`
	Valid            bool             `json:"valid"` // Valid is true if IdentityUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdentityUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.IdentityUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdentityUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdentityUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdentityUserRole), nil
}

func (e IdentityUserRole) Valid() bool {
	switch e {
	case IdentityUserRolePlatformAdmin,
		IdentityUserRoleDeveloper,
		IdentityUserRoleBusinessAdmin,
		IdentityUserRoleBusinessUser,
		IdentityUserRoleTenantAdmin:
		return true
	}
	return false
}

type ImportImportStatus string

const (
	ImportImportStatusValidating ImportImportStatus = "validating"
	ImportImportStatusStaged     ImportImportStatus = "staged"
	ImportImportStatusCommitted  ImportImportStatus = "committed"
	ImportImportStatusFailed     ImportImportStatus = "failed"
	ImportImportStatusAborted    ImportImportStatus = "aborted"
)

func (e *ImportImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportImportStatus(s)
	case string:
		*e = ImportImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportImportStatus: %T", src)
	}
	return nil
}

type NullImportImportStatus struct {
	ImportImportStatus ImportImportStatus `json:"import_import_status"`
	Valid              bool               `json:"valid"` // Valid is true if ImportImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportImportStatus), nil
}

func (e ImportImportStatus) Valid() bool {
	switch e {
	case ImportImportStatusValidating,
		ImportImportStatusStaged,
		ImportImportStatusCommitted,
		ImportImportStatusFailed,
		ImportImportStatusAborted:
		return true
	}
	return false
}

type NotificationChannel string

const (
	NotificationChannelInApp   NotificationChannel = "in_app"
	NotificationChannelEmail   NotificationChannel = "email"
	NotificationChannelWebhook NotificationChannel = "webhook"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel `json:"notification_channel"`
	Valid               bool                `json:"valid"` // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

func (e NotificationChannel) Valid() bool {
	switch e {
	case NotificationChannelInApp,
		NotificationChannelEmail,
		NotificationChannelWebhook:
		return true
	}
	return false
}

type NotificationNotifStatus string

const (
	NotificationNotifStatusPending   NotificationNotifStatus = "pending"
	NotificationNotifStatusDelivered NotificationNotifStatus = "delivered"
	NotificationNotifStatusFailed    NotificationNotifStatus = "failed"
	NotificationNotifStatusRead      NotificationNotifStatus = "read"
)

func (e *NotificationNotifStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationNotifStatus(s)
	case string:
		*e = NotificationNotifStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationNotifStatus: %T", src)
	}
	return nil
}

type NullNotificationNotifStatus struct {
	NotificationNotifStatus NotificationNotifStatus `json:"notification_notif_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if NotificationNotifStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationNotifStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationNotifStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationNotifStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationNotifStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationNotifStatus), nil
}

func (e NotificationNotifStatus) Valid() bool {
	switch e {
	case NotificationNotifStatusPending,
		NotificationNotifStatusDelivered,
		NotificationNotifStatusFailed,
		NotificationNotifStatusRead:
		return true
	}
	return false
}

type RuntimePartitionStatus string

const (
	RuntimePartitionStatusClean       RuntimePartitionStatus = "clean"
	RuntimePartitionStatusDirty       RuntimePartitionStatus = "dirty"
	RuntimePartitionStatusCalculating RuntimePartitionStatus = "calculating"
	RuntimePartitionStatusError       RuntimePartitionStatus = "error"
)

func (e *RuntimePartitionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuntimePartitionStatus(s)
	case string:
		*e = RuntimePartitionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RuntimePartitionStatus: %T", src)
	}
	return nil
}

type NullRuntimePartitionStatus struct {
	RuntimePartitionStatus RuntimePartitionStatus `json:"runtime_partition_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if RuntimePartitionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuntimePartitionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RuntimePartitionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuntimePartitionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuntimePartitionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuntimePartitionStatus), nil
}

func (e RuntimePartitionStatus) Valid() bool {
	switch e {
	case RuntimePartitionStatusClean,
		RuntimePartitionStatusDirty,
		RuntimePartitionStatusCalculating,
		RuntimePartitionStatusError:
		return true
	}
	return false
}

type RuntimeRecordStatus string

const (
	RuntimeRecordStatusDraft     RuntimeRecordStatus = "draft"
	RuntimeRecordStatusSubmitted RuntimeRecordStatus = "submitted"
	RuntimeRecordStatusApproved  RuntimeRecordStatus = "approved"
	RuntimeRecordStatusRejected  RuntimeRecordStatus = "rejected"
)

func (e *RuntimeRecordStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuntimeRecordStatus(s)
	case string:
		*e = RuntimeRecordStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RuntimeRecordStatus: %T", src)
	}
	return nil
}

type NullRuntimeRecordStatus struct {
	RuntimeRecordStatus RuntimeRecordStatus `json:"runtime_record_status"`
	Valid               bool                `json:"valid"` // Valid is true if RuntimeRecordStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuntimeRecordStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RuntimeRecordStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuntimeRecordStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuntimeRecordStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuntimeRecordStatus), nil
}

func (e RuntimeRecordStatus) Valid() bool {
	switch e {
	case RuntimeRecordStatusDraft,
		RuntimeRecordStatusSubmitted,
		RuntimeRecordStatusApproved,
		RuntimeRecordStatusRejected:
		return true
	}
	return false
}

type SecurityPolicyAction string

const (
	SecurityPolicyActionRead    SecurityPolicyAction = "read"
	SecurityPolicyActionWrite   SecurityPolicyAction = "write"
	SecurityPolicyActionApprove SecurityPolicyAction = "approve"
	SecurityPolicyActionAdmin   SecurityPolicyAction = "admin"
)

func (e *SecurityPolicyAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SecurityPolicyAction(s)
	case string:
		*e = SecurityPolicyAction(s)
	default:
		return fmt.Errorf("unsupported scan type for SecurityPolicyAction: %T", src)
	}
	return nil
}

type NullSecurityPolicyAction struct {
	SecurityPolicyAction SecurityPolicyAction `json:"security_policy_action"`
	Valid                bool                 `json:"valid"` // Valid is true if SecurityPolicyAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSecurityPolicyAction) Scan(value interface{}) error {
	if value == nil {
		ns.SecurityPolicyAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SecurityPolicyAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSecurityPolicyAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SecurityPolicyAction), nil
}

func (e SecurityPolicyAction) Valid() bool {
	switch e {
	case SecurityPolicyActionRead,
		SecurityPolicyActionWrite,
		SecurityPolicyActionApprove,
		SecurityPolicyActionAdmin:
		return true
	}
	return false
}

type SecurityRaciType string

const (
	SecurityRaciTypeResponsible SecurityRaciType = "responsible"
	SecurityRaciTypeAccountable SecurityRaciType = "accountable"
	SecurityRaciTypeConsulted   SecurityRaciType = "consulted"
	SecurityRaciTypeInformed    SecurityRaciType = "informed"
)

func (e *SecurityRaciType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SecurityRaciType(s)
	case string:
		*e = SecurityRaciType(s)
	default:
		return fmt.Errorf("unsupported scan type for SecurityRaciType: %T", src)
	}
	return nil
}

type NullSecurityRaciType struct {
	SecurityRaciType SecurityRaciType `json:"security_raci_type"`
	Valid            bool             `json:"valid"` // Valid is true if SecurityRaciType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSecurityRaciType) Scan(value interface{}) error {
	if value == nil {
		ns.SecurityRaciType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SecurityRaciType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSecurityRaciType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SecurityRaciType), nil
}

func (e SecurityRaciType) Valid() bool {
	switch e {
	case SecurityRaciTypeResponsible,
		SecurityRaciTypeAccountable,
		SecurityRaciTypeConsulted,
		SecurityRaciTypeInformed:
		return true
	}
	return false
}

type WorkflowExecutionStatus string

const (
	WorkflowExecutionStatusRunning   WorkflowExecutionStatus = "running"
	WorkflowExecutionStatusCompleted WorkflowExecutionStatus = "completed"
	WorkflowExecutionStatusFailed    WorkflowExecutionStatus = "failed"
	WorkflowExecutionStatusCancelled WorkflowExecutionStatus = "cancelled"
)

func (e *WorkflowExecutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowExecutionStatus(s)
	case string:
		*e = WorkflowExecutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowExecutionStatus: %T", src)
	}
	return nil
}

type NullWorkflowExecutionStatus struct {
	WorkflowExecutionStatus WorkflowExecutionStatus `json:"workflow_execution_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if WorkflowExecutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowExecutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowExecutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowExecutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowExecutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowExecutionStatus), nil
}

func (e WorkflowExecutionStatus) Valid() bool {
	switch e {
	case WorkflowExecutionStatusRunning,
		WorkflowExecutionStatusCompleted,
		WorkflowExecutionStatusFailed,
		WorkflowExecutionStatusCancelled:
		return true
	}
	return false
}

type WorkflowStepStatus string

const (
	WorkflowStepStatusPending    WorkflowStepStatus = "pending"
	WorkflowStepStatusInProgress WorkflowStepStatus = "in_progress"
	WorkflowStepStatusCompleted  WorkflowStepStatus = "completed"
	WorkflowStepStatusRejected   WorkflowStepStatus = "rejected"
	WorkflowStepStatusSkipped    WorkflowStepStatus = "skipped"
)

func (e *WorkflowStepStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowStepStatus(s)
	case string:
		*e = WorkflowStepStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowStepStatus: %T", src)
	}
	return nil
}

type NullWorkflowStepStatus struct {
	WorkflowStepStatus WorkflowStepStatus `json:"workflow_step_status"`
	Valid              bool               `json:"valid"` // Valid is true if WorkflowStepStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowStepStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowStepStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowStepStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowStepStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowStepStatus), nil
}

func (e WorkflowStepStatus) Valid() bool {
	switch e {
	case WorkflowStepStatusPending,
		WorkflowStepStatusInProgress,
		WorkflowStepStatusCompleted,
		WorkflowStepStatusRejected,
		WorkflowStepStatusSkipped:
		return true
	}
	return false
}

type WorkflowStepType string

const (
	WorkflowStepTypeTask         WorkflowStepType = "task"
	WorkflowStepTypeApproval     WorkflowStepType = "approval"
	WorkflowStepTypeNotification WorkflowStepType = "notification"
	WorkflowStepTypeCondition    WorkflowStepType = "condition"
)

func (e *WorkflowStepType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowStepType(s)
	case string:
		*e = WorkflowStepType(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowStepType: %T", src)
	}
	return nil
}

type NullWorkflowStepType struct {
	WorkflowStepType WorkflowStepType `json:"workflow_step_type"`
	Valid            bool             `json:"valid"` // Valid is true if WorkflowStepType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowStepType) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowStepType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowStepType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowStepType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowStepType), nil
}

func (e WorkflowStepType) Valid() bool {
	switch e {
	case WorkflowStepTypeTask,
		WorkflowStepTypeApproval,
		WorkflowStepTypeNotification,
		WorkflowStepTypeCondition:
		return true
	}
	return false
}

type WorkflowTriggerType string

const (
	WorkflowTriggerTypeManual               WorkflowTriggerType = "manual"
	WorkflowTriggerTypeFormSubmit           WorkflowTriggerType = "form_submit"
	WorkflowTriggerTypeApi                  WorkflowTriggerType = "api"
	WorkflowTriggerTypeFormApproval         WorkflowTriggerType = "form_approval"
	WorkflowTriggerTypeGridChange           WorkflowTriggerType = "grid_change"
	WorkflowTriggerTypeSchedule             WorkflowTriggerType = "schedule"
	WorkflowTriggerTypeIntegrationCompleted WorkflowTriggerType = "integration_completed"
	WorkflowTriggerTypeIntegrationFailed    WorkflowTriggerType = "integration_failed"
)

func (e *WorkflowTriggerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowTriggerType(s)
	case string:
		*e = WorkflowTriggerType(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowTriggerType: %T", src)
	}
	return nil
}

type NullWorkflowTriggerType struct {
	WorkflowTriggerType WorkflowTriggerType `json:"workflow_trigger_type"`
	Valid               bool                `json:"valid"` // Valid is true if WorkflowTriggerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowTriggerType) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowTriggerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowTriggerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowTriggerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowTriggerType), nil
}

func (e WorkflowTriggerType) Valid() bool {
	switch e {
	case WorkflowTriggerTypeManual,
		WorkflowTriggerTypeFormSubmit,
		WorkflowTriggerTypeApi,
		WorkflowTriggerTypeFormApproval,
		WorkflowTriggerTypeGridChange,
		WorkflowTriggerTypeSchedule,
		WorkflowTriggerTypeIntegrationCompleted,
		WorkflowTriggerTypeIntegrationFailed:
		return true
	}
	return false
}

type WorkflowWorkflowStatus string

const (
	WorkflowWorkflowStatusRunning   WorkflowWorkflowStatus = "running"
	WorkflowWorkflowStatusCompleted WorkflowWorkflowStatus = "completed"
	WorkflowWorkflowStatusCancelled WorkflowWorkflowStatus = "cancelled"
	WorkflowWorkflowStatusFailed    WorkflowWorkflowStatus = "failed"
)

func (e *WorkflowWorkflowStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkflowWorkflowStatus(s)
	case string:
		*e = WorkflowWorkflowStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkflowWorkflowStatus: %T", src)
	}
	return nil
}

type NullWorkflowWorkflowStatus struct {
	WorkflowWorkflowStatus WorkflowWorkflowStatus `json:"workflow_workflow_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if WorkflowWorkflowStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkflowWorkflowStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WorkflowWorkflowStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkflowWorkflowStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkflowWorkflowStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkflowWorkflowStatus), nil
}

func (e WorkflowWorkflowStatus) Valid() bool {
	switch e {
	case WorkflowWorkflowStatusRunning,
		WorkflowWorkflowStatusCompleted,
		WorkflowWorkflowStatusCancelled,
		WorkflowWorkflowStatusFailed:
		return true
	}
	return false
}

type AiAssistantAction struct {
	ID               uuid.UUID             `json:"id"`
	SessionID        uuid.UUID             `json:"session_id"`
	ActionType       AiAssistantActionType `json:"action_type"`
	Prompt           string                `json:"prompt"`
	Diffs            json.RawMessage       `json:"diffs"`
	Impact           json.RawMessage       `json:"impact"`
	Applied          bool                  `json:"applied"`
	RollbackActionID pgtype.UUID           `json:"rollback_action_id"`
	CreatedAt        time.Time             `json:"created_at"`
}

type AiAssistantDocument struct {
	ID        uuid.UUID `json:"id"`
	SessionID uuid.UUID `json:"session_id"`
	Filename  string    `json:"filename"`
	MimeType  string    `json:"mime_type"`
	CharCount int32     `json:"char_count"`
	Truncated bool      `json:"truncated"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type AiAssistantLlmSetting struct {
	UserID    uuid.UUID `json:"user_id"`
	Provider  string    `json:"provider"`
	Model     string    `json:"model"`
	ApiKeyEnc *string   `json:"api_key_enc"`
	UpdatedAt time.Time `json:"updated_at"`
}

type AiAssistantMessage struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	Role       string    `json:"role"`
	Content    string    `json:"content"`
	ToolCalls  []byte    `json:"tool_calls"`
	ToolCallID *string   `json:"tool_call_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type AiAssistantProposal struct {
	ID         uuid.UUID          `json:"id"`
	SessionID  uuid.UUID          `json:"session_id"`
	Steps      json.RawMessage    `json:"steps"`
	Status     string             `json:"status"`
	CreatedAt  time.Time          `json:"created_at"`
	ExecutedAt pgtype.Timestamptz `json:"executed_at"`
}

type AiAssistantSession struct {
	ID              uuid.UUID   `json:"id"`
	ApplicationID   uuid.UUID   `json:"application_id"`
	UserID          uuid.UUID   `json:"user_id"`
	CreatedAt       time.Time   `json:"created_at"`
	LlmProvider     string      `json:"llm_provider"`
	LlmModel        string      `json:"llm_model"`
	DraftRevisionID pgtype.UUID `json:"draft_revision_id"`
	Title           string      `json:"title"`
}

type AiAssistantTenantLlmSetting struct {
	Provider   string      `json:"provider"`
	Model      string      `json:"model"`
	ApiKeyEnc  string      `json:"api_key_enc"`
	Enforced   bool        `json:"enforced"`
	UpdatedAt  time.Time   `json:"updated_at"`
	CustomerID pgtype.UUID `json:"customer_id"`
}

type AuditAuditEvent struct {
	ID            uuid.UUID          `json:"id"`
	Category      AuditEventCategory `json:"category"`
	EventType     string             `json:"event_type"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	ActorRole     *string            `json:"actor_role"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ResourceType  *string            `json:"resource_type"`
	ResourceID    *string            `json:"resource_id"`
	Metadata      json.RawMessage    `json:"metadata"`
	BeforeState   []byte             `json:"before_state"`
	AfterState    []byte             `json:"after_state"`
	OccurredAt    time.Time          `json:"occurred_at"`
	RevisionID    pgtype.UUID        `json:"revision_id"`
	ApplicationID pgtype.UUID        `json:"application_id"`
}

type AuditAuditEventDefault struct {
	ID           uuid.UUID          `json:"id"`
	Category     AuditEventCategory `json:"category"`
	EventType    string             `json:"event_type"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	ActorRole    *string            `json:"actor_role"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   *string            `json:"resource_id"`
	Metadata     json.RawMessage    `json:"metadata"`
	BeforeState  []byte             `json:"before_state"`
	AfterState   []byte             `json:"after_state"`
	OccurredAt   time.Time          `json:"occurred_at"`
}

type AuditPartitionRegistry struct {
	PartitionName string    `json:"partition_name"`
	RangeStart    time.Time `json:"range_start"`
	RangeEnd      time.Time `json:"range_end"`
	CreatedAt     time.Time `json:"created_at"`
}

type AuditSetting struct {
	RetentionDays int32       `json:"retention_days"`
	UpdatedAt     time.Time   `json:"updated_at"`
	CustomerID    pgtype.UUID `json:"customer_id"`
}

type CoreApplication struct {
	ID             uuid.UUID             `json:"id"`
	WorkspaceID    pgtype.UUID           `json:"workspace_id"`
	Name           string                `json:"name"`
	Mode           CoreApplicationMode   `json:"mode"`
	Status         CoreApplicationStatus `json:"status"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      time.Time             `json:"updated_at"`
	CustomerID     pgtype.UUID           `json:"customer_id"`
	DefaultModelID pgtype.UUID           `json:"default_model_id"`
}

type CoreBranding struct {
	CustomerID     uuid.UUID `json:"customer_id"`
	ProductName    string    `json:"product_name"`
	Tagline        string    `json:"tagline"`
	LogoDataUrl    string    `json:"logo_data_url"`
	FaviconDataUrl string    `json:"favicon_data_url"`
	BrandColor     string    `json:"brand_color"`
	EmailFromName  string    `json:"email_from_name"`
	CustomDomain   string    `json:"custom_domain"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type CoreCustomer struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Plan           string             `json:"plan"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	LimitState     string             `json:"limit_state"`
	LimitReason    string             `json:"limit_reason"`
	UsageCheckedAt pgtype.Timestamptz `json:"usage_checked_at"`
}

type CoreModel struct {
	ID                 uuid.UUID       `json:"id"`
	ApplicationID      uuid.UUID       `json:"application_id"`
	Name               string          `json:"name"`
	StorageType        CoreStorageType `json:"storage_type"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
	ActiveRevisionName *string         `json:"active_revision_name"`
	ActiveRevisionID   pgtype.UUID     `json:"active_revision_id"`
}

type CoreSchemaVersion struct {
	ID            uuid.UUID          `json:"id"`
	ModelID       uuid.UUID          `json:"model_id"`
	VersionNumber int32              `json:"version_number"`
	SchemaHash    string             `json:"schema_hash"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type CoreTenantCredential struct {
	CustomerID uuid.UUID       `json:"customer_id"`
	Kind       string          `json:"kind"`
	Meta       json.RawMessage `json:"meta"`
	SecretEnc  string          `json:"secret_enc"`
	CreatedBy  pgtype.UUID     `json:"created_by"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type CoreWorkspace struct {
	ID         uuid.UUID       `json:"id"`
	CustomerID uuid.UUID       `json:"customer_id"`
	Name       string          `json:"name"`
	Settings   json.RawMessage `json:"settings"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type DeploymentSchemaMigration struct {
	ID            uuid.UUID          `json:"id"`
	ModelID       uuid.UUID          `json:"model_id"`
	RevisionID    pgtype.UUID        `json:"revision_id"`
	VersionNumber int32              `json:"version_number"`
	Status        string             `json:"status"`
	Files         json.RawMessage    `json:"files"`
	Error         *string            `json:"error"`
	CreatedAt     time.Time          `json:"created_at"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
	RolledBackAt  pgtype.Timestamptz `json:"rolled_back_at"`
}

type IdentityApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type IdentityBusinessRole struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
	ExternalID  *string   `json:"external_id"`
}

type IdentityBusinessRoleDashboard struct {
	RoleID      uuid.UUID `json:"role_id"`
	DashboardID uuid.UUID `json:"dashboard_id"`
}

type IdentityBusinessRoleMember struct {
	RoleID uuid.UUID `json:"role_id"`
	UserID uuid.UUID `json:"user_id"`
}

type IdentityRoleAssignment struct {
	ID          uuid.UUID        `json:"id"`
	UserID      uuid.UUID        `json:"user_id"`
	Role        IdentityUserRole `json:"role"`
	WorkspaceID pgtype.UUID      `json:"workspace_id"`
	AssignedBy  pgtype.UUID      `json:"assigned_by"`
	AssignedAt  time.Time        `json:"assigned_at"`
}

type IdentityScimToken struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	DefaultRole IdentityUserRole   `json:"default_role"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
}

type IdentitySsoProvider struct {
	Alias           string           `json:"alias"`
	Protocol        string           `json:"protocol"`
	DisplayName     string           `json:"display_name"`
	MetadataUrl     string           `json:"metadata_url"`
	ClientID        string           `json:"client_id"`
	AllowedDomains  []string         `json:"allowed_domains"`
	JitProvisioning bool             `json:"jit_provisioning"`
	DefaultRole     IdentityUserRole `json:"default_role"`
	Enabled         bool             `json:"enabled"`
	UpdatedAt       time.Time        `json:"updated_at"`
	CustomerID      pgtype.UUID      `json:"customer_id"`
}

type IdentityUser struct {
	ID          uuid.UUID          `json:"id"`
	KeycloakSub string             `json:"keycloak_sub"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	DisabledAt  pgtype.Timestamptz `json:"disabled_at"`
	ExternalID  *string            `json:"external_id"`
	ScimManaged bool               `json:"scim_managed"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type IdentityUserAccessRule struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	RuleType  string    `json:"rule_type"`
	RefID     string    `json:"ref_id"`
	Access    string    `json:"access"`
	CreatedAt time.Time `json:"created_at"`
}

type IdentityUserAppAccess struct {
	UserID        uuid.UUID `json:"user_id"`
	ApplicationID uuid.UUID `json:"application_id"`
}

type IdentityUserModelAccess struct {
	UserID  uuid.UUID `json:"user_id"`
	ModelID uuid.UUID `json:"model_id"`
}

type ImportImportError struct {
	ID         uuid.UUID `json:"id"`
	JobID      uuid.UUID `json:"job_id"`
	RowNumber  int32     `json:"row_number"`
	ColumnName *string   `json:"column_name"`
	ErrorCode  string    `json:"error_code"`
	Message    string    `json:"message"`
	RawValue   *string   `json:"raw_value"`
	CreatedAt  time.Time `json:"created_at"`
}

type ImportImportJob struct {
	ID          uuid.UUID          `json:"id"`
	ModelID     uuid.UUID          `json:"model_id"`
	Status      ImportImportStatus `json:"status"`
	Mappings    json.RawMessage    `json:"mappings"`
	FileUrl     string             `json:"file_url"`
	TotalRows   int32              `json:"total_rows"`
	ValidRows   int32              `json:"valid_rows"`
	ErrorRows   int32              `json:"error_rows"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	RevisionID  pgtype.UUID        `json:"revision_id"`
}

type ImportImportStaging struct {
	ID         uuid.UUID       `json:"id"`
	JobID      uuid.UUID       `json:"job_id"`
	MetricID   uuid.UUID       `json:"metric_id"`
	DimMembers json.RawMessage `json:"dim_members"`
	Value      pgtype.Numeric  `json:"value"`
	RowNumber  int32           `json:"row_number"`
	CreatedAt  time.Time       `json:"created_at"`
}

type ModelCalcDependency struct {
	ID                uuid.UUID `json:"id"`
	MetricID          uuid.UUID `json:"metric_id"`
	DependsOnMetricID uuid.UUID `json:"depends_on_metric_id"`
	DependencyType    string    `json:"dependency_type"`
	MinTimeOffset     int32     `json:"min_time_offset"`
	MaxTimeOffset     int32     `json:"max_time_offset"`
	UnboundedPast     bool      `json:"unbounded_past"`
	UnboundedFuture   bool      `json:"unbounded_future"`
}

type ModelDashboardDef struct {
	ID         uuid.UUID   `json:"id"`
	ModelID    uuid.UUID   `json:"model_id"`
	Name       string      `json:"name"`
	CreatedAt  time.Time   `json:"created_at"`
	Category   string      `json:"category"`
	FolderID   pgtype.UUID `json:"folder_id"`
	Tags       []string    `json:"tags"`
	RevisionID pgtype.UUID `json:"revision_id"`
}

type ModelDashboardFolder struct {
	ID         uuid.UUID   `json:"id"`
	ModelID    uuid.UUID   `json:"model_id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	Name       string      `json:"name"`
	CreatedAt  time.Time   `json:"created_at"`
	RevisionID pgtype.UUID `json:"revision_id"`
}

type ModelDashboardWidget struct {
	ID          uuid.UUID `json:"id"`
	DashboardID uuid.UUID `json:"dashboard_id"`
	// grid | form | automation_button | integration_button | text | image | workflow_action
	WidgetType  string  `json:"widget_type"`
	RefID       *string `json:"ref_id"`
	Content     *string `json:"content"`
	SortOrder   int32   `json:"sort_order"`
	ColStart    int16   `json:"col_start"`
	ColSpan     int16   `json:"col_span"`
	PosX        int32   `json:"pos_x"`
	PosY        int32   `json:"pos_y"`
	SizeW       int32   `json:"size_w"`
	SizeH       int32   `json:"size_h"`
	Title       *string `json:"title"`
	ShowTitle   bool    `json:"show_title"`
	WidgetProps []byte  `json:"widget_props"`
}

type ModelDimensionDef struct {
	ID                   uuid.UUID       `json:"id"`
	ModelID              uuid.UUID       `json:"model_id"`
	Name                 string          `json:"name"`
	Properties           json.RawMessage `json:"properties"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	AggRule              string          `json:"agg_rule"`
	RevisionID           pgtype.UUID     `json:"revision_id"`
	ParentDimensionID    pgtype.UUID     `json:"parent_dimension_id"`
	SourceDimensionID    pgtype.UUID     `json:"source_dimension_id"`
	SourceProperty       *string         `json:"source_property"`
	DimensionType        string          `json:"dimension_type"`
	TimeGranularity      *string         `json:"time_granularity"`
	FiscalYearStartMonth *int16          `json:"fiscal_year_start_month"`
}

type ModelDimensionMember struct {
	ID             uuid.UUID       `json:"id"`
	DimensionID    uuid.UUID       `json:"dimension_id"`
	Code           string          `json:"code"`
	Label          string          `json:"label"`
	ParentID       pgtype.UUID     `json:"parent_id"`
	Properties     json.RawMessage `json:"properties"`
	SortOrder      int32           `json:"sort_order"`
	CreatedAt      time.Time       `json:"created_at"`
	ParentMemberID pgtype.UUID     `json:"parent_member_id"`
	PeriodStart    pgtype.Date     `json:"period_start"`
	PeriodEnd      pgtype.Date     `json:"period_end"`
	TimeIndex      *int32          `json:"time_index"`
}

type ModelDimensionProperty struct {
	ID          uuid.UUID `json:"id"`
	DimensionID uuid.UUID `json:"dimension_id"`
	Name        string    `json:"name"`
	DataType    string    `json:"data_type"`
	CreatedAt   time.Time `json:"created_at"`
}

type ModelFormDef struct {
	ID         uuid.UUID       `json:"id"`
	ModelID    uuid.UUID       `json:"model_id"`
	Name       string          `json:"name"`
	Label      string          `json:"label"`
	Fields     json.RawMessage `json:"fields"`
	CreatedAt  time.Time       `json:"created_at"`
	RevisionID pgtype.UUID     `json:"revision_id"`
}

type ModelFormMetricMapping struct {
	ID                uuid.UUID       `json:"id"`
	ModelID           uuid.UUID       `json:"model_id"`
	FormID            uuid.UUID       `json:"form_id"`
	Name              string          `json:"name"`
	SourceField       string          `json:"source_field"`
	TargetMetricID    uuid.UUID       `json:"target_metric_id"`
	Aggregation       string          `json:"aggregation"`
	PostingStatuses   []string        `json:"posting_statuses"`
	DimensionMappings json.RawMessage `json:"dimension_mappings"`
	LivePosting       bool            `json:"live_posting"`
	CreatedAt         time.Time       `json:"created_at"`
	GridID            pgtype.UUID     `json:"grid_id"`
	RevisionID        pgtype.UUID     `json:"revision_id"`
}

type ModelGridDef struct {
	ID                 uuid.UUID   `json:"id"`
	ModelID            uuid.UUID   `json:"model_id"`
	Name               string      `json:"name"`
	CreatedAt          time.Time   `json:"created_at"`
	RevisionID         pgtype.UUID `json:"revision_id"`
	RollupSourceGridID pgtype.UUID `json:"rollup_source_grid_id"`
}

type ModelGridDimension struct {
	ID           uuid.UUID `json:"id"`
	GridID       uuid.UUID `json:"grid_id"`
	DimensionID  uuid.UUID `json:"dimension_id"`
	DisplayLevel *int32    `json:"display_level"`
}

type ModelGridMetric struct {
	ID        uuid.UUID `json:"id"`
	GridID    uuid.UUID `json:"grid_id"`
	MetricID  uuid.UUID `json:"metric_id"`
	SortOrder int32     `json:"sort_order"`
}

type ModelHierarchy struct {
	ID          uuid.UUID `json:"id"`
	ModelID     uuid.UUID `json:"model_id"`
	Name        string    `json:"name"`
	DimensionID uuid.UUID `json:"dimension_id"`
	LevelNames  []string  `json:"level_names"`
	CreatedAt   time.Time `json:"created_at"`
}

type ModelIntegrationAttempt struct {
	ID           uuid.UUID `json:"id"`
	RunID        uuid.UUID `json:"run_id"`
	Seq          int32     `json:"seq"`
	Page         int32     `json:"page"`
	Method       string    `json:"method"`
	UrlSanitized string    `json:"url_sanitized"`
	HttpStatus   int32     `json:"http_status"`
	DurationMs   int32     `json:"duration_ms"`
	ErrorCode    string    `json:"error_code"`
	Message      string    `json:"message"`
	CreatedAt    time.Time `json:"created_at"`
}

type ModelIntegrationConnection struct {
	ID            uuid.UUID       `json:"id"`
	ApplicationID uuid.UUID       `json:"application_id"`
	Name          string          `json:"name"`
	AuthType      string          `json:"auth_type"`
	Meta          json.RawMessage `json:"meta"`
	SecretEnc     string          `json:"secret_enc"`
	CreatedBy     pgtype.UUID     `json:"created_by"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type ModelIntegrationDef struct {
	ID             uuid.UUID          `json:"id"`
	ModelID        uuid.UUID          `json:"model_id"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	TargetType     string             `json:"target_type"`
	TargetID       pgtype.UUID        `json:"target_id"`
	Config         json.RawMessage    `json:"config"`
	CreatedAt      time.Time          `json:"created_at"`
	RevisionID     pgtype.UUID        `json:"revision_id"`
	Status         string             `json:"status"`
	Tags           []string           `json:"tags"`
	Direction      string             `json:"direction"`
	Enabled        bool               `json:"enabled"`
	ConnectionID   pgtype.UUID        `json:"connection_id"`
	ConfigVersion  int32              `json:"config_version"`
	LastTestedHash string             `json:"last_tested_hash"`
	LastTestedAt   pgtype.Timestamptz `json:"last_tested_at"`
	Description    string             `json:"description"`
}

type ModelIntegrationOauthState struct {
	State         string      `json:"state"`
	ConnectionID  uuid.UUID   `json:"connection_id"`
	ApplicationID uuid.UUID   `json:"application_id"`
	UserID        pgtype.UUID `json:"user_id"`
	CodeVerifier  string      `json:"code_verifier"`
	ReturnTo      string      `json:"return_to"`
	CreatedAt     time.Time   `json:"created_at"`
	ExpiresAt     time.Time   `json:"expires_at"`
}

type ModelIntegrationRun struct {
	ID             uuid.UUID          `json:"id"`
	IntegrationID  uuid.UUID          `json:"integration_id"`
	Status         string             `json:"status"`
	RowsImported   int32              `json:"rows_imported"`
	ErrorRows      int32              `json:"error_rows"`
	Message        string             `json:"message"`
	RunBy          pgtype.UUID        `json:"run_by"`
	CreatedAt      time.Time          `json:"created_at"`
	TriggerType    string             `json:"trigger_type"`
	DryRun         bool               `json:"dry_run"`
	ScheduledFor   pgtype.Timestamptz `json:"scheduled_for"`
	ClaimedBy      string             `json:"claimed_by"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	AttemptCount   int32              `json:"attempt_count"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	HttpStatus     int32              `json:"http_status"`
	DurationMs     int32              `json:"duration_ms"`
	Pages          int32              `json:"pages"`
	Requests       int32              `json:"requests"`
	Retries        int32              `json:"retries"`
	RecordsRead    int32              `json:"records_read"`
	RecordsWritten int32              `json:"records_written"`
	RecordsSkipped int32              `json:"records_skipped"`
	ErrorCode      string             `json:"error_code"`
	Meta           json.RawMessage    `json:"meta"`
}

type ModelIntegrationSchedule struct {
	IntegrationID   uuid.UUID          `json:"integration_id"`
	Kind            string             `json:"kind"`
	IntervalSeconds *int32             `json:"interval_seconds"`
	CronExpr        string             `json:"cron_expr"`
	Timezone        string             `json:"timezone"`
	Enabled         bool               `json:"enabled"`
	OverlapPolicy   string             `json:"overlap_policy"`
	MisfirePolicy   string             `json:"misfire_policy"`
	EnabledBy       pgtype.UUID        `json:"enabled_by"`
	NextFireAt      pgtype.Timestamptz `json:"next_fire_at"`
	LastFireAt      pgtype.Timestamptz `json:"last_fire_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type ModelMetricDef struct {
	ID                     uuid.UUID       `json:"id"`
	ModelID                uuid.UUID       `json:"model_id"`
	Name                   string          `json:"name"`
	Formula                *string         `json:"formula"`
	StorageType            CoreStorageType `json:"storage_type"`
	IsInput                bool            `json:"is_input"`
	CreatedAt              time.Time       `json:"created_at"`
	UpdatedAt              time.Time       `json:"updated_at"`
	AggRule                string          `json:"agg_rule"`
	RevisionID             pgtype.UUID     `json:"revision_id"`
	Format                 string          `json:"format"`
	FormatDecimals         int16           `json:"format_decimals"`
	FormatCurrency         string          `json:"format_currency"`
	AggNumeratorMetricID   pgtype.UUID     `json:"agg_numerator_metric_id"`
	AggDenominatorMetricID pgtype.UUID     `json:"agg_denominator_metric_id"`
	TimeSummary            string          `json:"time_summary"`
}

type ModelRevision struct {
	ID            uuid.UUID `json:"id"`
	ModelID       uuid.UUID `json:"model_id"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	CreatedAt     time.Time `json:"created_at"`
	SystemManaged bool      `json:"system_managed"`
}

type NotificationNotification struct {
	ID              uuid.UUID               `json:"id"`
	RecipientUserID uuid.UUID               `json:"recipient_user_id"`
	Channel         NotificationChannel     `json:"channel"`
	TemplateID      string                  `json:"template_id"`
	TemplateVars    json.RawMessage         `json:"template_vars"`
	Status          NotificationNotifStatus `json:"status"`
	CreatedAt       time.Time               `json:"created_at"`
	DeliveredAt     pgtype.Timestamptz      `json:"delivered_at"`
	ResourceType    *string                 `json:"resource_type"`
	ResourceID      *string                 `json:"resource_id"`
	Attempts        int32                   `json:"attempts"`
	LastError       string                  `json:"last_error"`
	NextAttemptAt   time.Time               `json:"next_attempt_at"`
}

type NotificationSetting struct {
	EmailEnabled      bool        `json:"email_enabled"`
	WebhookEnabled    bool        `json:"webhook_enabled"`
	WebhookUrl        string      `json:"webhook_url"`
	WebhookSecret     string      `json:"webhook_secret"`
	RemindersEnabled  bool        `json:"reminders_enabled"`
	ReminderLeadHours int32       `json:"reminder_lead_hours"`
	UpdatedAt         time.Time   `json:"updated_at"`
	CustomerID        pgtype.UUID `json:"customer_id"`
}

type OpsNodeStat struct {
	ID             int64          `json:"id"`
	Node           string         `json:"node"`
	DiskTotalGb    pgtype.Numeric `json:"disk_total_gb"`
	DiskUsedGb     pgtype.Numeric `json:"disk_used_gb"`
	DiskPct        int32          `json:"disk_pct"`
	MemTotalMb     int32          `json:"mem_total_mb"`
	MemAvailableMb int32          `json:"mem_available_mb"`
	Load1          pgtype.Numeric `json:"load1"`
	CollectedAt    time.Time      `json:"collected_at"`
}

type PlatformApplicationDirectory struct {
	ApplicationID uuid.UUID `json:"application_id"`
	CustomerID    uuid.UUID `json:"customer_id"`
}

type PlatformBrandingDomain struct {
	Domain     string    `json:"domain"`
	CustomerID uuid.UUID `json:"customer_id"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type PlatformPlan struct {
	Key         string          `json:"key"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	SelfService bool            `json:"self_service"`
	Limits      json.RawMessage `json:"limits"`
	SortOrder   int32           `json:"sort_order"`
	UpdatedAt   time.Time       `json:"updated_at"`
	LimitNote   string          `json:"limit_note"`
}

type PlatformSsoDomain struct {
	Domain     string    `json:"domain"`
	CustomerID uuid.UUID `json:"customer_id"`
	Alias      string    `json:"alias"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type PlatformTenantDatabase struct {
	CustomerID uuid.UUID `json:"customer_id"`
	Name       string    `json:"name"`
	Plan       string    `json:"plan"`
	Database   string    `json:"database"`
	Status     string    `json:"status"`
	Error      string    `json:"error"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type PlatformUserDirectory struct {
	KeycloakSub string    `json:"keycloak_sub"`
	CustomerID  uuid.UUID `json:"customer_id"`
	Email       string    `json:"email"`
	CreatedAt   time.Time `json:"created_at"`
}

type RuntimeCalcResult struct {
	ID           uuid.UUID       `json:"id"`
	ModelID      uuid.UUID       `json:"model_id"`
	RevisionName *string         `json:"revision_name"`
	DimMembers   json.RawMessage `json:"dim_members"`
	MetricID     uuid.UUID       `json:"metric_id"`
	Value        pgtype.Numeric  `json:"value"`
	PartitionKey string          `json:"partition_key"`
	CalcAt       time.Time       `json:"calc_at"`
	RevisionID   uuid.UUID       `json:"revision_id"`
}

type RuntimeCalcResultDefault struct {
	ID           uuid.UUID       `json:"id"`
	ModelID      uuid.UUID       `json:"model_id"`
	RevisionName *string         `json:"revision_name"`
	Version      *string         `json:"version"`
	DimMembers   json.RawMessage `json:"dim_members"`
	MetricID     uuid.UUID       `json:"metric_id"`
	Value        pgtype.Numeric  `json:"value"`
	PartitionKey string          `json:"partition_key"`
	CalcAt       time.Time       `json:"calc_at"`
}

type RuntimeFactInput struct {
	ID           uuid.UUID       `json:"id"`
	ModelID      uuid.UUID       `json:"model_id"`
	RevisionName *string         `json:"revision_name"`
	DimMembers   json.RawMessage `json:"dim_members"`
	MetricID     uuid.UUID       `json:"metric_id"`
	Value        pgtype.Numeric  `json:"value"`
	EnteredBy    pgtype.UUID     `json:"entered_by"`
	EnteredAt    time.Time       `json:"entered_at"`
	RevisionID   uuid.UUID       `json:"revision_id"`
	SourceRef    pgtype.UUID     `json:"source_ref"`
}

type RuntimeFactInputDefault struct {
	ID           uuid.UUID       `json:"id"`
	ModelID      uuid.UUID       `json:"model_id"`
	RevisionName *string         `json:"revision_name"`
	Version      *string         `json:"version"`
	DimMembers   json.RawMessage `json:"dim_members"`
	MetricID     uuid.UUID       `json:"metric_id"`
	Value        pgtype.Numeric  `json:"value"`
	EnteredBy    pgtype.UUID     `json:"entered_by"`
	EnteredAt    time.Time       `json:"entered_at"`
}

type RuntimeFactInputHistory struct {
	ID           uuid.UUID       `json:"id"`
	ModelID      uuid.UUID       `json:"model_id"`
	RevisionID   pgtype.UUID     `json:"revision_id"`
	MetricID     uuid.UUID       `json:"metric_id"`
	DimMembers   json.RawMessage `json:"dim_members"`
	Value        pgtype.Numeric  `json:"value"`
	EnteredBy    pgtype.UUID     `json:"entered_by"`
	EnteredAt    time.Time       `json:"entered_at"`
	SourceRef    pgtype.UUID     `json:"source_ref"`
	DeletedAt    time.Time       `json:"deleted_at"`
	DeleteReason string          `json:"delete_reason"`
}

type RuntimeFormRecord struct {
	ID        uuid.UUID           `json:"id"`
	FormID    uuid.UUID           `json:"form_id"`
	Data      json.RawMessage     `json:"data"`
	Status    RuntimeRecordStatus `json:"status"`
	CreatedBy pgtype.UUID         `json:"created_by"`
	CreatedAt time.Time           `json:"created_at"`
	UpdatedAt time.Time           `json:"updated_at"`
}

type RuntimeFormRecordPosting struct {
	ID             uuid.UUID       `json:"id"`
	MappingID      uuid.UUID       `json:"mapping_id"`
	FormRecordID   uuid.UUID       `json:"form_record_id"`
	TargetMetricID uuid.UUID       `json:"target_metric_id"`
	DimMembers     json.RawMessage `json:"dim_members"`
	PostedValue    pgtype.Numeric  `json:"posted_value"`
	PostedAt       time.Time       `json:"posted_at"`
	RevisionID     pgtype.UUID     `json:"revision_id"`
}

type RuntimeMetricPartitionState struct {
	PartitionKey  string                 `json:"partition_key"`
	ModelID       uuid.UUID              `json:"model_id"`
	MetricID      uuid.UUID              `json:"metric_id"`
	TimePartition string                 `json:"time_partition"`
	Status        RuntimePartitionStatus `json:"status"`
	LastCalcAt    pgtype.Timestamptz     `json:"last_calc_at"`
	Error         *string                `json:"error"`
	UpdatedAt     time.Time              `json:"updated_at"`
	RevisionID    pgtype.UUID            `json:"revision_id"`
}

type SecurityAbacRule struct {
	ID            uuid.UUID              `json:"id"`
	ApplicationID uuid.UUID              `json:"application_id"`
	Name          string                 `json:"name"`
	Expression    string                 `json:"expression"`
	Actions       []SecurityPolicyAction `json:"actions"`
	ResourceType  string                 `json:"resource_type"`
	CreatedAt     time.Time              `json:"created_at"`
	UpdatedAt     time.Time              `json:"updated_at"`
}

type SecurityCellPolicy struct {
	ID            uuid.UUID       `json:"id"`
	ApplicationID uuid.UUID       `json:"application_id"`
	UserID        uuid.UUID       `json:"user_id"`
	MetricID      uuid.UUID       `json:"metric_id"`
	DimMembers    json.RawMessage `json:"dim_members"`
	CanRead       bool            `json:"can_read"`
	CanWrite      bool            `json:"can_write"`
	CreatedAt     time.Time       `json:"created_at"`
}

type SecurityDimensionMemberPolicy struct {
	ID                 uuid.UUID `json:"id"`
	ApplicationID      uuid.UUID `json:"application_id"`
	UserID             uuid.UUID `json:"user_id"`
	DimensionID        uuid.UUID `json:"dimension_id"`
	AllowedMemberCodes []string  `json:"allowed_member_codes"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type SecurityMetricPolicy struct {
	ID            uuid.UUID `json:"id"`
	ApplicationID uuid.UUID `json:"application_id"`
	UserID        uuid.UUID `json:"user_id"`
	MetricID      uuid.UUID `json:"metric_id"`
	CanRead       bool      `json:"can_read"`
	CanWrite      bool      `json:"can_write"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type SecurityRaciRule struct {
	ID              uuid.UUID        `json:"id"`
	ApplicationID   uuid.UUID        `json:"application_id"`
	UserID          uuid.UUID        `json:"user_id"`
	ResourcePattern string           `json:"resource_pattern"`
	RaciType        SecurityRaciType `json:"raci_type"`
	CreatedAt       time.Time        `json:"created_at"`
}

type StorageObject struct {
	ID             uuid.UUID   `json:"id"`
	Bucket         string      `json:"bucket"`
	ObjectKey      string      `json:"object_key"`
	ContentType    string      `json:"content_type"`
	SizeBytes      int64       `json:"size_bytes"`
	ChecksumSha256 string      `json:"checksum_sha256"`
	OwnerType      string      `json:"owner_type"`
	OwnerID        string      `json:"owner_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type WorkflowAutomationRule struct {
	ID                  uuid.UUID           `json:"id"`
	ApplicationID       uuid.UUID           `json:"application_id"`
	Name                string              `json:"name"`
	Description         *string             `json:"description"`
	TriggerType         WorkflowTriggerType `json:"trigger_type"`
	WorkflowName        string              `json:"workflow_name"`
	Enabled             bool                `json:"enabled"`
	CreatedAt           time.Time           `json:"created_at"`
	WorkflowDefID       pgtype.UUID         `json:"workflow_def_id"`
	SourceFormID        pgtype.UUID         `json:"source_form_id"`
	SourceGridID        pgtype.UUID         `json:"source_grid_id"`
	RevisionID          pgtype.UUID         `json:"revision_id"`
	CronExpr            *string             `json:"cron_expr"`
	Timezone            string              `json:"timezone"`
	MisfirePolicy       string              `json:"misfire_policy"`
	MaxRetries          int32               `json:"max_retries"`
	RetryBackoffSeconds int32               `json:"retry_backoff_seconds"`
	NextFireAt          pgtype.Timestamptz  `json:"next_fire_at"`
	LastFireAt          pgtype.Timestamptz  `json:"last_fire_at"`
	SourceIntegrationID pgtype.UUID         `json:"source_integration_id"`
}

type WorkflowExecution struct {
	ID             uuid.UUID               `json:"id"`
	RuleID         pgtype.UUID             `json:"rule_id"`
	ApplicationID  uuid.UUID               `json:"application_id"`
	Status         WorkflowExecutionStatus `json:"status"`
	TriggerPayload json.RawMessage         `json:"trigger_payload"`
	InstanceID     pgtype.UUID             `json:"instance_id"`
	Error          *string                 `json:"error"`
	StartedAt      time.Time               `json:"started_at"`
	CompletedAt    pgtype.Timestamptz      `json:"completed_at"`
	ScheduledFor   pgtype.Timestamptz      `json:"scheduled_for"`
	ClaimedBy      *string                 `json:"claimed_by"`
}

type WorkflowWorkflowDef struct {
	ID                   uuid.UUID          `json:"id"`
	ApplicationID        uuid.UUID          `json:"application_id"`
	Name                 string             `json:"name"`
	TriggerEvent         string             `json:"trigger_event"`
	Steps                json.RawMessage    `json:"steps"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	Description          string             `json:"description"`
	Status               string             `json:"status"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	ContextSchema        json.RawMessage    `json:"context_schema"`
	SubjectType          string             `json:"subject_type"`
	SubjectConfig        json.RawMessage    `json:"subject_config"`
	RevisionID           pgtype.UUID        `json:"revision_id"`
	SingleActiveInstance bool               `json:"single_active_instance"`
}

type WorkflowWorkflowInstance struct {
	ID                    uuid.UUID              `json:"id"`
	WorkflowDefID         uuid.UUID              `json:"workflow_def_id"`
	Status                WorkflowWorkflowStatus `json:"status"`
	StartedBy             pgtype.UUID            `json:"started_by"`
	Context               json.RawMessage        `json:"context"`
	StartedAt             time.Time              `json:"started_at"`
	CompletedAt           pgtype.Timestamptz     `json:"completed_at"`
	TestRun               bool                   `json:"test_run"`
	StepsSnapshot         []byte                 `json:"steps_snapshot"`
	ContextSchemaSnapshot []byte                 `json:"context_schema_snapshot"`
}

type WorkflowWorkflowStep struct {
	ID             uuid.UUID          `json:"id"`
	InstanceID     uuid.UUID          `json:"instance_id"`
	StepDefID      string             `json:"step_def_id"`
	Status         WorkflowStepStatus `json:"status"`
	AssigneeUserID pgtype.UUID        `json:"assignee_user_id"`
	Decision       *string            `json:"decision"`
	Comment        *string            `json:"comment"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      time.Time          `json:"created_at"`
	ReworkCount    int32              `json:"rework_count"`
	RemindedAt     pgtype.Timestamptz `json:"reminded_at"`
}
