// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package tenantdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO core.application (workspace_id, name, mode)
VALUES ($1, $2, $3) RETURNING id, workspace_id, name, mode, status, created_at, updated_at, customer_id, default_model_id
`

type CreateApplicationParams struct {
	WorkspaceID pgtype.UUID         `json:"workspace_id"`
	Name        string              `json:"name"`
	Mode        CoreApplicationMode `json:"mode"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (CoreApplication, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.WorkspaceID, arg.Name, arg.Mode)
	var i CoreApplication
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerID,
		&i.DefaultModelID,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO core.customer (name, plan)
VALUES ($1, $2) RETURNING id, name, plan, created_at, updated_at, limit_state, limit_reason, usage_checked_at
`

type CreateCustomerParams struct {
	Name string `json:"name"`
	Plan string `json:"plan"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (CoreCustomer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.Plan)
	var i CoreCustomer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LimitState,
		&i.LimitReason,
		&i.UsageCheckedAt,
	)
	return i, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO core.model (application_id, name, storage_type)
VALUES ($1, $2, $3) RETURNING id, application_id, name, storage_type, created_at, updated_at, active_revision_name, active_revision_id
`

type CreateModelParams struct {
	ApplicationID uuid.UUID       `json:"application_id"`
	Name          string          `json:"name"`
	StorageType   CoreStorageType `json:"storage_type"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (CoreModel, error) {
	row := q.db.QueryRow(ctx, createModel, arg.ApplicationID, arg.Name, arg.StorageType)
	var i CoreModel
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRevisionName,
		&i.ActiveRevisionID,
	)
	return i, err
}

const createRevision = `-- name: CreateRevision :one
INSERT INTO core.schema_version (model_id, version_number, schema_hash)
VALUES ($1, $2, $3) RETURNING id, model_id, version_number, schema_hash, published_at, created_at
`

type CreateRevisionParams struct {
	ModelID       uuid.UUID `json:"model_id"`
	VersionNumber int32     `json:"version_number"`
	SchemaHash    string    `json:"schema_hash"`
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (CoreSchemaVersion, error) {
	row := q.db.QueryRow(ctx, createRevision, arg.ModelID, arg.VersionNumber, arg.SchemaHash)
	var i CoreSchemaVersion
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.VersionNumber,
		&i.SchemaHash,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO core.workspace (customer_id, name, settings)
VALUES ($1, $2, $3) RETURNING id, customer_id, name, settings, created_at, updated_at
`

type CreateWorkspaceParams struct {
	CustomerID uuid.UUID       `json:"customer_id"`
	Name       string          `json:"name"`
	Settings   json.RawMessage `json:"settings"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (CoreWorkspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.CustomerID, arg.Name, arg.Settings)
	var i CoreWorkspace
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, workspace_id, name, mode, status, created_at, updated_at
FROM core.application WHERE id = $1
`

type GetApplicationRow struct {
	ID          uuid.UUID             `json:"id"`
	WorkspaceID pgtype.UUID           `json:"workspace_id"`
	Name        string                `json:"name"`
	Mode        CoreApplicationMode   `json:"mode"`
	Status      CoreApplicationStatus `json:"status"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, plan, created_at, updated_at
FROM core.customer WHERE id = $1
`

type GetCustomerRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Plan      string    `json:"plan"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (GetCustomerRow, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i GetCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRevision = `-- name: GetLatestRevision :one
SELECT id, model_id, version_number, schema_hash, published_at, created_at
FROM core.schema_version
WHERE model_id = $1
ORDER BY version_number DESC LIMIT 1
`

func (q *Queries) GetLatestRevision(ctx context.Context, modelID uuid.UUID) (CoreSchemaVersion, error) {
	row := q.db.QueryRow(ctx, getLatestRevision, modelID)
	var i CoreSchemaVersion
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.VersionNumber,
		&i.SchemaHash,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getModel = `-- name: GetModel :one
SELECT id, application_id, name, storage_type, created_at, updated_at
FROM core.model WHERE id = $1
`

type GetModelRow struct {
	ID            uuid.UUID       `json:"id"`
	ApplicationID uuid.UUID       `json:"application_id"`
	Name          string          `json:"name"`
	StorageType   CoreStorageType `json:"storage_type"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

func (q *Queries) GetModel(ctx context.Context, id uuid.UUID) (GetModelRow, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i GetModelRow
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Name,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, customer_id, name, settings, created_at, updated_at
FROM core.workspace WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (CoreWorkspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i CoreWorkspace
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationsByWorkspace = `-- name: ListApplicationsByWorkspace :many
SELECT id, workspace_id, name, mode, status, created_at, updated_at
FROM core.application WHERE workspace_id = $1 ORDER BY name
`

type ListApplicationsByWorkspaceRow struct {
	ID          uuid.UUID             `json:"id"`
	WorkspaceID pgtype.UUID           `json:"workspace_id"`
	Name        string                `json:"name"`
	Mode        CoreApplicationMode   `json:"mode"`
	Status      CoreApplicationStatus `json:"status"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

func (q *Queries) ListApplicationsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListApplicationsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsByWorkspaceRow
	for rows.Next() {
		var i ListApplicationsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Mode,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, plan, created_at, updated_at
FROM core.customer ORDER BY name LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListCustomersRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Plan      string    `json:"plan"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ListCustomersRow, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersRow
	for rows.Next() {
		var i ListCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Plan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByApplication = `-- name: ListModelsByApplication :many
SELECT id, application_id, name, storage_type, created_at, updated_at
FROM core.model WHERE application_id = $1 ORDER BY name
`

type ListModelsByApplicationRow struct {
	ID            uuid.UUID       `json:"id"`
	ApplicationID uuid.UUID       `json:"application_id"`
	Name          string          `json:"name"`
	StorageType   CoreStorageType `json:"storage_type"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

func (q *Queries) ListModelsByApplication(ctx context.Context, applicationID uuid.UUID) ([]ListModelsByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listModelsByApplication, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsByApplicationRow
	for rows.Next() {
		var i ListModelsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Name,
			&i.StorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByCustomer = `-- name: ListWorkspacesByCustomer :many
SELECT id, customer_id, name, settings, created_at, updated_at
FROM core.workspace WHERE customer_id = $1 ORDER BY name
`

func (q *Queries) ListWorkspacesByCustomer(ctx context.Context, customerID uuid.UUID) ([]CoreWorkspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreWorkspace
	for rows.Next() {
		var i CoreWorkspace
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Name,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishRevision = `-- name: PublishRevision :one
UPDATE core.schema_version SET published_at = now()
WHERE id = $1 RETURNING id, model_id, version_number, schema_hash, published_at, created_at
`

func (q *Queries) PublishRevision(ctx context.Context, id uuid.UUID) (CoreSchemaVersion, error) {
	row := q.db.QueryRow(ctx, publishRevision, id)
	var i CoreSchemaVersion
	err := row.Scan(
		&i.ID,
		&i.ModelID,
		&i.VersionNumber,
		&i.SchemaHash,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE core.customer SET name = $2, plan = $3
WHERE id = $1 RETURNING id, name, plan, created_at, updated_at, limit_state, limit_reason, usage_checked_at
`

type UpdateCustomerParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Plan string    `json:"plan"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (CoreCustomer, error) {
	row := q.db.QueryRow(ctx, updateCustomer, arg.ID, arg.Name, arg.Plan)
	var i CoreCustomer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LimitState,
		&i.LimitReason,
		&i.UsageCheckedAt,
	)
	return i, err
}
