// Code generated by ogen, DO NOT EDIT.
package oas

type ActivateRevisionRes interface {
	activateRevisionRes()
}

type AddAdminUserRoleRes interface {
	addAdminUserRoleRes()
}

type AddBARoleMemberRes interface {
	addBARoleMemberRes()
}

type AddBusinessMemberRes interface {
	addBusinessMemberRes()
}

type AddGridDimensionRes interface {
	addGridDimensionRes()
}

type AddGridMetricRes interface {
	addGridMetricRes()
}

type AdminSwitchModelLinkRes interface {
	adminSwitchModelLinkRes()
}

type ApplyMigrationRes interface {
	applyMigrationRes()
}

type CancelIntegrationRunRes interface {
	cancelIntegrationRunRes()
}

type CancelWorkflowInstanceRes interface {
	cancelWorkflowInstanceRes()
}

type ClearAuditSettingsRes interface {
	clearAuditSettingsRes()
}

type ClearNotificationSettingsRes interface {
	clearNotificationSettingsRes()
}

type ClearTenantAIKeyRes interface {
	clearTenantAIKeyRes()
}

type CompleteTaskRes interface {
	completeTaskRes()
}

type ConfirmAiProposalRes interface {
	confirmAiProposalRes()
}

type CreateAdminApplicationRes interface {
	createAdminApplicationRes()
}

type CreateAdminModelRes interface {
	createAdminModelRes()
}

type CreateAdminRevisionRes interface {
	createAdminRevisionRes()
}

type CreateAdminUserRes interface {
	createAdminUserRes()
}

type CreateAutomationRuleRes interface {
	createAutomationRuleRes()
}

type CreateBARoleRes interface {
	createBARoleRes()
}

type CreateDashboardRes interface {
	createDashboardRes()
}

type CreateDashboardWidgetRes interface {
	createDashboardWidgetRes()
}

type CreateDimensionMemberRes interface {
	createDimensionMemberRes()
}

type CreateDimensionPropertyRes interface {
	createDimensionPropertyRes()
}

type CreateDimensionRes interface {
	createDimensionRes()
}

type CreateFolderRes interface {
	createFolderRes()
}

type CreateFormMappingRes interface {
	createFormMappingRes()
}

type CreateFormRecordRes interface {
	createFormRecordRes()
}

type CreateFormRes interface {
	createFormRes()
}

type CreateGridRes interface {
	createGridRes()
}

type CreateIntegrationConnectionRes interface {
	createIntegrationConnectionRes()
}

type CreateIntegrationRes interface {
	createIntegrationRes()
}

type CreateMetricRes interface {
	createMetricRes()
}

type CreateRevisionRes interface {
	createRevisionRes()
}

type CreateScimTokenRes interface {
	createScimTokenRes()
}

type CreateTenantForDeveloperRes interface {
	createTenantForDeveloperRes()
}

type CreateTenantRes interface {
	createTenantRes()
}

type CreateWorkflowRes interface {
	createWorkflowRes()
}

type DebugCalcRes interface {
	debugCalcRes()
}

type DebugFactsRes interface {
	debugFactsRes()
}

type DeleteAdminUserRes interface {
	deleteAdminUserRes()
}

type DeleteAiDocumentRes interface {
	deleteAiDocumentRes()
}

type DeleteAiSessionRes interface {
	deleteAiSessionRes()
}

type DeleteBARoleRes interface {
	deleteBARoleRes()
}

type DeleteBusinessMemberRes interface {
	deleteBusinessMemberRes()
}

type DeleteDimensionMemberRes interface {
	deleteDimensionMemberRes()
}

type DeleteDimensionPropertyRes interface {
	deleteDimensionPropertyRes()
}

type DeleteDimensionRes interface {
	deleteDimensionRes()
}

type DeleteFormRecordRes interface {
	deleteFormRecordRes()
}

type DeleteFormRes interface {
	deleteFormRes()
}

type DeleteGoogleConnectionRes interface {
	deleteGoogleConnectionRes()
}

type DeleteImportJobRes interface {
	deleteImportJobRes()
}

type DeleteIntegrationConnectionRes interface {
	deleteIntegrationConnectionRes()
}

type DeleteRevisionRes interface {
	deleteRevisionRes()
}

type DeleteTenantRes interface {
	deleteTenantRes()
}

type DeleteWorkflowRes interface {
	deleteWorkflowRes()
}

type DiscardAiDraftRes interface {
	discardAiDraftRes()
}

type DisconnectIntegrationOAuthRes interface {
	disconnectIntegrationOAuthRes()
}

type DownloadAiConversionRes interface {
	downloadAiConversionRes()
}

type DownloadExportIntegrationRes interface {
	downloadExportIntegrationRes()
}

type DuplicateIntegrationRes interface {
	duplicateIntegrationRes()
}

type ExportAuditRes interface {
	exportAuditRes()
}

type ExportFormRecordsRes interface {
	exportFormRecordsRes()
}

type ExportGridRes interface {
	exportGridRes()
}

type ExportModelPackageRes interface {
	exportModelPackageRes()
}

type ExportModelRes interface {
	exportModelRes()
}

type GenerateDimensionPeriodsRes interface {
	generateDimensionPeriodsRes()
}

type GetAdminBrandingRes interface {
	getAdminBrandingRes()
}

type GetAiSessionRes interface {
	getAiSessionRes()
}

type GetAuditSettingsRes interface {
	getAuditSettingsRes()
}

type GetBusinessDashboardRes interface {
	getBusinessDashboardRes()
}

type GetCellHistoryRes interface {
	getCellHistoryRes()
}

type GetChartDataRes interface {
	getChartDataRes()
}

type GetConnectorSettingsRes interface {
	getConnectorSettingsRes()
}

type GetDemoRes interface {
	getDemoRes()
}

type GetFormRecordRes interface {
	getFormRecordRes()
}

type GetGoogleConnectionRes interface {
	getGoogleConnectionRes()
}

type GetGridRes interface {
	getGridRes()
}

type GetGridSeriesRes interface {
	getGridSeriesRes()
}

type GetIntegrationRes interface {
	getIntegrationRes()
}

type GetIntegrationRunRes interface {
	getIntegrationRunRes()
}

type GetLicenseRes interface {
	getLicenseRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetNotificationSettingsRes interface {
	getNotificationSettingsRes()
}

type GetSsoSettingsRes interface {
	getSsoSettingsRes()
}

type GetTenantAISettingsRes interface {
	getTenantAISettingsRes()
}

type GetUsageRes interface {
	getUsageRes()
}

type GetWorkflowDefinitionRes interface {
	getWorkflowDefinitionRes()
}

type GetWorkflowRes interface {
	getWorkflowRes()
}

type GrantAdminUserAppAccessRes interface {
	grantAdminUserAppAccessRes()
}

type GrantAdminUserModelAccessRes interface {
	grantAdminUserModelAccessRes()
}

type ImportDimensionMembersRes interface {
	importDimensionMembersRes()
}

type ImportFormRecordsRes interface {
	importFormRecordsRes()
}

type ImportModelRes interface {
	importModelRes()
}

type ImportParseWorkbookRes interface {
	importParseWorkbookRes()
}

type ImportSheetFetchRes interface {
	importSheetFetchRes()
}

type ImportTemplateWorkbookRes interface {
	importTemplateWorkbookRes()
}

type ImportUploadRes interface {
	importUploadRes()
}

type ListAiConversionsRes interface {
	listAiConversionsRes()
}

type ListAiProposalsRes interface {
	listAiProposalsRes()
}

type ListAuditEventsRes interface {
	listAuditEventsRes()
}

type ListAutomationRulesRes interface {
	listAutomationRulesRes()
}

type ListBAAvailableRes interface {
	listBAAvailableRes()
}

type ListBARoleDashboardsRes interface {
	listBARoleDashboardsRes()
}

type ListBARoleMembersRes interface {
	listBARoleMembersRes()
}

type ListBARolesRes interface {
	listBARolesRes()
}

type ListBAUsersRes interface {
	listBAUsersRes()
}

type ListBusinessFoldersRes interface {
	listBusinessFoldersRes()
}

type ListBusinessIntegrationsRes interface {
	listBusinessIntegrationsRes()
}

type ListDevPersonasRes interface {
	listDevPersonasRes()
}

type ListDeveloperFoldersRes interface {
	listDeveloperFoldersRes()
}

type ListDeveloperIntegrationsRes interface {
	listDeveloperIntegrationsRes()
}

type ListFormMappingsRes interface {
	listFormMappingsRes()
}

type ListFormRecordsRes interface {
	listFormRecordsRes()
}

type ListFormsRes interface {
	listFormsRes()
}

type ListGridsRes interface {
	listGridsRes()
}

type ListIntegrationRunsRes interface {
	listIntegrationRunsRes()
}

type ListMetricsRes interface {
	listMetricsRes()
}

type ListPlansRes interface {
	listPlansRes()
}

type ListPublicDimensionsRes interface {
	listPublicDimensionsRes()
}

type ListReadableGridsRes interface {
	listReadableGridsRes()
}

type ListScimTokensRes interface {
	listScimTokensRes()
}

type ListUserAccessRulesRes interface {
	listUserAccessRulesRes()
}

type ListWorkflowDefinitionsRes interface {
	listWorkflowDefinitionsRes()
}

type ListWorkflowRolesRes interface {
	listWorkflowRolesRes()
}

type ListWorkflowTriggerEventsRes interface {
	listWorkflowTriggerEventsRes()
}

type ListWorkflowsRes interface {
	listWorkflowsRes()
}

type PreviewExportIntegrationRes interface {
	previewExportIntegrationRes()
}

type PreviewImportReshapeRes interface {
	previewImportReshapeRes()
}

type PromoteAiDraftRes interface {
	promoteAiDraftRes()
}

type PublishWorkflowRes interface {
	publishWorkflowRes()
}

type PutGoogleConnectionRes interface {
	putGoogleConnectionRes()
}

type RejectAiProposalRes interface {
	rejectAiProposalRes()
}

type RemoveAdminUserFromTenantRes interface {
	removeAdminUserFromTenantRes()
}

type RemoveAdminUserRoleRes interface {
	removeAdminUserRoleRes()
}

type RemoveBARoleMemberRes interface {
	removeBARoleMemberRes()
}

type RemoveBrandingRes interface {
	removeBrandingRes()
}

type RemoveGridDimensionRes interface {
	removeGridDimensionRes()
}

type RemoveSsoRes interface {
	removeSsoRes()
}

type RenameAiSessionRes interface {
	renameAiSessionRes()
}

type ReorderDimensionMembersRes interface {
	reorderDimensionMembersRes()
}

type ReorderGridMetricsRes interface {
	reorderGridMetricsRes()
}

type ResendAdminUserInvitationRes interface {
	resendAdminUserInvitationRes()
}

type RestoreWorkflowRes interface {
	restoreWorkflowRes()
}

type RevokeAdminUserAppAccessRes interface {
	revokeAdminUserAppAccessRes()
}

type RevokeAdminUserModelAccessRes interface {
	revokeAdminUserModelAccessRes()
}

type RevokeScimTokenRes interface {
	revokeScimTokenRes()
}

type RunIntegrationRes interface {
	runIntegrationRes()
}

type ScimCreateGroupRes interface {
	scimCreateGroupRes()
}

type ScimCreateUserRes interface {
	scimCreateUserRes()
}

type ScimDeleteGroupRes interface {
	scimDeleteGroupRes()
}

type ScimDeleteUserRes interface {
	scimDeleteUserRes()
}

type ScimGetGroupRes interface {
	scimGetGroupRes()
}

type ScimGetUserRes interface {
	scimGetUserRes()
}

type ScimListGroupsRes interface {
	scimListGroupsRes()
}

type ScimListUsersRes interface {
	scimListUsersRes()
}

type ScimPatchGroupRes interface {
	scimPatchGroupRes()
}

type ScimPatchUserRes interface {
	scimPatchUserRes()
}

type ScimReplaceGroupRes interface {
	scimReplaceGroupRes()
}

type ScimReplaceUserRes interface {
	scimReplaceUserRes()
}

type ScimResourceTypesRes interface {
	scimResourceTypesRes()
}

type ScimSchemasRes interface {
	scimSchemasRes()
}

type ScimServiceProviderConfigRes interface {
	scimServiceProviderConfigRes()
}

type SendAiMessageRes interface {
	sendAiMessageRes()
}

type SendNotificationTestMailRes interface {
	sendNotificationTestMailRes()
}

type SetActiveRevisionRes interface {
	setActiveRevisionRes()
}

type SetBARoleDashboardsRes interface {
	setBARoleDashboardsRes()
}

type SetDefaultModelRes interface {
	setDefaultModelRes()
}

type SetUserAccessRulesRes interface {
	setUserAccessRulesRes()
}

type SignupRes interface {
	signupRes()
}

type SsoDiscoverRes interface {
	ssoDiscoverRes()
}

type StartIntegrationOAuthRes interface {
	startIntegrationOAuthRes()
}

type StartWorkflowInstanceRes interface {
	startWorkflowInstanceRes()
}

type SubmitBudgetRes interface {
	submitBudgetRes()
}

type SwitchModelLinkSourceRes interface {
	switchModelLinkSourceRes()
}

type SyncFormMappingsRes interface {
	syncFormMappingsRes()
}

type TestGoogleConnectionRes interface {
	testGoogleConnectionRes()
}

type TestIntegrationConnectionRes interface {
	testIntegrationConnectionRes()
}

type TestIntegrationRes interface {
	testIntegrationRes()
}

type TestSsoProviderRes interface {
	testSsoProviderRes()
}

type TestTenantAISettingsRes interface {
	testTenantAISettingsRes()
}

type TriggerAutomationRuleRes interface {
	triggerAutomationRuleRes()
}

type UpdateAdminUserRes interface {
	updateAdminUserRes()
}

type UpdateAuditSettingsRes interface {
	updateAuditSettingsRes()
}

type UpdateAutomationRuleRes interface {
	updateAutomationRuleRes()
}

type UpdateBARoleRes interface {
	updateBARoleRes()
}

type UpdateBrandingRes interface {
	updateBrandingRes()
}

type UpdateBusinessMemberRes interface {
	updateBusinessMemberRes()
}

type UpdateConnectorSettingsRes interface {
	updateConnectorSettingsRes()
}

type UpdateDashboardRes interface {
	updateDashboardRes()
}

type UpdateDashboardWidgetRes interface {
	updateDashboardWidgetRes()
}

type UpdateDimensionMemberRes interface {
	updateDimensionMemberRes()
}

type UpdateDimensionPropertyRes interface {
	updateDimensionPropertyRes()
}

type UpdateDimensionRes interface {
	updateDimensionRes()
}

type UpdateFolderRes interface {
	updateFolderRes()
}

type UpdateFormMappingRes interface {
	updateFormMappingRes()
}

type UpdateFormRecordRes interface {
	updateFormRecordRes()
}

type UpdateFormRes interface {
	updateFormRes()
}

type UpdateGridRes interface {
	updateGridRes()
}

type UpdateIntegrationConfigRes interface {
	updateIntegrationConfigRes()
}

type UpdateIntegrationConnectionRes interface {
	updateIntegrationConnectionRes()
}

type UpdateIntegrationRes interface {
	updateIntegrationRes()
}

type UpdateMetricRes interface {
	updateMetricRes()
}

type UpdateMyPreferencesRes interface {
	updateMyPreferencesRes()
}

type UpdateNotificationSettingsRes interface {
	updateNotificationSettingsRes()
}

type UpdateSsoSettingsRes interface {
	updateSsoSettingsRes()
}

type UpdateTenantAISettingsRes interface {
	updateTenantAISettingsRes()
}

type UpdateTenantRes interface {
	updateTenantRes()
}

type UpdateWorkflowInstanceRes interface {
	updateWorkflowInstanceRes()
}

type UpdateWorkflowRes interface {
	updateWorkflowRes()
}

type UploadAiDocumentRes interface {
	uploadAiDocumentRes()
}

type UpsertPlanRes interface {
	upsertPlanRes()
}

type ValidateIntegrationRes interface {
	validateIntegrationRes()
}

type ValidateWorkflowRes interface {
	validateWorkflowRes()
}

type WritebackBatchRes interface {
	writebackBatchRes()
}

type WritebackRes interface {
	writebackRes()
}
