// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	"github.com/google/uuid"
	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ActivateRevision implements activateRevision operation.
//
// Make a revision the model's active revision.
//
// PUT /api/developer/revisions/{id}/activate
func (UnimplementedHandler) ActivateRevision(ctx context.Context, params ActivateRevisionParams) (r ActivateRevisionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAdminUserRole implements addAdminUserRole operation.
//
// The granting actor may only assign roles strictly below their own tier (see assignableRoles in
// internal/gateway/handler.go) — a tenant_admin can never mint another tenant_admin, for example.
//
// POST /api/admin/users/{id}/roles
func (UnimplementedHandler) AddAdminUserRole(ctx context.Context, req *AddUserRoleRequest, params AddAdminUserRoleParams) (r AddAdminUserRoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddBARoleMember implements addBARoleMember operation.
//
// Add a user to a business role.
//
// POST /api/business-admin/roles/{id}/members
func (UnimplementedHandler) AddBARoleMember(ctx context.Context, req *AddRoleMemberRequest, params AddBARoleMemberParams) (r AddBARoleMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddGridDimension implements addGridDimension operation.
//
// Add a dimension to a grid.
//
// POST /api/developer/grids/{id}/dimensions/{dimId}
func (UnimplementedHandler) AddGridDimension(ctx context.Context, params AddGridDimensionParams) (r *AddGridDimensionOK, _ error) {
	return r, ht.ErrNotImplemented
}

// AddGridMetric implements addGridMetric operation.
//
// Add a metric to a grid (a metric may belong to only one grid at a time).
//
// POST /api/developer/grids/{id}/metrics/{metricId}
func (UnimplementedHandler) AddGridMetric(ctx context.Context, params AddGridMetricParams) (r AddGridMetricRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AdminInfraNodes implements adminInfraNodes operation.
//
// Latest health sample per cluster node (disk/memory/load), fed by the node-stats DaemonSet.
//
// GET /api/admin/infra/nodes
func (UnimplementedHandler) AdminInfraNodes(ctx context.Context) (r []AdminInfraNodesOKItem, _ error) {
	return r, ht.ErrNotImplemented
}

// ApplyMigration implements applyMigration operation.
//
// Generate and immediately apply a schema migration for a model.
//
// POST /api/developer/migration/apply
func (UnimplementedHandler) ApplyMigration(ctx context.Context, req *MigrationApplyRequest) (r ApplyMigrationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ArchiveWorkflow implements archiveWorkflow operation.
//
// Archive a workflow definition.
//
// POST /api/developer/workflows/{id}/archive
func (UnimplementedHandler) ArchiveWorkflow(ctx context.Context, params ArchiveWorkflowParams) (r *WorkflowDefFull, _ error) {
	return r, ht.ErrNotImplemented
}

// BackfillFormMapping implements backfillFormMapping operation.
//
// Re-apply a form-to-metric mapping against all already-submitted records.
//
// POST /api/developer/form-integrations/{id}/backfill
func (UnimplementedHandler) BackfillFormMapping(ctx context.Context, params BackfillFormMappingParams) (r *BackfillFormMappingOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CancelIntegrationRun implements cancelIntegrationRun operation.
//
// Cancel a queued run immediately, or request cooperative cancellation of a running one.
//
// POST /api/developer/integration-runs/{runId}/cancel
func (UnimplementedHandler) CancelIntegrationRun(ctx context.Context, params CancelIntegrationRunParams) (r CancelIntegrationRunRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ClearAuditSettings implements clearAuditSettings operation.
//
// Drop the tenant's own retention so it inherits the deployment's again (administrators; enterprise).
//
// DELETE /api/admin/audit/settings
func (UnimplementedHandler) ClearAuditSettings(ctx context.Context) (r ClearAuditSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ClearNotificationSettings implements clearNotificationSettings operation.
//
// Drop the tenant's own delivery settings so it inherits the deployment's again (administrators).
//
// DELETE /api/notifications/settings
func (UnimplementedHandler) ClearNotificationSettings(ctx context.Context) (r ClearNotificationSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ClearTenantAIKey implements clearTenantAIKey operation.
//
// Remove the stored tenant key and stop enforcing it, returning the tenant to personal keys
// (administrators; enterprise).
//
// DELETE /api/admin/ai-settings/key
func (UnimplementedHandler) ClearTenantAIKey(ctx context.Context) (r ClearTenantAIKeyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteTask implements completeTask operation.
//
// Approve or reject a workflow step.
//
// POST /api/tasks/{stepId}/complete
func (UnimplementedHandler) CompleteTask(ctx context.Context, req *TaskActionRequest, params CompleteTaskParams) (r CompleteTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ConfirmAiProposal implements confirmAiProposal operation.
//
// Execute a pending proposal's write steps (lazily creates the session's draft revision on first use).
//
// POST /api/ai/sessions/{id}/proposals/{pid}/confirm
func (UnimplementedHandler) ConfirmAiProposal(ctx context.Context, params ConfirmAiProposalParams) (r ConfirmAiProposalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAdminApplication implements createAdminApplication operation.
//
// Create an application under a tenant (a tenant admin: their own tenant only).
//
// POST /api/admin/applications
func (UnimplementedHandler) CreateAdminApplication(ctx context.Context, req *CreateApplicationRequest) (r CreateAdminApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAdminModel implements createAdminModel operation.
//
// Create a model under an application (no list endpoint exists; models are reached via the tenant
// hierarchy).
//
// POST /api/admin/models
func (UnimplementedHandler) CreateAdminModel(ctx context.Context, req *CreateAdminModelRequest) (r CreateAdminModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAdminRevision implements createAdminRevision operation.
//
// Create a revision under a model, copying metrics/dimensions from the model's active (or
// NULL-revision) definitions.
//
// POST /api/admin/revisions
func (UnimplementedHandler) CreateAdminRevision(ctx context.Context, req *CreateAdminRevisionRequest) (r CreateAdminRevisionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAdminUser implements createAdminUser operation.
//
// Available to platform_admin, tenant_admin, and developer roles. Non-platform admins create users
// in their tenant scope and cannot assign platform-level roles during creation.
// Creates a real identity-provider account and emails a set-your-password invitation; no password is
// ever set server-side. The whole operation is undone if any step fails, so a user that exists can
// always sign in. When no identity provider is configured (the dev stack) the account is local-only
// and `invited` is false.
//
// POST /api/admin/users
func (UnimplementedHandler) CreateAdminUser(ctx context.Context, req *CreateAdminUserReq) (r CreateAdminUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAdminUserTrailingSlash implements createAdminUserTrailingSlash operation.
//
// A second, directly reachable route to the same adminUserAction create branch that POST
// /api/admin/users delegates into internally — not just an internal implementation detail. Kept
// for backward compatibility; prefer POST /api/admin/users.
//
// POST /api/admin/users/
func (UnimplementedHandler) CreateAdminUserTrailingSlash(ctx context.Context, req *CreateAdminUserTrailingSlashReq) (r *CreateAdminUserTrailingSlashOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAiSession implements createAiSession operation.
//
// Create a new AI assistant session, seeded with the caller's saved provider/model settings.
//
// POST /api/ai/sessions
func (UnimplementedHandler) CreateAiSession(ctx context.Context) (r *AiSession, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateAutomationRule implements createAutomationRule operation.
//
// Create an automation rule (a workflow_def_id must point at a published workflow).
//
// POST /api/automation/rules
func (UnimplementedHandler) CreateAutomationRule(ctx context.Context, req *AutomationRuleRequest) (r CreateAutomationRuleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateBARole implements createBARole operation.
//
// Create a business role in the caller's workspace.
//
// POST /api/business-admin/roles
func (UnimplementedHandler) CreateBARole(ctx context.Context, req *BARoleRequest) (r CreateBARoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDashboard implements createDashboard operation.
//
// Create a dashboard, defaulting to the model's active revision.
//
// POST /api/developer/dashboards
func (UnimplementedHandler) CreateDashboard(ctx context.Context, req *CreateDashboardRequest) (r CreateDashboardRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDashboardWidget implements createDashboardWidget operation.
//
// Add a widget to a dashboard's free canvas.
//
// POST /api/developer/dashboards/{id}/widgets
func (UnimplementedHandler) CreateDashboardWidget(ctx context.Context, req *CreateWidgetRequest, params CreateDashboardWidgetParams) (r CreateDashboardWidgetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDimension implements createDimension operation.
//
// Create a new dimension.
//
// POST /api/developer/dimensions
func (UnimplementedHandler) CreateDimension(ctx context.Context, req *CreateDimensionRequest) (r CreateDimensionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDimensionMember implements createDimensionMember operation.
//
// Add a member to a dimension (splits parent-level facts and triggers recalculation when this is the
// first child of an existing parent member).
//
// POST /api/developer/dimensions/{dimId}/members
func (UnimplementedHandler) CreateDimensionMember(ctx context.Context, req *MemberRequest, params CreateDimensionMemberParams) (r CreateDimensionMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateDimensionProperty implements createDimensionProperty operation.
//
// Define a new typed property on a dimension.
//
// POST /api/developer/dimensions/{dimId}/properties
func (UnimplementedHandler) CreateDimensionProperty(ctx context.Context, req *PropertyRequest, params CreateDimensionPropertyParams) (r *CreateDimensionPropertyOK, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFolder implements createFolder operation.
//
// Create a dashboard folder.
//
// POST /api/developer/folders
func (UnimplementedHandler) CreateFolder(ctx context.Context, req *FolderRequest) (r CreateFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateForm implements createForm operation.
//
// Create a CRUD form.
//
// POST /api/forms
func (UnimplementedHandler) CreateForm(ctx context.Context, req *CreateFormRequest) (r CreateFormRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFormMapping implements createFormMapping operation.
//
// Create a form-to-metric mapping (posts submitted form field values into a metric's facts).
//
// POST /api/developer/form-integrations
func (UnimplementedHandler) CreateFormMapping(ctx context.Context, req *CreateFormMappingRequest) (r CreateFormMappingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFormRecord implements createFormRecord operation.
//
// Submit a new record to a form (posts to any live form-metric mappings and dispatches form_submit
// automation rules).
//
// POST /api/forms/{id}/records
func (UnimplementedHandler) CreateFormRecord(ctx context.Context, req *CreateRecordRequest, params CreateFormRecordParams) (r *FormRecord, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateGrid implements createGrid operation.
//
// Create a new grid definition.
//
// POST /api/developer/grids
func (UnimplementedHandler) CreateGrid(ctx context.Context, req *CreateGridRequest) (r CreateGridRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateIntegration implements createIntegration operation.
//
// Create an integration definition.
//
// POST /api/developer/integrations
func (UnimplementedHandler) CreateIntegration(ctx context.Context, req *CreateIntegrationRequest) (r CreateIntegrationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateIntegrationConnection implements createIntegrationConnection operation.
//
// Create a connection; the secret document is sealed with mandatory AEAD and never returned.
//
// POST /api/developer/integration-connections
func (UnimplementedHandler) CreateIntegrationConnection(ctx context.Context, req *CreateIntegrationConnectionReq) (r CreateIntegrationConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMetric implements createMetric operation.
//
// Create a new metric definition.
//
// POST /api/developer/metrics
func (UnimplementedHandler) CreateMetric(ctx context.Context, req *CreateMetricRequest) (r CreateMetricRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRevision implements createRevision operation.
//
// Duplicate a revision (deep-copies metrics, dimensions, grids, dashboards, forms, workflows, and
// facts).
//
// POST /api/developer/revisions
func (UnimplementedHandler) CreateRevision(ctx context.Context, req *CreateRevisionRequest) (r CreateRevisionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateScimToken implements createScimToken operation.
//
// Issue a SCIM bearer token; the plaintext is returned once (administrators; enterprise).
//
// POST /api/admin/scim/tokens
func (UnimplementedHandler) CreateScimToken(ctx context.Context, req *ScimToken) (r CreateScimTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTenant implements createTenant operation.
//
// Create a tenant (platform_admin only) with a default workspace.
//
// POST /api/admin/tenants
func (UnimplementedHandler) CreateTenant(ctx context.Context, req *CreateTenantRequest) (r CreateTenantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTenantForDeveloper implements createTenantForDeveloper operation.
//
// Same underlying handler as POST /api/admin/tenants. Despite being reachable at a
// developer-role-gated path, tenant creation itself still requires platform_admin — a plain
// developer receives 403.
//
// POST /api/developer/applications
func (UnimplementedHandler) CreateTenantForDeveloper(ctx context.Context, req *CreateTenantRequest) (r CreateTenantForDeveloperRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWorkflow implements createWorkflow operation.
//
// Create a new workflow definition (starts in draft status, with no steps).
//
// POST /api/developer/workflows
func (UnimplementedHandler) CreateWorkflow(ctx context.Context, req *CreateWorkflowRequest, params CreateWorkflowParams) (r CreateWorkflowRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DebugCalc implements debugCalc operation.
//
// Inspect persisted runtime.calc_result rows (debugging aid) — per-metric summary, or every
// metric's row at one exact dim_members combo.
//
// GET /api/developer/debug/calc
func (UnimplementedHandler) DebugCalc(ctx context.Context, params DebugCalcParams) (r DebugCalcRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DebugFacts implements debugFacts operation.
//
// List the 50 most recently entered raw fact_input rows for a model (debugging aid).
//
// GET /api/developer/debug/facts
func (UnimplementedHandler) DebugFacts(ctx context.Context) (r DebugFactsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAdminApplication implements deleteAdminApplication operation.
//
// Delete an application.
//
// DELETE /api/admin/applications/{id}
func (UnimplementedHandler) DeleteAdminApplication(ctx context.Context, params DeleteAdminApplicationParams) (r *DeleteAdminApplicationOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAdminModel implements deleteAdminModel operation.
//
// Delete a model.
//
// DELETE /api/admin/models/{id}
func (UnimplementedHandler) DeleteAdminModel(ctx context.Context, params DeleteAdminModelParams) (r *DeleteAdminModelOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAdminRevision implements deleteAdminRevision operation.
//
// Delete a revision.
//
// DELETE /api/admin/revisions/{id}
func (UnimplementedHandler) DeleteAdminRevision(ctx context.Context, params DeleteAdminRevisionParams) (r *DeleteAdminRevisionOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAdminUser implements deleteAdminUser operation.
//
// Removes the application row and the identity-provider account. Deleting your own account is
// refused: it is not undoable from inside the product, and for the sole platform admin it would
// leave nobody able to administer users at all. Another administrator can do it.
//
// DELETE /api/admin/users/{id}
func (UnimplementedHandler) DeleteAdminUser(ctx context.Context, params DeleteAdminUserParams) (r DeleteAdminUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAiDocument implements deleteAiDocument operation.
//
// Delete a document from a session.
//
// DELETE /api/ai/sessions/{id}/documents/{docId}
func (UnimplementedHandler) DeleteAiDocument(ctx context.Context, params DeleteAiDocumentParams) (r DeleteAiDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAiSession implements deleteAiSession operation.
//
// Delete a session (and its messages/documents/proposals).
//
// DELETE /api/ai/sessions/{id}
func (UnimplementedHandler) DeleteAiSession(ctx context.Context, params DeleteAiSessionParams) (r DeleteAiSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAutomationRule implements deleteAutomationRule operation.
//
// Delete an automation rule.
//
// DELETE /api/automation/rules/{id}
func (UnimplementedHandler) DeleteAutomationRule(ctx context.Context, params DeleteAutomationRuleParams) (r *DeleteAutomationRuleOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteBARole implements deleteBARole operation.
//
// Delete a business role.
//
// DELETE /api/business-admin/roles/{id}
func (UnimplementedHandler) DeleteBARole(ctx context.Context, params DeleteBARoleParams) (r *DeleteBARoleOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDashboard implements deleteDashboard operation.
//
// Delete a dashboard.
//
// DELETE /api/developer/dashboards/{id}
func (UnimplementedHandler) DeleteDashboard(ctx context.Context, params DeleteDashboardParams) (r *DeleteDashboardOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDashboardWidget implements deleteDashboardWidget operation.
//
// Delete a dashboard widget.
//
// DELETE /api/developer/dashboards/{id}/widgets/{widgetId}
func (UnimplementedHandler) DeleteDashboardWidget(ctx context.Context, params DeleteDashboardWidgetParams) (r *DeleteDashboardWidgetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDimension implements deleteDimension operation.
//
// Delete a dimension.
//
// DELETE /api/developer/dimensions/{dimId}
func (UnimplementedHandler) DeleteDimension(ctx context.Context, params DeleteDimensionParams) (r *DeleteDimensionOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDimensionMember implements deleteDimensionMember operation.
//
// Delete a dimension member.
//
// DELETE /api/developer/dimensions/{dimId}/members/{memberId}
func (UnimplementedHandler) DeleteDimensionMember(ctx context.Context, params DeleteDimensionMemberParams) (r *DeleteDimensionMemberOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteDimensionProperty implements deleteDimensionProperty operation.
//
// Delete a dimension property.
//
// DELETE /api/developer/dimensions/{dimId}/properties/{propId}
func (UnimplementedHandler) DeleteDimensionProperty(ctx context.Context, params DeleteDimensionPropertyParams) (r *DeleteDimensionPropertyOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFolder implements deleteFolder operation.
//
// Delete a dashboard folder.
//
// DELETE /api/developer/folders/{id}
func (UnimplementedHandler) DeleteFolder(ctx context.Context, params DeleteFolderParams) (r *DeleteFolderOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteForm implements deleteForm operation.
//
// Delete a form.
//
// DELETE /api/forms/{id}
func (UnimplementedHandler) DeleteForm(ctx context.Context, params DeleteFormParams) (r *DeleteFormOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFormMapping implements deleteFormMapping operation.
//
// Delete a form-to-metric mapping.
//
// DELETE /api/developer/form-integrations/{id}
func (UnimplementedHandler) DeleteFormMapping(ctx context.Context, params DeleteFormMappingParams) (r *DeleteFormMappingOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFormRecord implements deleteFormRecord operation.
//
// Delete a form record.
//
// DELETE /api/records/{id}
func (UnimplementedHandler) DeleteFormRecord(ctx context.Context, params DeleteFormRecordParams) (r DeleteFormRecordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteGoogleConnection implements deleteGoogleConnection operation.
//
// Forget the tenant's Google service account; private sheets become unreachable again (developers
// and administrators).
//
// DELETE /api/developer/integrations/google-service-account
func (UnimplementedHandler) DeleteGoogleConnection(ctx context.Context) (r DeleteGoogleConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteGrid implements deleteGrid operation.
//
// Delete a grid.
//
// DELETE /api/developer/grids/{id}
func (UnimplementedHandler) DeleteGrid(ctx context.Context, params DeleteGridParams) (r *DeleteGridOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteImportJob implements deleteImportJob operation.
//
// Delete an import job record.
//
// DELETE /api/import/jobs/{id}
func (UnimplementedHandler) DeleteImportJob(ctx context.Context, params DeleteImportJobParams) (r DeleteImportJobRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteIntegration implements deleteIntegration operation.
//
// Delete an integration definition.
//
// DELETE /api/developer/integrations/{id}
func (UnimplementedHandler) DeleteIntegration(ctx context.Context, params DeleteIntegrationParams) (r *DeleteIntegrationOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteIntegrationConnection implements deleteIntegrationConnection operation.
//
// Delete a connection (refused while any integration references it).
//
// DELETE /api/developer/integration-connections/{id}
func (UnimplementedHandler) DeleteIntegrationConnection(ctx context.Context, params DeleteIntegrationConnectionParams) (r DeleteIntegrationConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMetric implements deleteMetric operation.
//
// Delete a metric definition.
//
// DELETE /api/developer/metrics/{id}
func (UnimplementedHandler) DeleteMetric(ctx context.Context, params DeleteMetricParams) (r *DeleteMetricOK, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRevision implements deleteRevision operation.
//
// Delete a revision (rejected if it is the model's active revision).
//
// DELETE /api/developer/revisions/{id}
func (UnimplementedHandler) DeleteRevision(ctx context.Context, params DeleteRevisionParams) (r DeleteRevisionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTenant implements deleteTenant operation.
//
// Delete a tenant and cascade-delete its applications (platform_admin only).
//
// DELETE /api/admin/tenants/{id}
func (UnimplementedHandler) DeleteTenant(ctx context.Context, params DeleteTenantParams) (r DeleteTenantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWorkflow implements deleteWorkflow operation.
//
// Delete a workflow definition.
//
// DELETE /api/developer/workflows/{id}
func (UnimplementedHandler) DeleteWorkflow(ctx context.Context, params DeleteWorkflowParams) (r DeleteWorkflowRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DiscardAiDraft implements discardAiDraft operation.
//
// Delete the session's isolated draft revision and clear the session's draft, in one server-side
// action.
//
// POST /api/ai/sessions/{id}/discard-draft
func (UnimplementedHandler) DiscardAiDraft(ctx context.Context, params DiscardAiDraftParams) (r DiscardAiDraftRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DisconnectIntegrationOAuth implements disconnectIntegrationOAuth operation.
//
// Forget the connection's tokens, keeping the client so it can be connected again.
//
// POST /api/developer/integration-connections/{id}/oauth/disconnect
func (UnimplementedHandler) DisconnectIntegrationOAuth(ctx context.Context, params DisconnectIntegrationOAuthParams) (r DisconnectIntegrationOAuthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DuplicateIntegration implements duplicateIntegration operation.
//
// Duplicate a rest_api integration (test state cleared, schedule copied disabled, no run history).
//
// POST /api/developer/integrations/{id}/duplicate
func (UnimplementedHandler) DuplicateIntegration(ctx context.Context, params DuplicateIntegrationParams) (r DuplicateIntegrationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DuplicateWorkflow implements duplicateWorkflow operation.
//
// Duplicate a workflow definition as a new draft.
//
// POST /api/developer/workflows/{id}/duplicate
func (UnimplementedHandler) DuplicateWorkflow(ctx context.Context, req OptDuplicateWorkflowRequest, params DuplicateWorkflowParams) (r *WorkflowDefFull, _ error) {
	return r, ht.ErrNotImplemented
}

// ExportAudit implements exportAudit operation.
//
// Stream the caller's audit events, oldest first, as a CSV download or JSON Lines for a collector;
// the same tenant scope as the listing (administrators; enterprise feature audit_export).
//
// GET /api/admin/audit/export
func (UnimplementedHandler) ExportAudit(ctx context.Context, params ExportAuditParams) (r ExportAuditRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ExportFormRecords implements exportFormRecords operation.
//
// Export a form's records as CSV or XLSX.
//
// GET /api/forms/{id}/export
func (UnimplementedHandler) ExportFormRecords(ctx context.Context, params ExportFormRecordsParams) (r ExportFormRecordsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ExportGrid implements exportGrid operation.
//
// Export a grid's raw input-metric values as CSV or XLSX (one row per dimension-member combination;
// round-trips through POST /api/import/upload).
//
// GET /api/grid/export
func (UnimplementedHandler) ExportGrid(ctx context.Context, params ExportGridParams) (r ExportGridRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ExportModel implements exportModel operation.
//
// Export a model revision as a self-contained transfer package (tenant admins for their own tenant,
// platform admins for any).
//
// GET /api/admin/models/{id}/export
func (UnimplementedHandler) ExportModel(ctx context.Context, params ExportModelParams) (r ExportModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ExportModelPackage implements exportModelPackage operation.
//
// Download a standalone deployment package for a model revision — a tar.gz containing the entity
// graph (package.json), the complete database migrations, a provenance manifest, and an infra-only
// docker-compose (tenant admins for their own tenant, platform admins for any).
//
// GET /api/admin/models/{id}/export/package
func (UnimplementedHandler) ExportModelPackage(ctx context.Context, params ExportModelPackageParams) (r ExportModelPackageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ExtractFormulaRefs implements extractFormulaRefs operation.
//
// Parse a formula string and return the metric/dimension names it references.
//
// POST /api/formula/refs
func (UnimplementedHandler) ExtractFormulaRefs(ctx context.Context, req *FormulaRefsRequest) (r *ExtractFormulaRefsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateDimensionPeriods implements generateDimensionPeriods operation.
//
// Bulk-generate a time dimension's periods between two dates (same validation and chronological
// indexing as single members; time dimensions only).
//
// POST /api/developer/dimensions/{dimId}/members/generate
func (UnimplementedHandler) GenerateDimensionPeriods(ctx context.Context, req *GeneratePeriodsRequest, params GenerateDimensionPeriodsParams) (r GenerateDimensionPeriodsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GenerateMigration implements generateMigration operation.
//
// Generate (but do not apply) the next schema migration for a model's current definition.
//
// POST /api/developer/migration/generate
func (UnimplementedHandler) GenerateMigration(ctx context.Context) (r *GenerateMigrationOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAdminBranding implements getAdminBranding operation.
//
// This tenant's branding (administrators; feature white_label).
//
// GET /api/admin/branding
func (UnimplementedHandler) GetAdminBranding(ctx context.Context) (r GetAdminBrandingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAdminMe implements getAdminMe operation.
//
// Get the current actor's admin identity.
//
// GET /api/admin/me
func (UnimplementedHandler) GetAdminMe(ctx context.Context) (r *GetAdminMeOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAiSession implements getAiSession operation.
//
// Get a session with its full message and document history.
//
// GET /api/ai/sessions/{id}
func (UnimplementedHandler) GetAiSession(ctx context.Context, params GetAiSessionParams) (r GetAiSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAiSettings implements getAiSettings operation.
//
// Get the caller's saved LLM provider settings.
//
// GET /api/ai/settings
func (UnimplementedHandler) GetAiSettings(ctx context.Context) (r *AiLLMSettings, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAuditSettings implements getAuditSettings operation.
//
// The audit retention policy (administrators; enterprise).
//
// GET /api/admin/audit/settings
func (UnimplementedHandler) GetAuditSettings(ctx context.Context) (r GetAuditSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBranding implements getBranding operation.
//
// The brand to apply — a signed-in caller's tenant, else the tenant registered for the request's
// host, else the platform's own (public).
//
// GET /api/branding
func (UnimplementedHandler) GetBranding(ctx context.Context) (r *BrandView, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBusinessDashboard implements getBusinessDashboard operation.
//
// Get a dashboard's widgets, if the caller may access it.
//
// GET /api/dashboards/{id}
func (UnimplementedHandler) GetBusinessDashboard(ctx context.Context, params GetBusinessDashboardParams) (r GetBusinessDashboardRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCellHistory implements getCellHistory operation.
//
// Every value one intersection held, newest first, including rows later deleted and why (any user
// who can see the cell; enterprise feature cell_history).
//
// GET /api/cells/history
func (UnimplementedHandler) GetCellHistory(ctx context.Context, params GetCellHistoryParams) (r GetCellHistoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetChartData implements getChartData operation.
//
// Evaluate a chart widget's live data against a grid's facts and calculated values.
//
// POST /api/dashboard-widgets/{id}/chart-data
func (UnimplementedHandler) GetChartData(ctx context.Context, req OptChartRuntimeRequest, params GetChartDataParams) (r GetChartDataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDemo implements getDemo operation.
//
// Get demo context (model, revision, actor for current persona).
//
// GET /api/demo
func (UnimplementedHandler) GetDemo(ctx context.Context) (r GetDemoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDeveloperModel implements getDeveloperModel operation.
//
// Get full model definition with metrics and dependencies.
//
// GET /api/developer/model
func (UnimplementedHandler) GetDeveloperModel(ctx context.Context, params GetDeveloperModelParams) (r *GetDeveloperModelOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGoogleConnection implements getGoogleConnection operation.
//
// The tenant's Google service account, public half only — the address to share sheets with
// (developers and administrators; the tenant of the application in X-App-Id).
//
// GET /api/developer/integrations/google-service-account
func (UnimplementedHandler) GetGoogleConnection(ctx context.Context) (r GetGoogleConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetGrid implements getGrid operation.
//
// Get planning grid for a revision.
//
// GET /api/grid
func (UnimplementedHandler) GetGrid(ctx context.Context, params GetGridParams) (r GetGridRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIntegration implements getIntegration operation.
//
// One integration; rest_api returns the typed definition + schedule + tested flag.
//
// GET /api/developer/integrations/{id}
func (UnimplementedHandler) GetIntegration(ctx context.Context, params GetIntegrationParams) (r GetIntegrationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIntegrationRun implements getIntegrationRun operation.
//
// One run's full state (poll while queued/running).
//
// GET /api/developer/integration-runs/{runId}
func (UnimplementedHandler) GetIntegrationRun(ctx context.Context, params GetIntegrationRunParams) (r GetIntegrationRunRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLegalInfo implements getLegalInfo operation.
//
// The operator's identity and the documents it publishes, for the terms of service and privacy
// notice a visitor reads before signing up (public; see internal/gateway/legal.go).
//
// GET /api/legal
func (UnimplementedHandler) GetLegalInfo(ctx context.Context) (r *LegalInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLicense implements getLicense operation.
//
// Report the edition in force, the features it unlocks and the full gated-feature catalog (any
// signed-in user; see pkg/license).
//
// GET /api/license
func (UnimplementedHandler) GetLicense(ctx context.Context) (r GetLicenseRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// Get the resolved actor for the current identity (no model/app context required).
//
// GET /api/me
func (UnimplementedHandler) GetMe(ctx context.Context) (r GetMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyWorkflowHistory implements getMyWorkflowHistory operation.
//
// List the 50 most recent workflow instances where the caller started the instance or was assigned a
// step.
//
// GET /api/workflow/my-history
func (UnimplementedHandler) GetMyWorkflowHistory(ctx context.Context) (r []WorkflowInstance, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNotificationSettings implements getNotificationSettings operation.
//
// Outbound notification settings for this tenant — which channels deliver, and whether overdue
// tasks are reminded (administrators).
//
// GET /api/notifications/settings
func (UnimplementedHandler) GetNotificationSettings(ctx context.Context) (r GetNotificationSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSignupOptions implements getSignupOptions operation.
//
// Whether public self-service sign-up is open on this deployment and on what terms (public; see
// internal/gateway/signup.go).
//
// GET /api/signup/options
func (UnimplementedHandler) GetSignupOptions(ctx context.Context) (r *SignupOptions, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSsoSettings implements getSsoSettings operation.
//
// This tenant's single sign-on provider (administrators; enterprise feature sso).
//
// GET /api/admin/sso
func (UnimplementedHandler) GetSsoSettings(ctx context.Context) (r GetSsoSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTenantAISettings implements getTenantAISettings operation.
//
// The tenant-level AI provider key for this tenant (administrators; enterprise feature
// tenant_ai_keys).
//
// GET /api/admin/ai-settings
func (UnimplementedHandler) GetTenantAISettings(ctx context.Context) (r GetTenantAISettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsage implements getUsage operation.
//
// Per-tenant usage — every tenant for a platform admin, their own for a tenant admin
// (administrators; enterprise feature usage_analytics).
//
// GET /api/admin/usage
func (UnimplementedHandler) GetUsage(ctx context.Context, params GetUsageParams) (r GetUsageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkflow implements getWorkflow operation.
//
// Get a workflow definition, including its full step configuration.
//
// GET /api/developer/workflows/{id}
func (UnimplementedHandler) GetWorkflow(ctx context.Context, params GetWorkflowParams) (r GetWorkflowRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkflowHistory implements getWorkflowHistory operation.
//
// List the 50 most recent workflow instances across the whole platform (business_admin only).
//
// GET /api/workflow/history
func (UnimplementedHandler) GetWorkflowHistory(ctx context.Context) (r []WorkflowInstance, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkflowInstances implements getWorkflowInstances operation.
//
// List the most recent 20 executions started from a workflow definition.
//
// GET /api/developer/workflows/{id}/instances
func (UnimplementedHandler) GetWorkflowInstances(ctx context.Context, params GetWorkflowInstancesParams) (r []WorkflowInstanceSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkflowUsage implements getWorkflowUsage operation.
//
// List the automation rules that reference a workflow definition.
//
// GET /api/developer/workflows/{id}/usage
func (UnimplementedHandler) GetWorkflowUsage(ctx context.Context, params GetWorkflowUsageParams) (r []WorkflowDefUsage, _ error) {
	return r, ht.ErrNotImplemented
}

// GrantAdminUserAppAccess implements grantAdminUserAppAccess operation.
//
// Requires platform_admin or tenant_admin. A developer may administer users but not decide who
// reaches which application.
//
// POST /api/admin/users/{id}/access/apps/{appId}
func (UnimplementedHandler) GrantAdminUserAppAccess(ctx context.Context, params GrantAdminUserAppAccessParams) (r GrantAdminUserAppAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GrantAdminUserModelAccess implements grantAdminUserModelAccess operation.
//
// Requires platform_admin or tenant_admin. A developer may administer users but not decide who
// reaches which model.
//
// POST /api/admin/users/{id}/access/models/{modelId}
func (UnimplementedHandler) GrantAdminUserModelAccess(ctx context.Context, params GrantAdminUserModelAccessParams) (r GrantAdminUserModelAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements healthz operation.
//
// Health check.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) (r *HealthzOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportDimensionMembers implements importDimensionMembers operation.
//
// One-off dimension member import (code/label/parent_code/property:<name> columns; codes
// auto-generated from labels when absent).
//
// POST /api/import/dimension-members
func (UnimplementedHandler) ImportDimensionMembers(ctx context.Context, req *ImportDimensionMembersReq) (r ImportDimensionMembersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportFormRecords implements importFormRecords operation.
//
// Bulk-create form records from an uploaded CSV or XLSX (atomic — any row failing validation
// rejects the whole file).
//
// POST /api/forms/{id}/import
func (UnimplementedHandler) ImportFormRecords(ctx context.Context, req *FormImportRequest, params ImportFormRecordsParams) (r ImportFormRecordsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportModel implements importModel operation.
//
// Import a model export package into an application, creating a new model and revision (tenant
// admins for their own tenant, platform admins for any).
//
// POST /api/admin/models/import
func (UnimplementedHandler) ImportModel(ctx context.Context, req *ModelImportRequest) (r ImportModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportSheetFetch implements importSheetFetch operation.
//
// Fetch a link-shared Google Sheet as CSV text (server-side — Google's export endpoint sends no
// CORS headers; only docs.google.com exports for the parsed spreadsheet ID are ever requested).
//
// POST /api/import/sheets/fetch
func (UnimplementedHandler) ImportSheetFetch(ctx context.Context, req *ImportSheetFetchReq) (r ImportSheetFetchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ImportUpload implements importUpload operation.
//
// Import facts from a CSV or XLSX file (atomic — any row failing validation rejects the whole file).
//
// POST /api/import/upload
func (UnimplementedHandler) ImportUpload(ctx context.Context, req *ImportUploadRequest) (r ImportUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// IntegrationOAuthCallback implements integrationOAuthCallback operation.
//
// Where the provider sends the browser after consent (public: the person arrives with the state
// only). Exchanges the code, seals the tokens into the connection, and redirects to the console with
// ?oauth=connected or ?oauth=error&oauth_error=….
//
// GET /api/integrations/oauth/callback
func (UnimplementedHandler) IntegrationOAuthCallback(ctx context.Context, params IntegrationOAuthCallbackParams) error {
	return ht.ErrNotImplemented
}

// ListAdminApplications implements listAdminApplications operation.
//
// List the applications in the caller's scope — every tenant's for a platform admin, their own
// tenant's for a tenant admin.
//
// GET /api/admin/applications
func (UnimplementedHandler) ListAdminApplications(ctx context.Context) (r []AdminApplicationItem, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAdminTenants implements listAdminTenants operation.
//
// List all tenants with app/model/revision hierarchy.
//
// GET /api/admin/tenants
func (UnimplementedHandler) ListAdminTenants(ctx context.Context) (r []AdminTenant, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAdminUsers implements listAdminUsers operation.
//
// Available to platform_admin, tenant_admin, and developer roles. Platform admins see all users;
// tenant admins and developers are scoped to reachable tenant/workspace/app/model access.
//
// GET /api/admin/users
func (UnimplementedHandler) ListAdminUsers(ctx context.Context) (r []AdminUser, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAdminWorkspaces implements listAdminWorkspaces operation.
//
// Available to platform_admin, tenant_admin, and developer roles. Results are scoped to the acting
// admin's reachable tenant/workspace scope.
//
// GET /api/admin/workspaces
func (UnimplementedHandler) ListAdminWorkspaces(ctx context.Context) (r []AdminWorkspace, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAiProposals implements listAiProposals operation.
//
// List every proposal ever made in a session, most recent first (not just pending ones) — the
// Activity panel's data source.
//
// GET /api/ai/sessions/{id}/proposals
func (UnimplementedHandler) ListAiProposals(ctx context.Context, params ListAiProposalsParams) (r ListAiProposalsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAiSessions implements listAiSessions operation.
//
// List the caller's 20 most recent AI assistant sessions for the current application.
//
// GET /api/ai/sessions
func (UnimplementedHandler) ListAiSessions(ctx context.Context) (r []AiSession, _ error) {
	return r, ht.ErrNotImplemented
}

// ListApplicationsForDeveloper implements listApplicationsForDeveloper operation.
//
// Same underlying handler as GET /api/admin/tenants; reachable by developer, platform_admin, or
// tenant_admin. A developer's results are additionally scoped to their reachable workspace/app/model
// access grants.
//
// GET /api/developer/applications
func (UnimplementedHandler) ListApplicationsForDeveloper(ctx context.Context) (r []AdminTenant, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAuditEvents implements listAuditEvents operation.
//
// Takes no query parameters. A Platform Admin sees the most recent 200 events across all tenants; a
// Tenant Admin sees only events attributable to their own customers — those whose application
// belongs to one, plus application-less events (user/tenant administration) performed by one of
// their users.
//
// GET /api/admin/audit
func (UnimplementedHandler) ListAuditEvents(ctx context.Context) (r ListAuditEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAutomationExecutions implements listAutomationExecutions operation.
//
// List the 50 most recent automation rule executions for the current application.
//
// GET /api/automation/executions
func (UnimplementedHandler) ListAutomationExecutions(ctx context.Context) (r []AutomationExecution, _ error) {
	return r, ht.ErrNotImplemented
}

// ListAutomationRules implements listAutomationRules operation.
//
// List automation rules for the current application/revision.
//
// GET /api/automation/rules
func (UnimplementedHandler) ListAutomationRules(ctx context.Context) (r []AutomationRule, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBAAvailable implements listBAAvailable operation.
//
// List dashboards, metrics, dimensions, or dimension members available for role/access configuration.
//
// GET /api/business-admin/available
func (UnimplementedHandler) ListBAAvailable(ctx context.Context, params ListBAAvailableParams) (r ListBAAvailableRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBARoleDashboards implements listBARoleDashboards operation.
//
// List the dashboard IDs assigned to a business role.
//
// GET /api/business-admin/roles/{id}/dashboards
func (UnimplementedHandler) ListBARoleDashboards(ctx context.Context, params ListBARoleDashboardsParams) (r []uuid.UUID, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBARoleMembers implements listBARoleMembers operation.
//
// List the users assigned to a business role.
//
// GET /api/business-admin/roles/{id}/members
func (UnimplementedHandler) ListBARoleMembers(ctx context.Context, params ListBARoleMembersParams) (r []BARoleMember, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBARoles implements listBARoles operation.
//
// List business roles in the caller's workspace.
//
// GET /api/business-admin/roles
func (UnimplementedHandler) ListBARoles(ctx context.Context) (r []BARole, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBAUsers implements listBAUsers operation.
//
// List business_user-role members of the caller's workspace.
//
// GET /api/business-admin/users
func (UnimplementedHandler) ListBAUsers(ctx context.Context) (r []BAUser, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBusinessDashboards implements listBusinessDashboards operation.
//
// Scoped by business-role dashboard assignment: a dashboard is visible if the caller has a business
// role it's assigned to, or if the dashboard's workspace defines no business roles at all (dev/demo
// fallback).
//
// GET /api/dashboards
func (UnimplementedHandler) ListBusinessDashboards(ctx context.Context) (r []BusinessDashboardSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBusinessFolders implements listBusinessFolders operation.
//
// List dashboard folders for a model (read-only, any authenticated user).
//
// GET /api/folders
func (UnimplementedHandler) ListBusinessFolders(ctx context.Context, params ListBusinessFoldersParams) (r ListBusinessFoldersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListBusinessIntegrations implements listBusinessIntegrations operation.
//
// List integrations visible to business users (e.g. for run-button labels).
//
// GET /api/integrations
func (UnimplementedHandler) ListBusinessIntegrations(ctx context.Context, params ListBusinessIntegrationsParams) (r ListBusinessIntegrationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDashboards implements listDashboards operation.
//
// List dashboards (with widgets) for a model, defaulting to its active revision.
//
// GET /api/developer/dashboards
func (UnimplementedHandler) ListDashboards(ctx context.Context, params ListDashboardsParams) (r []DashboardDef, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDevPersonas implements listDevPersonas operation.
//
// List every user in the database as a switchable dev persona (dev mode only — 404s in production).
//
// GET /api/dev/personas
func (UnimplementedHandler) ListDevPersonas(ctx context.Context) (r ListDevPersonasRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDeveloperFolders implements listDeveloperFolders operation.
//
// List dashboard folders for a model.
//
// GET /api/developer/folders
func (UnimplementedHandler) ListDeveloperFolders(ctx context.Context, params ListDeveloperFoldersParams) (r ListDeveloperFoldersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDeveloperIntegrations implements listDeveloperIntegrations operation.
//
// List integration definitions for a model.
//
// GET /api/developer/integrations
func (UnimplementedHandler) ListDeveloperIntegrations(ctx context.Context, params ListDeveloperIntegrationsParams) (r ListDeveloperIntegrationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDimensionProperties implements listDimensionProperties operation.
//
// List typed properties defined on a dimension.
//
// GET /api/developer/dimensions/{dimId}/properties
func (UnimplementedHandler) ListDimensionProperties(ctx context.Context, params ListDimensionPropertiesParams) (r []DimensionProperty, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDimensions implements listDimensions operation.
//
// List dimensions with members.
//
// GET /api/developer/dimensions
func (UnimplementedHandler) ListDimensions(ctx context.Context, params ListDimensionsParams) (r []Dimension, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFormMappings implements listFormMappings operation.
//
// List form-to-metric mappings for a model.
//
// GET /api/developer/form-integrations
func (UnimplementedHandler) ListFormMappings(ctx context.Context, params ListFormMappingsParams) (r ListFormMappingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListFormRecords implements listFormRecords operation.
//
// List the 100 most recent records submitted to a form.
//
// GET /api/forms/{id}/records
func (UnimplementedHandler) ListFormRecords(ctx context.Context, params ListFormRecordsParams) (r []FormRecord, _ error) {
	return r, ht.ErrNotImplemented
}

// ListForms implements listForms operation.
//
// List CRUD forms for the current model's revision.
//
// GET /api/forms
func (UnimplementedHandler) ListForms(ctx context.Context, params ListFormsParams) (r ListFormsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListGrids implements listGrids operation.
//
// List grid definitions for a model.
//
// GET /api/developer/grids
func (UnimplementedHandler) ListGrids(ctx context.Context, params ListGridsParams) (r ListGridsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListImportJobs implements listImportJobs operation.
//
// List the 20 most recent import jobs for the model.
//
// GET /api/import/jobs
func (UnimplementedHandler) ListImportJobs(ctx context.Context) (r []ImportJob, _ error) {
	return r, ht.ErrNotImplemented
}

// ListIntegrationConnections implements listIntegrationConnections operation.
//
// List reusable credential connections (public metadata + has_secret only — secrets are write-only).
//
// GET /api/developer/integration-connections
func (UnimplementedHandler) ListIntegrationConnections(ctx context.Context) (r []ListIntegrationConnectionsOKItem, _ error) {
	return r, ht.ErrNotImplemented
}

// ListIntegrationRuns implements listIntegrationRuns operation.
//
// Run history of one saved integration (most recent first, max 50).
//
// GET /api/developer/integrations/{id}/runs
func (UnimplementedHandler) ListIntegrationRuns(ctx context.Context, params ListIntegrationRunsParams) (r ListIntegrationRunsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMetrics implements listMetrics operation.
//
// List all metrics for the demo model.
//
// GET /api/metrics
func (UnimplementedHandler) ListMetrics(ctx context.Context) (r ListMetricsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListNotifications implements listNotifications operation.
//
// List the 50 most recent notifications for the current user.
//
// GET /api/notifications
func (UnimplementedHandler) ListNotifications(ctx context.Context) (r []Notification, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPlans implements listPlans operation.
//
// The plan catalog in display order (platform_admin and tenant_admin; internal/plan).
//
// GET /api/admin/plans
func (UnimplementedHandler) ListPlans(ctx context.Context) (r ListPlansRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPublicDimensions implements listPublicDimensions operation.
//
// List all dimensions with members for the current model (any authenticated user).
//
// GET /api/dimensions
func (UnimplementedHandler) ListPublicDimensions(ctx context.Context, params ListPublicDimensionsParams) (r ListPublicDimensionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRevisions implements listRevisions operation.
//
// List revisions for a model.
//
// GET /api/developer/revisions
func (UnimplementedHandler) ListRevisions(ctx context.Context, params ListRevisionsParams) (r []DevRevision, _ error) {
	return r, ht.ErrNotImplemented
}

// ListScimTokens implements listScimTokens operation.
//
// This tenant's SCIM tokens, revoked ones included, never the secret (administrators; enterprise
// feature scim).
//
// GET /api/admin/scim/tokens
func (UnimplementedHandler) ListScimTokens(ctx context.Context) (r ListScimTokensRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTasks implements listTasks operation.
//
// List pending workflow tasks for the current user.
//
// GET /api/tasks
func (UnimplementedHandler) ListTasks(ctx context.Context) (r []Task, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUserAccessRules implements listUserAccessRules operation.
//
// List a user's dimension/metric access rules.
//
// GET /api/business-admin/users/{id}/access-rules
func (UnimplementedHandler) ListUserAccessRules(ctx context.Context, params ListUserAccessRulesParams) (r []UserAccessRule, _ error) {
	return r, ht.ErrNotImplemented
}

// ListUserApps implements listUserApps operation.
//
// List applications accessible to the current user, scoped by tenant/workspace membership and
// app/model access grants.
//
// GET /api/apps
func (UnimplementedHandler) ListUserApps(ctx context.Context) (r []UserApp, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkflowDefinitions implements listWorkflowDefinitions operation.
//
// Published workflow definitions of the caller's application, with context schemas — what the
// Planning workspace renders its start-workflow dialog from.
//
// GET /api/workflow/definitions
func (UnimplementedHandler) ListWorkflowDefinitions(ctx context.Context) (r ListWorkflowDefinitionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkflowRoles implements listWorkflowRoles operation.
//
// List business roles in the application's workspace, selectable as a workflow step's
// approver/assignee.
//
// GET /api/developer/workflow-roles
func (UnimplementedHandler) ListWorkflowRoles(ctx context.Context, params ListWorkflowRolesParams) (r ListWorkflowRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkflowTriggerEvents implements listWorkflowTriggerEvents operation.
//
// List the catalog of events (system, form-submit, integration-import) that can trigger a workflow.
//
// GET /api/developer/workflow-trigger-events
func (UnimplementedHandler) ListWorkflowTriggerEvents(ctx context.Context, params ListWorkflowTriggerEventsParams) (r []TriggerEventCatalogItem, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkflows implements listWorkflows operation.
//
// List workflow definitions for an application.
//
// GET /api/developer/workflows
func (UnimplementedHandler) ListWorkflows(ctx context.Context, params ListWorkflowsParams) (r ListWorkflowsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// MarkNotificationRead implements markNotificationRead operation.
//
// Mark one or more of the caller's own notifications as read.
//
// POST /api/notifications/mark-read
func (UnimplementedHandler) MarkNotificationRead(ctx context.Context, req *MarkNotificationReadRequest) (r *MarkNotificationReadOK, _ error) {
	return r, ht.ErrNotImplemented
}

// PreviewFormMapping implements previewFormMapping operation.
//
// Preview the fact rows a mapping would currently produce, without writing them.
//
// GET /api/developer/form-integrations/{id}/preview
func (UnimplementedHandler) PreviewFormMapping(ctx context.Context, params PreviewFormMappingParams) (r []PreviewFormMappingOKItem, _ error) {
	return r, ht.ErrNotImplemented
}

// PromoteAiDraft implements promoteAiDraft operation.
//
// Make the session's isolated draft revision the model's active revision, then clear the session's
// draft.
//
// POST /api/ai/sessions/{id}/promote-draft
func (UnimplementedHandler) PromoteAiDraft(ctx context.Context, params PromoteAiDraftParams) (r PromoteAiDraftRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PublishWorkflow implements publishWorkflow operation.
//
// Publish a workflow definition (rejected if it fails validation).
//
// POST /api/developer/workflows/{id}/publish
func (UnimplementedHandler) PublishWorkflow(ctx context.Context, params PublishWorkflowParams) (r PublishWorkflowRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutGoogleConnection implements putGoogleConnection operation.
//
// Store a Google service-account key file for this tenant — the JSON Google Cloud downloaded; only
// the address and the private key are kept, sealed (developers and administrators).
//
// PUT /api/developer/integrations/google-service-account
func (UnimplementedHandler) PutGoogleConnection(ctx context.Context, req *PutGoogleConnectionReq) (r PutGoogleConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RejectAiProposal implements rejectAiProposal operation.
//
// Reject a pending proposal without executing it.
//
// POST /api/ai/sessions/{id}/proposals/{pid}/reject
func (UnimplementedHandler) RejectAiProposal(ctx context.Context, params RejectAiProposalParams) (r RejectAiProposalRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveAdminUserRole implements removeAdminUserRole operation.
//
// Mirrors the grant tier check. Additionally refused when the actor is revoking their own last grant
// of developer, tenant_admin or platform_admin — the roles that gate these endpoints — since
// nothing in the product could give it back.
//
// DELETE /api/admin/users/{id}/roles/{role}
func (UnimplementedHandler) RemoveAdminUserRole(ctx context.Context, params RemoveAdminUserRoleParams) (r RemoveAdminUserRoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveBARoleMember implements removeBARoleMember operation.
//
// Remove a user from a business role.
//
// DELETE /api/business-admin/roles/{id}/members/{userId}
func (UnimplementedHandler) RemoveBARoleMember(ctx context.Context, params RemoveBARoleMemberParams) (r *RemoveBARoleMemberOK, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveBranding implements removeBranding operation.
//
// Return the tenant to the platform's own look (administrators; feature white_label).
//
// DELETE /api/admin/branding
func (UnimplementedHandler) RemoveBranding(ctx context.Context) (r RemoveBrandingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveGridDimension implements removeGridDimension operation.
//
// Remove a dimension from a grid.
//
// DELETE /api/developer/grids/{id}/dimensions/{dimId}
func (UnimplementedHandler) RemoveGridDimension(ctx context.Context, params RemoveGridDimensionParams) (r *RemoveGridDimensionOK, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveGridMetric implements removeGridMetric operation.
//
// Remove a metric from a grid.
//
// DELETE /api/developer/grids/{id}/metrics/{metricId}
func (UnimplementedHandler) RemoveGridMetric(ctx context.Context, params RemoveGridMetricParams) (r *RemoveGridMetricOK, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveSso implements removeSso operation.
//
// Remove the tenant's identity provider from Keycloak and clear the settings (administrators;
// enterprise).
//
// DELETE /api/admin/sso
func (UnimplementedHandler) RemoveSso(ctx context.Context) (r RemoveSsoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RenameAiSession implements renameAiSession operation.
//
// Rename a session (an explicit rename always wins over auto-naming).
//
// PATCH /api/ai/sessions/{id}
func (UnimplementedHandler) RenameAiSession(ctx context.Context, req *RenameAiSessionReq, params RenameAiSessionParams) (r RenameAiSessionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResendAdminUserInvitation implements resendAdminUserInvitation operation.
//
// Invitations expire and mail gets lost; without this the only recovery is deleting and re-creating
// the user, which discards their roles and access grants. Returns 409 for users created before
// identity-provider provisioning existed — they carry a synthetic subject and have no account to
// invite.
//
// POST /api/admin/users/{id}/invite
func (UnimplementedHandler) ResendAdminUserInvitation(ctx context.Context, params ResendAdminUserInvitationParams) (r ResendAdminUserInvitationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RestoreWorkflow implements restoreWorkflow operation.
//
// Restore an archived workflow definition to draft.
//
// POST /api/developer/workflows/{id}/restore
func (UnimplementedHandler) RestoreWorkflow(ctx context.Context, params RestoreWorkflowParams) (r RestoreWorkflowRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeAdminUserAppAccess implements revokeAdminUserAppAccess operation.
//
// Requires platform_admin or tenant_admin. See grantAdminUserAppAccess.
//
// DELETE /api/admin/users/{id}/access/apps/{appId}
func (UnimplementedHandler) RevokeAdminUserAppAccess(ctx context.Context, params RevokeAdminUserAppAccessParams) (r RevokeAdminUserAppAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeAdminUserModelAccess implements revokeAdminUserModelAccess operation.
//
// Requires platform_admin or tenant_admin. See grantAdminUserModelAccess.
//
// DELETE /api/admin/users/{id}/access/models/{modelId}
func (UnimplementedHandler) RevokeAdminUserModelAccess(ctx context.Context, params RevokeAdminUserModelAccessParams) (r RevokeAdminUserModelAccessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeScimToken implements revokeScimToken operation.
//
// Revoke a SCIM token (administrators; enterprise).
//
// DELETE /api/admin/scim/tokens/{id}
func (UnimplementedHandler) RevokeScimToken(ctx context.Context, params RevokeScimTokenParams) (r RevokeScimTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RunIntegration implements runIntegration operation.
//
// Execute a saved integration against an uploaded CSV (target is a form, dimension, or grid, per the
// integration's target_type).
//
// POST /api/integrations/{id}/run
func (UnimplementedHandler) RunIntegration(ctx context.Context, req *IntegrationRunRequest, params RunIntegrationParams) (r RunIntegrationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SaveAiSettings implements saveAiSettings operation.
//
// Save the caller's LLM provider settings.
//
// PUT /api/ai/settings
func (UnimplementedHandler) SaveAiSettings(ctx context.Context, req *AiSaveSettingsRequest) (r *SaveAiSettingsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimCreateGroup implements scimCreateGroup operation.
//
// Create a business role with members (SCIM bearer token).
//
// POST /api/scim/v2/Groups
func (UnimplementedHandler) ScimCreateGroup(ctx context.Context, req ScimResource) (r ScimCreateGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimCreateUser implements scimCreateUser operation.
//
// Create a user exactly as the console's Users screen would (SCIM bearer token).
//
// POST /api/scim/v2/Users
func (UnimplementedHandler) ScimCreateUser(ctx context.Context, req ScimResource) (r ScimCreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimDeleteGroup implements scimDeleteGroup operation.
//
// Delete the business role (SCIM bearer token).
//
// DELETE /api/scim/v2/Groups/{id}
func (UnimplementedHandler) ScimDeleteGroup(ctx context.Context, params ScimDeleteGroupParams) (r ScimDeleteGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimDeleteUser implements scimDeleteUser operation.
//
// Delete the user and their identity-provider account (SCIM bearer token).
//
// DELETE /api/scim/v2/Users/{id}
func (UnimplementedHandler) ScimDeleteUser(ctx context.Context, params ScimDeleteUserParams) (r ScimDeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimGetGroup implements scimGetGroup operation.
//
// One group (SCIM bearer token).
//
// GET /api/scim/v2/Groups/{id}
func (UnimplementedHandler) ScimGetGroup(ctx context.Context, params ScimGetGroupParams) (r ScimGetGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimGetUser implements scimGetUser operation.
//
// One user (SCIM bearer token).
//
// GET /api/scim/v2/Users/{id}
func (UnimplementedHandler) ScimGetUser(ctx context.Context, params ScimGetUserParams) (r ScimGetUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimListGroups implements scimListGroups operation.
//
// List or filter this tenant's business roles as SCIM groups (SCIM bearer token).
//
// GET /api/scim/v2/Groups
func (UnimplementedHandler) ScimListGroups(ctx context.Context, params ScimListGroupsParams) (r ScimListGroupsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimListUsers implements scimListUsers operation.
//
// List or filter this tenant's users as SCIM resources (SCIM bearer token); filter supports attr eq
// "value" joined by and.
//
// GET /api/scim/v2/Users
func (UnimplementedHandler) ScimListUsers(ctx context.Context, params ScimListUsersParams) (r ScimListUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimPatchGroup implements scimPatchGroup operation.
//
// Add or remove members, rename (SCIM bearer token).
//
// PATCH /api/scim/v2/Groups/{id}
func (UnimplementedHandler) ScimPatchGroup(ctx context.Context, req ScimResource, params ScimPatchGroupParams) (r ScimPatchGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimPatchUser implements scimPatchUser operation.
//
// Apply PatchOp operations to a user; active=false deactivates sign-in immediately (SCIM bearer
// token).
//
// PATCH /api/scim/v2/Users/{id}
func (UnimplementedHandler) ScimPatchUser(ctx context.Context, req ScimResource, params ScimPatchUserParams) (r ScimPatchUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimReplaceGroup implements scimReplaceGroup operation.
//
// Replace a group's name and members (SCIM bearer token).
//
// PUT /api/scim/v2/Groups/{id}
func (UnimplementedHandler) ScimReplaceGroup(ctx context.Context, req ScimResource, params ScimReplaceGroupParams) (r ScimReplaceGroupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimReplaceUser implements scimReplaceUser operation.
//
// Replace a user's attributes (SCIM bearer token).
//
// PUT /api/scim/v2/Users/{id}
func (UnimplementedHandler) ScimReplaceUser(ctx context.Context, req ScimResource, params ScimReplaceUserParams) (r ScimReplaceUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimResourceTypes implements scimResourceTypes operation.
//
// SCIM 2.0 resource types (SCIM bearer token).
//
// GET /api/scim/v2/ResourceTypes
func (UnimplementedHandler) ScimResourceTypes(ctx context.Context) (r ScimResourceTypesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimSchemas implements scimSchemas operation.
//
// SCIM 2.0 schemas (SCIM bearer token).
//
// GET /api/scim/v2/Schemas
func (UnimplementedHandler) ScimSchemas(ctx context.Context) (r ScimSchemasRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ScimServiceProviderConfig implements scimServiceProviderConfig operation.
//
// SCIM 2.0 service provider configuration (SCIM bearer token).
//
// GET /api/scim/v2/ServiceProviderConfig
func (UnimplementedHandler) ScimServiceProviderConfig(ctx context.Context) (r ScimServiceProviderConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SendAiMessage implements sendAiMessage operation.
//
// Response is text/event-stream, not JSON — ogen/generated clients cannot consume this operation
// and callers should use a raw fetch/ EventSource instead. Named events: "delta" ({content}) for
// each streamed token; "tool_status" ({tool}) before executing a read tool; "proposal" ({proposal:
// AiProposal, messages, session}) when the model calls a write tool and a proposal is created
// instead of executing immediately; "error" ({error}) on any failure (rate limit, provider error,
// invalid proposal); "done" ({reply: AiChatMessage, messages, session}) on normal completion.
// Rate-limited to 50 LLM calls per session and 200 per user per day (429 if exceeded before any
// streaming has started — after streaming begins, limit hits are only reported via an "error"
// event since the HTTP status is already sent).
//
// POST /api/ai/sessions/{id}/messages
func (UnimplementedHandler) SendAiMessage(ctx context.Context, req *AiSendMessageRequest, params SendAiMessageParams) (r SendAiMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SendNotificationTestMail implements sendNotificationTestMail operation.
//
// Send the calling administrator a test e-mail through the deployment's relay, synchronously — the
// relay's verdict comes back as the response (administrators).
//
// POST /api/notifications/settings/test
func (UnimplementedHandler) SendNotificationTestMail(ctx context.Context) (r SendNotificationTestMailRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetActiveRevision implements setActiveRevision operation.
//
// Set a model's active revision by name.
//
// PUT /api/admin/models/{id}/active-revision
func (UnimplementedHandler) SetActiveRevision(ctx context.Context, req *ActiveRevisionRequest, params SetActiveRevisionParams) (r SetActiveRevisionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetBARoleDashboards implements setBARoleDashboards operation.
//
// Replace the full set of dashboards assigned to a business role.
//
// PUT /api/business-admin/roles/{id}/dashboards
func (UnimplementedHandler) SetBARoleDashboards(ctx context.Context, req *SetRoleDashboardsRequest, params SetBARoleDashboardsParams) (r SetBARoleDashboardsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetDefaultModel implements setDefaultModel operation.
//
// Make this model its application's business default (what business consoles resolve).
//
// POST /api/developer/models/{id}/set-default
func (UnimplementedHandler) SetDefaultModel(ctx context.Context, params SetDefaultModelParams) (r SetDefaultModelRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetUserAccessRules implements setUserAccessRules operation.
//
// Replace the full set of a user's dimension/metric access rules.
//
// PUT /api/business-admin/users/{id}/access-rules
func (UnimplementedHandler) SetUserAccessRules(ctx context.Context, req *SetUserAccessRulesRequest, params SetUserAccessRulesParams) (r SetUserAccessRulesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Signup implements signup operation.
//
// Register a tenant from the public sign-up page — the tenant on the self-service plan, its first
// administrator/developer, an application with the starter model, and an invitation to set a
// password (public, rate-limited per address).
//
// POST /api/signup
func (UnimplementedHandler) Signup(ctx context.Context, req *SignupRequest) (r SignupRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SsoDiscover implements ssoDiscover operation.
//
// Before sign-in, whether single sign-on exists and which provider an e-mail belongs to (public,
// rate-limited; answers nothing about e-mails it does not know).
//
// GET /api/sso/discover
func (UnimplementedHandler) SsoDiscover(ctx context.Context, params SsoDiscoverParams) (r SsoDiscoverRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartIntegrationOAuth implements startIntegrationOAuth operation.
//
// Begin the OAuth 2.0 authorization-code consent for a connection of that auth type: records the
// pending authorisation (PKCE) and answers the provider URL to open; the provider returns the
// browser to /api/integrations/oauth/callback.
//
// POST /api/developer/integration-connections/{id}/oauth/start
func (UnimplementedHandler) StartIntegrationOAuth(ctx context.Context, req OptStartIntegrationOAuthReq, params StartIntegrationOAuthParams) (r StartIntegrationOAuthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartWorkflowInstance implements startWorkflowInstance operation.
//
// Start a workflow instance from a published workflow definition.
//
// POST /api/workflow/instances
func (UnimplementedHandler) StartWorkflowInstance(ctx context.Context, req *StartWorkflowInstanceRequest) (r StartWorkflowInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SubmitBudget implements submitBudget operation.
//
// Submit a budget for approval (starts the model's workflow).
//
// POST /api/workflow/submit
func (UnimplementedHandler) SubmitBudget(ctx context.Context, req *SubmitBudgetRequest) (r SubmitBudgetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SyncFormMappings implements syncFormMappings operation.
//
// Re-apply every live form-metric mapping against all of a form's existing records.
//
// POST /api/forms/{id}/sync
func (UnimplementedHandler) SyncFormMappings(ctx context.Context, params SyncFormMappingsParams) (r *SyncFormMappingsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// TestAiSettings implements testAiSettings operation.
//
// Always responds 200 with {ok, ...} — even on failure — so the frontend can render the result
// inline rather than as a transport error.
//
// POST /api/ai/settings/test
func (UnimplementedHandler) TestAiSettings(ctx context.Context, req OptAiTestSettingsRequest) (r *TestAiSettingsOK, _ error) {
	return r, ht.ErrNotImplemented
}

// TestGoogleConnection implements testGoogleConnection operation.
//
// Prove the stored key by obtaining an access token from Google; nothing is read (developers and
// administrators).
//
// POST /api/developer/integrations/google-service-account/test
func (UnimplementedHandler) TestGoogleConnection(ctx context.Context) (r TestGoogleConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestIntegration implements testIntegration operation.
//
// Enqueue a test (or dry_run=1) execution — 202 + run id; the worker executes it, never the
// gateway. Mutation methods require acknowledge_side_effects=1.
//
// POST /api/developer/integrations/{id}/test
func (UnimplementedHandler) TestIntegration(ctx context.Context, params TestIntegrationParams) (r TestIntegrationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestIntegrationConnection implements testIntegrationConnection operation.
//
// Verify the stored credential decrypts and matches its auth type's required fields (no network call
// — full round-trips go through an integration's own /test run).
//
// POST /api/developer/integration-connections/{id}/test
func (UnimplementedHandler) TestIntegrationConnection(ctx context.Context, params TestIntegrationConnectionParams) (r TestIntegrationConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestRunWorkflow implements testRunWorkflow operation.
//
// Test mode is a property of the instance (workflow_instance.test_run), not a context flag. The run
// advances through the graph exactly like a real one — routing, conditions and auto-steps all
// execute — but every durable side effect is suppressed: no notifications are sent and no
// on_approve fact copies are written.
//
// POST /api/developer/workflows/{id}/test-run
func (UnimplementedHandler) TestRunWorkflow(ctx context.Context, req OptTestRunWorkflowRequest, params TestRunWorkflowParams) (r *TestRunWorkflowOK, _ error) {
	return r, ht.ErrNotImplemented
}

// TestSsoProvider implements testSsoProvider operation.
//
// Read the provider's discovery or metadata document without registering it (administrators;
// enterprise).
//
// POST /api/admin/sso/test
func (UnimplementedHandler) TestSsoProvider(ctx context.Context, req *SsoSettings) (r TestSsoProviderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TestTenantAISettings implements testTenantAISettings operation.
//
// Verify the tenant key with a live tool-calling probe before enforcing it (administrators;
// enterprise).
//
// POST /api/admin/ai-settings/test
func (UnimplementedHandler) TestTenantAISettings(ctx context.Context, req OptTenantAISettings) (r TestTenantAISettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TriggerAutomationRule implements triggerAutomationRule operation.
//
// Manually trigger an automation rule, starting its workflow instance.
//
// POST /api/automation/trigger/{id}
func (UnimplementedHandler) TriggerAutomationRule(ctx context.Context, req OptTriggerAutomationRequest, params TriggerAutomationRuleParams) (r TriggerAutomationRuleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAdminApplication implements updateAdminApplication operation.
//
// Rename an application.
//
// PATCH /api/admin/applications/{id}
func (UnimplementedHandler) UpdateAdminApplication(ctx context.Context, req *UpdateApplicationRequest, params UpdateAdminApplicationParams) (r *UpdateAdminApplicationOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAdminRevision implements updateAdminRevision operation.
//
// Rename or redescribe a revision.
//
// PATCH /api/admin/revisions/{id}
func (UnimplementedHandler) UpdateAdminRevision(ctx context.Context, req *UpdateAdminRevisionRequest, params UpdateAdminRevisionParams) (r *UpdateAdminRevisionOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAdminUser implements updateAdminUser operation.
//
// Only display_name is mutable. The email address is the sign-in identity in the identity provider,
// and this endpoint writes only the application's copy — changing it here would leave the account
// signing in under the old address while the console showed the new one. Sending an email that
// differs from the stored one is rejected; to move someone to a new address, delete them and invite
// them again.
//
// PATCH /api/admin/users/{id}
func (UnimplementedHandler) UpdateAdminUser(ctx context.Context, req *UpdateAdminUserRequest, params UpdateAdminUserParams) (r UpdateAdminUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAuditSettings implements updateAuditSettings operation.
//
// Set how long audit events are kept; 0 forever, otherwise at least 30 days (administrators;
// enterprise).
//
// PUT /api/admin/audit/settings
func (UnimplementedHandler) UpdateAuditSettings(ctx context.Context, req *AuditSettings) (r UpdateAuditSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAutomationRule implements updateAutomationRule operation.
//
// Update an automation rule.
//
// PATCH /api/automation/rules/{id}
func (UnimplementedHandler) UpdateAutomationRule(ctx context.Context, req *AutomationRuleRequest, params UpdateAutomationRuleParams) (r UpdateAutomationRuleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateBARole implements updateBARole operation.
//
// Rename a business role.
//
// PATCH /api/business-admin/roles/{id}
func (UnimplementedHandler) UpdateBARole(ctx context.Context, req *BARoleRequest, params UpdateBARoleParams) (r UpdateBARoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateBranding implements updateBranding operation.
//
// Set the tenant's name, tagline, logo, favicon, colour, e-mail sender name and custom domain
// (administrators; feature white_label).
//
// PUT /api/admin/branding
func (UnimplementedHandler) UpdateBranding(ctx context.Context, req *Branding) (r UpdateBrandingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDashboard implements updateDashboard operation.
//
// Rename, retag, or move a dashboard between folders.
//
// PATCH /api/developer/dashboards/{id}
func (UnimplementedHandler) UpdateDashboard(ctx context.Context, req *UpdateDashboardRequest, params UpdateDashboardParams) (r UpdateDashboardRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDashboardWidget implements updateDashboardWidget operation.
//
// Update a dashboard widget's position, size, or content.
//
// PATCH /api/developer/dashboards/{id}/widgets/{widgetId}
func (UnimplementedHandler) UpdateDashboardWidget(ctx context.Context, req *UpdateWidgetRequest, params UpdateDashboardWidgetParams) (r UpdateDashboardWidgetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDimension implements updateDimension operation.
//
// Update a dimension (rejects cycles in the parent-dimension hierarchy).
//
// PATCH /api/developer/dimensions/{dimId}
func (UnimplementedHandler) UpdateDimension(ctx context.Context, req *UpdateDimensionRequest, params UpdateDimensionParams) (r UpdateDimensionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDimensionMember implements updateDimensionMember operation.
//
// Update a dimension member (rejects cycles in the parent-member hierarchy).
//
// PATCH /api/developer/dimensions/{dimId}/members/{memberId}
func (UnimplementedHandler) UpdateDimensionMember(ctx context.Context, req *MemberRequest, params UpdateDimensionMemberParams) (r UpdateDimensionMemberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateDimensionProperty implements updateDimensionProperty operation.
//
// Update a dimension property.
//
// PATCH /api/developer/dimensions/{dimId}/properties/{propId}
func (UnimplementedHandler) UpdateDimensionProperty(ctx context.Context, req *PropertyRequest, params UpdateDimensionPropertyParams) (r *UpdateDimensionPropertyOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFolder implements updateFolder operation.
//
// Rename or reparent a dashboard folder.
//
// PATCH /api/developer/folders/{id}
func (UnimplementedHandler) UpdateFolder(ctx context.Context, req *FolderRequest, params UpdateFolderParams) (r UpdateFolderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateForm implements updateForm operation.
//
// Update a form's name, label, or fields.
//
// PATCH /api/forms/{id}
func (UnimplementedHandler) UpdateForm(ctx context.Context, req *CreateFormRequest, params UpdateFormParams) (r UpdateFormRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFormMapping implements updateFormMapping operation.
//
// Update a form-to-metric mapping (immediately re-applies it to already-submitted records).
//
// PATCH /api/developer/form-integrations/{id}
func (UnimplementedHandler) UpdateFormMapping(ctx context.Context, req *UpdateFormMappingRequest, params UpdateFormMappingParams) (r UpdateFormMappingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFormRecord implements updateFormRecord operation.
//
// Update a form record's data and/or status (dispatches form_submit/form_approval automation rules
// on status transitions).
//
// PUT /api/records/{id}
func (UnimplementedHandler) UpdateFormRecord(ctx context.Context, req *UpdateRecordRequest, params UpdateFormRecordParams) (r UpdateFormRecordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateGrid implements updateGrid operation.
//
// Rename a grid.
//
// PATCH /api/developer/grids/{id}
func (UnimplementedHandler) UpdateGrid(ctx context.Context, req *UpdateGridRequest, params UpdateGridParams) (r UpdateGridRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateGridDimension implements updateGridDimension operation.
//
// Set the display level for a grid's dimension.
//
// PATCH /api/developer/grids/{id}/dimensions/{dimId}
func (UnimplementedHandler) UpdateGridDimension(ctx context.Context, req *GridDimensionRequest, params UpdateGridDimensionParams) (r *UpdateGridDimensionOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateIntegration implements updateIntegration operation.
//
// Rename or retarget an integration definition.
//
// PATCH /api/developer/integrations/{id}
func (UnimplementedHandler) UpdateIntegration(ctx context.Context, req *UpdateIntegrationRequest, params UpdateIntegrationParams) (r UpdateIntegrationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateIntegrationConfig implements updateIntegrationConfig operation.
//
// Replace an integration's type-specific config blob.
//
// PATCH /api/developer/integrations/{id}/config
func (UnimplementedHandler) UpdateIntegrationConfig(ctx context.Context, req *UpdateIntegrationConfigRequest, params UpdateIntegrationConfigParams) (r UpdateIntegrationConfigRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateIntegrationConnection implements updateIntegrationConnection operation.
//
// Update a connection. Secret semantics: field absent = keep, null = remove, object = replace.
//
// PATCH /api/developer/integration-connections/{id}
func (UnimplementedHandler) UpdateIntegrationConnection(ctx context.Context, req *UpdateIntegrationConnectionReq, params UpdateIntegrationConnectionParams) (r UpdateIntegrationConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMetric implements updateMetric operation.
//
// Update a metric definition (re-wires formula dependencies and recalculates affected revisions).
//
// PATCH /api/developer/metrics/{id}
func (UnimplementedHandler) UpdateMetric(ctx context.Context, req *UpdateMetricRequest, params UpdateMetricParams) (r UpdateMetricRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateNotificationSettings implements updateNotificationSettings operation.
//
// Update the outbound notification settings (administrators).
//
// PUT /api/notifications/settings
func (UnimplementedHandler) UpdateNotificationSettings(ctx context.Context, req *NotificationSettings) (r UpdateNotificationSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSsoSettings implements updateSsoSettings operation.
//
// Register or update the tenant's identity provider in Keycloak and save the settings
// (administrators; enterprise).
//
// PUT /api/admin/sso
func (UnimplementedHandler) UpdateSsoSettings(ctx context.Context, req *SsoSettings) (r UpdateSsoSettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTenant implements updateTenant operation.
//
// Rename a tenant (tenant_admin scoped to their own tenant; platform_admin any).
//
// PATCH /api/admin/tenants/{id}
func (UnimplementedHandler) UpdateTenant(ctx context.Context, req *UpdateTenantRequest, params UpdateTenantParams) (r UpdateTenantRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTenantAISettings implements updateTenantAISettings operation.
//
// Set the tenant AI provider, model, key and whether it is enforced (administrators; enterprise).
//
// PUT /api/admin/ai-settings
func (UnimplementedHandler) UpdateTenantAISettings(ctx context.Context, req *TenantAISettings) (r UpdateTenantAISettingsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkflow implements updateWorkflow operation.
//
// Update a workflow definition's steps or metadata.
//
// PATCH /api/developer/workflows/{id}
func (UnimplementedHandler) UpdateWorkflow(ctx context.Context, req *UpdateWorkflowRequest, params UpdateWorkflowParams) (r UpdateWorkflowRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkflowInstance implements updateWorkflowInstance operation.
//
// Admin override of a workflow instance's status (business_admin only).
//
// PATCH /api/workflow/instances/{id}
func (UnimplementedHandler) UpdateWorkflowInstance(ctx context.Context, req *UpdateWorkflowInstanceRequest, params UpdateWorkflowInstanceParams) (r UpdateWorkflowInstanceRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadAiDocument implements uploadAiDocument operation.
//
// Upload a document (pdf, xlsx, docx, csv, txt, md, json) into a session; extracted text is injected
// into every subsequent chat call.
//
// POST /api/ai/sessions/{id}/documents
func (UnimplementedHandler) UploadAiDocument(ctx context.Context, req *UploadAiDocumentReq, params UploadAiDocumentParams) (r UploadAiDocumentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertPlan implements upsertPlan operation.
//
// Create or change a plan — name, self-service flag and limits (platform_admin; applies to every
// tenant on the plan within a minute).
//
// PUT /api/admin/plans/{key}
func (UnimplementedHandler) UpsertPlan(ctx context.Context, req *PlanInput, params UpsertPlanParams) (r UpsertPlanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ValidateIntegration implements validateIntegration operation.
//
// Validate a rest_api integration's configuration and target/connection ownership without saving.
//
// POST /api/developer/integrations/{id}/validate
func (UnimplementedHandler) ValidateIntegration(ctx context.Context, params ValidateIntegrationParams) (r ValidateIntegrationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ValidateWorkflow implements validateWorkflow operation.
//
// Run structural validation on a workflow definition without publishing it.
//
// POST /api/developer/workflows/{id}/validate
func (UnimplementedHandler) ValidateWorkflow(ctx context.Context, req OptValidateWorkflowReq, params ValidateWorkflowParams) (r ValidateWorkflowRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Writeback implements writeback operation.
//
// Write a single cell value (triggers recalculation).
//
// POST /api/cells
func (UnimplementedHandler) Writeback(ctx context.Context, req *WritebackRequest) (r WritebackRes, _ error) {
	return r, ht.ErrNotImplemented
}
