// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleBearerAuth handles bearerAuth security.
	HandleBearerAuth(ctx context.Context, operationName OperationName, t BearerAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesBearerAuth is a private map storing roles per operation.
var operationRolesBearerAuth = map[string][]string{
	ActivateRevisionOperation:             []string{},
	AddAdminUserRoleOperation:             []string{},
	AddBARoleMemberOperation:              []string{},
	AddGridDimensionOperation:             []string{},
	AddGridMetricOperation:                []string{},
	AdminInfraNodesOperation:              []string{},
	ApplyMigrationOperation:               []string{},
	ArchiveWorkflowOperation:              []string{},
	BackfillFormMappingOperation:          []string{},
	CancelIntegrationRunOperation:         []string{},
	ClearTenantAIKeyOperation:             []string{},
	CompleteTaskOperation:                 []string{},
	ConfirmAiProposalOperation:            []string{},
	CreateAdminApplicationOperation:       []string{},
	CreateAdminModelOperation:             []string{},
	CreateAdminRevisionOperation:          []string{},
	CreateAdminUserOperation:              []string{},
	CreateAdminUserTrailingSlashOperation: []string{},
	CreateAiSessionOperation:              []string{},
	CreateAutomationRuleOperation:         []string{},
	CreateBARoleOperation:                 []string{},
	CreateDashboardOperation:              []string{},
	CreateDashboardWidgetOperation:        []string{},
	CreateDimensionOperation:              []string{},
	CreateDimensionMemberOperation:        []string{},
	CreateDimensionPropertyOperation:      []string{},
	CreateFolderOperation:                 []string{},
	CreateFormOperation:                   []string{},
	CreateFormMappingOperation:            []string{},
	CreateFormRecordOperation:             []string{},
	CreateGridOperation:                   []string{},
	CreateIntegrationOperation:            []string{},
	CreateIntegrationConnectionOperation:  []string{},
	CreateMetricOperation:                 []string{},
	CreateRevisionOperation:               []string{},
	CreateScimTokenOperation:              []string{},
	CreateTenantOperation:                 []string{},
	CreateTenantForDeveloperOperation:     []string{},
	CreateWorkflowOperation:               []string{},
	DebugCalcOperation:                    []string{},
	DebugFactsOperation:                   []string{},
	DeleteAdminApplicationOperation:       []string{},
	DeleteAdminModelOperation:             []string{},
	DeleteAdminRevisionOperation:          []string{},
	DeleteAdminUserOperation:              []string{},
	DeleteAiDocumentOperation:             []string{},
	DeleteAiSessionOperation:              []string{},
	DeleteAutomationRuleOperation:         []string{},
	DeleteBARoleOperation:                 []string{},
	DeleteDashboardOperation:              []string{},
	DeleteDashboardWidgetOperation:        []string{},
	DeleteDimensionOperation:              []string{},
	DeleteDimensionMemberOperation:        []string{},
	DeleteDimensionPropertyOperation:      []string{},
	DeleteFolderOperation:                 []string{},
	DeleteFormOperation:                   []string{},
	DeleteFormMappingOperation:            []string{},
	DeleteFormRecordOperation:             []string{},
	DeleteGridOperation:                   []string{},
	DeleteImportJobOperation:              []string{},
	DeleteIntegrationOperation:            []string{},
	DeleteIntegrationConnectionOperation:  []string{},
	DeleteMetricOperation:                 []string{},
	DeleteRevisionOperation:               []string{},
	DeleteTenantOperation:                 []string{},
	DeleteWorkflowOperation:               []string{},
	DiscardAiDraftOperation:               []string{},
	DuplicateIntegrationOperation:         []string{},
	DuplicateWorkflowOperation:            []string{},
	ExportAuditOperation:                  []string{},
	ExportFormRecordsOperation:            []string{},
	ExportGridOperation:                   []string{},
	ExportModelOperation:                  []string{},
	ExportModelPackageOperation:           []string{},
	ExtractFormulaRefsOperation:           []string{},
	GenerateMigrationOperation:            []string{},
	GetAdminBrandingOperation:             []string{},
	GetAdminMeOperation:                   []string{},
	GetAiSessionOperation:                 []string{},
	GetAiSettingsOperation:                []string{},
	GetAuditSettingsOperation:             []string{},
	GetBrandingOperation:                  []string{},
	GetBusinessDashboardOperation:         []string{},
	GetCellHistoryOperation:               []string{},
	GetChartDataOperation:                 []string{},
	GetDemoOperation:                      []string{},
	GetDeveloperModelOperation:            []string{},
	GetGridOperation:                      []string{},
	GetIntegrationOperation:               []string{},
	GetIntegrationRunOperation:            []string{},
	GetLicenseOperation:                   []string{},
	GetMeOperation:                        []string{},
	GetMyWorkflowHistoryOperation:         []string{},
	GetNotificationSettingsOperation:      []string{},
	GetSignupOptionsOperation:             []string{},
	GetSsoSettingsOperation:               []string{},
	GetTenantAISettingsOperation:          []string{},
	GetUsageOperation:                     []string{},
	GetWorkflowOperation:                  []string{},
	GetWorkflowHistoryOperation:           []string{},
	GetWorkflowInstancesOperation:         []string{},
	GetWorkflowUsageOperation:             []string{},
	GrantAdminUserAppAccessOperation:      []string{},
	GrantAdminUserModelAccessOperation:    []string{},
	ImportDimensionMembersOperation:       []string{},
	ImportFormRecordsOperation:            []string{},
	ImportModelOperation:                  []string{},
	ImportSheetFetchOperation:             []string{},
	ImportUploadOperation:                 []string{},
	ListAdminApplicationsOperation:        []string{},
	ListAdminTenantsOperation:             []string{},
	ListAdminUsersOperation:               []string{},
	ListAdminWorkspacesOperation:          []string{},
	ListAiProposalsOperation:              []string{},
	ListAiSessionsOperation:               []string{},
	ListApplicationsForDeveloperOperation: []string{},
	ListAuditEventsOperation:              []string{},
	ListAutomationExecutionsOperation:     []string{},
	ListAutomationRulesOperation:          []string{},
	ListBAAvailableOperation:              []string{},
	ListBARoleDashboardsOperation:         []string{},
	ListBARoleMembersOperation:            []string{},
	ListBARolesOperation:                  []string{},
	ListBAUsersOperation:                  []string{},
	ListBusinessDashboardsOperation:       []string{},
	ListBusinessFoldersOperation:          []string{},
	ListBusinessIntegrationsOperation:     []string{},
	ListDashboardsOperation:               []string{},
	ListDevPersonasOperation:              []string{},
	ListDeveloperFoldersOperation:         []string{},
	ListDeveloperIntegrationsOperation:    []string{},
	ListDimensionPropertiesOperation:      []string{},
	ListDimensionsOperation:               []string{},
	ListFormMappingsOperation:             []string{},
	ListFormRecordsOperation:              []string{},
	ListFormsOperation:                    []string{},
	ListGridsOperation:                    []string{},
	ListImportJobsOperation:               []string{},
	ListIntegrationConnectionsOperation:   []string{},
	ListIntegrationRunsOperation:          []string{},
	ListMetricsOperation:                  []string{},
	ListNotificationsOperation:            []string{},
	ListPlansOperation:                    []string{},
	ListPublicDimensionsOperation:         []string{},
	ListRevisionsOperation:                []string{},
	ListScimTokensOperation:               []string{},
	ListTasksOperation:                    []string{},
	ListUserAccessRulesOperation:          []string{},
	ListUserAppsOperation:                 []string{},
	ListWorkflowDefinitionsOperation:      []string{},
	ListWorkflowRolesOperation:            []string{},
	ListWorkflowTriggerEventsOperation:    []string{},
	ListWorkflowsOperation:                []string{},
	MarkNotificationReadOperation:         []string{},
	PreviewFormMappingOperation:           []string{},
	PromoteAiDraftOperation:               []string{},
	PublishWorkflowOperation:              []string{},
	RejectAiProposalOperation:             []string{},
	RemoveAdminUserRoleOperation:          []string{},
	RemoveBARoleMemberOperation:           []string{},
	RemoveBrandingOperation:               []string{},
	RemoveGridDimensionOperation:          []string{},
	RemoveGridMetricOperation:             []string{},
	RemoveSsoOperation:                    []string{},
	RenameAiSessionOperation:              []string{},
	ResendAdminUserInvitationOperation:    []string{},
	RestoreWorkflowOperation:              []string{},
	RevokeAdminUserAppAccessOperation:     []string{},
	RevokeAdminUserModelAccessOperation:   []string{},
	RevokeScimTokenOperation:              []string{},
	RunIntegrationOperation:               []string{},
	SaveAiSettingsOperation:               []string{},
	ScimCreateGroupOperation:              []string{},
	ScimCreateUserOperation:               []string{},
	ScimDeleteGroupOperation:              []string{},
	ScimDeleteUserOperation:               []string{},
	ScimGetGroupOperation:                 []string{},
	ScimGetUserOperation:                  []string{},
	ScimListGroupsOperation:               []string{},
	ScimListUsersOperation:                []string{},
	ScimPatchGroupOperation:               []string{},
	ScimPatchUserOperation:                []string{},
	ScimReplaceGroupOperation:             []string{},
	ScimReplaceUserOperation:              []string{},
	ScimResourceTypesOperation:            []string{},
	ScimSchemasOperation:                  []string{},
	ScimServiceProviderConfigOperation:    []string{},
	SendAiMessageOperation:                []string{},
	SetActiveRevisionOperation:            []string{},
	SetBARoleDashboardsOperation:          []string{},
	SetDefaultModelOperation:              []string{},
	SetUserAccessRulesOperation:           []string{},
	SignupOperation:                       []string{},
	SsoDiscoverOperation:                  []string{},
	StartWorkflowInstanceOperation:        []string{},
	SubmitBudgetOperation:                 []string{},
	SyncFormMappingsOperation:             []string{},
	TestAiSettingsOperation:               []string{},
	TestIntegrationOperation:              []string{},
	TestIntegrationConnectionOperation:    []string{},
	TestRunWorkflowOperation:              []string{},
	TestSsoProviderOperation:              []string{},
	TestTenantAISettingsOperation:         []string{},
	TriggerAutomationRuleOperation:        []string{},
	UpdateAdminApplicationOperation:       []string{},
	UpdateAdminRevisionOperation:          []string{},
	UpdateAdminUserOperation:              []string{},
	UpdateAuditSettingsOperation:          []string{},
	UpdateAutomationRuleOperation:         []string{},
	UpdateBARoleOperation:                 []string{},
	UpdateBrandingOperation:               []string{},
	UpdateDashboardOperation:              []string{},
	UpdateDashboardWidgetOperation:        []string{},
	UpdateDimensionOperation:              []string{},
	UpdateDimensionMemberOperation:        []string{},
	UpdateDimensionPropertyOperation:      []string{},
	UpdateFolderOperation:                 []string{},
	UpdateFormOperation:                   []string{},
	UpdateFormMappingOperation:            []string{},
	UpdateFormRecordOperation:             []string{},
	UpdateGridOperation:                   []string{},
	UpdateGridDimensionOperation:          []string{},
	UpdateIntegrationOperation:            []string{},
	UpdateIntegrationConfigOperation:      []string{},
	UpdateIntegrationConnectionOperation:  []string{},
	UpdateMetricOperation:                 []string{},
	UpdateNotificationSettingsOperation:   []string{},
	UpdateSsoSettingsOperation:            []string{},
	UpdateTenantOperation:                 []string{},
	UpdateTenantAISettingsOperation:       []string{},
	UpdateWorkflowOperation:               []string{},
	UpdateWorkflowInstanceOperation:       []string{},
	UploadAiDocumentOperation:             []string{},
	UpsertPlanOperation:                   []string{},
	ValidateIntegrationOperation:          []string{},
	ValidateWorkflowOperation:             []string{},
	WritebackOperation:                    []string{},
}

// GetRolesForBearerAuth returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForBearerAuth(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForBearerAuth(operation string) []string {
	roles, ok := operationRolesBearerAuth[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t BearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesBearerAuth[operationName]
	rctx, err := s.sec.HandleBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BearerAuth provides bearerAuth security value.
	BearerAuth(ctx context.Context, operationName OperationName) (BearerAuth, error)
}

func (s *Client) securityBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
