// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	"github.com/google/uuid"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ActivateRevision implements activateRevision operation.
	//
	// Make a revision the model's active revision.
	//
	// PUT /api/developer/revisions/{id}/activate
	ActivateRevision(ctx context.Context, params ActivateRevisionParams) (ActivateRevisionRes, error)
	// AddAdminUserRole implements addAdminUserRole operation.
	//
	// The granting actor may only assign roles strictly below their own tier (see assignableRoles in
	// internal/gateway/handler.go) — a tenant_admin can never mint another tenant_admin, for example.
	//
	// POST /api/admin/users/{id}/roles
	AddAdminUserRole(ctx context.Context, req *AddUserRoleRequest, params AddAdminUserRoleParams) (AddAdminUserRoleRes, error)
	// AddBARoleMember implements addBARoleMember operation.
	//
	// Add a user to a business role.
	//
	// POST /api/business-admin/roles/{id}/members
	AddBARoleMember(ctx context.Context, req *AddRoleMemberRequest, params AddBARoleMemberParams) (AddBARoleMemberRes, error)
	// AddGridDimension implements addGridDimension operation.
	//
	// Add a dimension to a grid.
	//
	// POST /api/developer/grids/{id}/dimensions/{dimId}
	AddGridDimension(ctx context.Context, params AddGridDimensionParams) (*AddGridDimensionOK, error)
	// AddGridMetric implements addGridMetric operation.
	//
	// Add a metric to a grid (a metric may belong to only one grid at a time).
	//
	// POST /api/developer/grids/{id}/metrics/{metricId}
	AddGridMetric(ctx context.Context, params AddGridMetricParams) (AddGridMetricRes, error)
	// AdminInfraNodes implements adminInfraNodes operation.
	//
	// Latest health sample per cluster node (disk/memory/load), fed by the node-stats DaemonSet.
	//
	// GET /api/admin/infra/nodes
	AdminInfraNodes(ctx context.Context) ([]AdminInfraNodesOKItem, error)
	// ApplyMigration implements applyMigration operation.
	//
	// Generate and immediately apply a schema migration for a model.
	//
	// POST /api/developer/migration/apply
	ApplyMigration(ctx context.Context, req *MigrationApplyRequest) (ApplyMigrationRes, error)
	// ArchiveWorkflow implements archiveWorkflow operation.
	//
	// Archive a workflow definition.
	//
	// POST /api/developer/workflows/{id}/archive
	ArchiveWorkflow(ctx context.Context, params ArchiveWorkflowParams) (*WorkflowDefFull, error)
	// BackfillFormMapping implements backfillFormMapping operation.
	//
	// Re-apply a form-to-metric mapping against all already-submitted records.
	//
	// POST /api/developer/form-integrations/{id}/backfill
	BackfillFormMapping(ctx context.Context, params BackfillFormMappingParams) (*BackfillFormMappingOK, error)
	// CancelIntegrationRun implements cancelIntegrationRun operation.
	//
	// Cancel a queued run immediately, or request cooperative cancellation of a running one.
	//
	// POST /api/developer/integration-runs/{runId}/cancel
	CancelIntegrationRun(ctx context.Context, params CancelIntegrationRunParams) (CancelIntegrationRunRes, error)
	// ClearAuditSettings implements clearAuditSettings operation.
	//
	// Drop the tenant's own retention so it inherits the deployment's again (administrators; enterprise).
	//
	// DELETE /api/admin/audit/settings
	ClearAuditSettings(ctx context.Context) (ClearAuditSettingsRes, error)
	// ClearNotificationSettings implements clearNotificationSettings operation.
	//
	// Drop the tenant's own delivery settings so it inherits the deployment's again (administrators).
	//
	// DELETE /api/notifications/settings
	ClearNotificationSettings(ctx context.Context) (ClearNotificationSettingsRes, error)
	// ClearTenantAIKey implements clearTenantAIKey operation.
	//
	// Remove the stored tenant key and stop enforcing it, returning the tenant to personal keys
	// (administrators; enterprise).
	//
	// DELETE /api/admin/ai-settings/key
	ClearTenantAIKey(ctx context.Context) (ClearTenantAIKeyRes, error)
	// CompleteTask implements completeTask operation.
	//
	// Approve or reject a workflow step.
	//
	// POST /api/tasks/{stepId}/complete
	CompleteTask(ctx context.Context, req *TaskActionRequest, params CompleteTaskParams) (CompleteTaskRes, error)
	// ConfirmAiProposal implements confirmAiProposal operation.
	//
	// Execute a pending proposal's write steps (lazily creates the session's draft revision on first use).
	//
	// POST /api/ai/sessions/{id}/proposals/{pid}/confirm
	ConfirmAiProposal(ctx context.Context, params ConfirmAiProposalParams) (ConfirmAiProposalRes, error)
	// CreateAdminApplication implements createAdminApplication operation.
	//
	// Create an application under a tenant (a tenant admin: their own tenant only).
	//
	// POST /api/admin/applications
	CreateAdminApplication(ctx context.Context, req *CreateApplicationRequest) (CreateAdminApplicationRes, error)
	// CreateAdminModel implements createAdminModel operation.
	//
	// Create a model under an application (no list endpoint exists; models are reached via the tenant
	// hierarchy).
	//
	// POST /api/admin/models
	CreateAdminModel(ctx context.Context, req *CreateAdminModelRequest) (CreateAdminModelRes, error)
	// CreateAdminRevision implements createAdminRevision operation.
	//
	// Create a revision under a model, copying metrics/dimensions from the model's active (or
	// NULL-revision) definitions.
	//
	// POST /api/admin/revisions
	CreateAdminRevision(ctx context.Context, req *CreateAdminRevisionRequest) (CreateAdminRevisionRes, error)
	// CreateAdminUser implements createAdminUser operation.
	//
	// Available to platform_admin, tenant_admin, and developer roles. Non-platform admins create users
	// in their tenant scope and cannot assign platform-level roles during creation.
	// Creates a real identity-provider account and emails a set-your-password invitation; no password is
	// ever set server-side. The whole operation is undone if any step fails, so a user that exists can
	// always sign in. When no identity provider is configured (the dev stack) the account is local-only
	// and `invited` is false.
	//
	// POST /api/admin/users
	CreateAdminUser(ctx context.Context, req *CreateAdminUserReq) (CreateAdminUserRes, error)
	// CreateAdminUserTrailingSlash implements createAdminUserTrailingSlash operation.
	//
	// A second, directly reachable route to the same adminUserAction create branch that POST
	// /api/admin/users delegates into internally — not just an internal implementation detail. Kept
	// for backward compatibility; prefer POST /api/admin/users.
	//
	// POST /api/admin/users/
	CreateAdminUserTrailingSlash(ctx context.Context, req *CreateAdminUserTrailingSlashReq) (*CreateAdminUserTrailingSlashOK, error)
	// CreateAiSession implements createAiSession operation.
	//
	// Create a new AI assistant session, seeded with the caller's saved provider/model settings.
	//
	// POST /api/ai/sessions
	CreateAiSession(ctx context.Context) (*AiSession, error)
	// CreateAutomationRule implements createAutomationRule operation.
	//
	// Create an automation rule (a workflow_def_id must point at a published workflow).
	//
	// POST /api/automation/rules
	CreateAutomationRule(ctx context.Context, req *AutomationRuleRequest) (CreateAutomationRuleRes, error)
	// CreateBARole implements createBARole operation.
	//
	// Create a business role in the caller's workspace.
	//
	// POST /api/business-admin/roles
	CreateBARole(ctx context.Context, req *BARoleRequest) (CreateBARoleRes, error)
	// CreateDashboard implements createDashboard operation.
	//
	// Create a dashboard, defaulting to the model's active revision.
	//
	// POST /api/developer/dashboards
	CreateDashboard(ctx context.Context, req *CreateDashboardRequest) (CreateDashboardRes, error)
	// CreateDashboardWidget implements createDashboardWidget operation.
	//
	// Add a widget to a dashboard's free canvas.
	//
	// POST /api/developer/dashboards/{id}/widgets
	CreateDashboardWidget(ctx context.Context, req *CreateWidgetRequest, params CreateDashboardWidgetParams) (CreateDashboardWidgetRes, error)
	// CreateDimension implements createDimension operation.
	//
	// Create a new dimension.
	//
	// POST /api/developer/dimensions
	CreateDimension(ctx context.Context, req *CreateDimensionRequest) (CreateDimensionRes, error)
	// CreateDimensionMember implements createDimensionMember operation.
	//
	// Add a member to a dimension (splits parent-level facts and triggers recalculation when this is the
	// first child of an existing parent member).
	//
	// POST /api/developer/dimensions/{dimId}/members
	CreateDimensionMember(ctx context.Context, req *MemberRequest, params CreateDimensionMemberParams) (CreateDimensionMemberRes, error)
	// CreateDimensionProperty implements createDimensionProperty operation.
	//
	// Define a new typed property on a dimension.
	//
	// POST /api/developer/dimensions/{dimId}/properties
	CreateDimensionProperty(ctx context.Context, req *PropertyRequest, params CreateDimensionPropertyParams) (*CreateDimensionPropertyOK, error)
	// CreateFolder implements createFolder operation.
	//
	// Create a dashboard folder.
	//
	// POST /api/developer/folders
	CreateFolder(ctx context.Context, req *FolderRequest) (CreateFolderRes, error)
	// CreateForm implements createForm operation.
	//
	// Create a CRUD form.
	//
	// POST /api/forms
	CreateForm(ctx context.Context, req *CreateFormRequest) (CreateFormRes, error)
	// CreateFormMapping implements createFormMapping operation.
	//
	// Create a form-to-metric mapping (posts submitted form field values into a metric's facts).
	//
	// POST /api/developer/form-integrations
	CreateFormMapping(ctx context.Context, req *CreateFormMappingRequest) (CreateFormMappingRes, error)
	// CreateFormRecord implements createFormRecord operation.
	//
	// Submit a new record to a form (posts to any live form-metric mappings and dispatches form_submit
	// automation rules).
	//
	// POST /api/forms/{id}/records
	CreateFormRecord(ctx context.Context, req *CreateRecordRequest, params CreateFormRecordParams) (*FormRecord, error)
	// CreateGrid implements createGrid operation.
	//
	// Create a new grid definition.
	//
	// POST /api/developer/grids
	CreateGrid(ctx context.Context, req *CreateGridRequest) (CreateGridRes, error)
	// CreateIntegration implements createIntegration operation.
	//
	// Create an integration definition.
	//
	// POST /api/developer/integrations
	CreateIntegration(ctx context.Context, req *CreateIntegrationRequest) (CreateIntegrationRes, error)
	// CreateIntegrationConnection implements createIntegrationConnection operation.
	//
	// Create a connection; the secret document is sealed with mandatory AEAD and never returned.
	//
	// POST /api/developer/integration-connections
	CreateIntegrationConnection(ctx context.Context, req *CreateIntegrationConnectionReq) (CreateIntegrationConnectionRes, error)
	// CreateMetric implements createMetric operation.
	//
	// Create a new metric definition.
	//
	// POST /api/developer/metrics
	CreateMetric(ctx context.Context, req *CreateMetricRequest) (CreateMetricRes, error)
	// CreateRevision implements createRevision operation.
	//
	// Duplicate a revision (deep-copies metrics, dimensions, grids, dashboards, forms, workflows, and
	// facts).
	//
	// POST /api/developer/revisions
	CreateRevision(ctx context.Context, req *CreateRevisionRequest) (CreateRevisionRes, error)
	// CreateScimToken implements createScimToken operation.
	//
	// Issue a SCIM bearer token; the plaintext is returned once (administrators; enterprise).
	//
	// POST /api/admin/scim/tokens
	CreateScimToken(ctx context.Context, req *ScimToken) (CreateScimTokenRes, error)
	// CreateTenant implements createTenant operation.
	//
	// Create a tenant (platform_admin only) with a default workspace.
	//
	// POST /api/admin/tenants
	CreateTenant(ctx context.Context, req *CreateTenantRequest) (CreateTenantRes, error)
	// CreateTenantForDeveloper implements createTenantForDeveloper operation.
	//
	// Same underlying handler as POST /api/admin/tenants. Despite being reachable at a
	// developer-role-gated path, tenant creation itself still requires platform_admin — a plain
	// developer receives 403.
	//
	// POST /api/developer/applications
	CreateTenantForDeveloper(ctx context.Context, req *CreateTenantRequest) (CreateTenantForDeveloperRes, error)
	// CreateWorkflow implements createWorkflow operation.
	//
	// Create a new workflow definition (starts in draft status, with no steps).
	//
	// POST /api/developer/workflows
	CreateWorkflow(ctx context.Context, req *CreateWorkflowRequest, params CreateWorkflowParams) (CreateWorkflowRes, error)
	// DebugCalc implements debugCalc operation.
	//
	// Inspect persisted runtime.calc_result rows (debugging aid) — per-metric summary, or every
	// metric's row at one exact dim_members combo.
	//
	// GET /api/developer/debug/calc
	DebugCalc(ctx context.Context, params DebugCalcParams) (DebugCalcRes, error)
	// DebugFacts implements debugFacts operation.
	//
	// List the 50 most recently entered raw fact_input rows for a model (debugging aid).
	//
	// GET /api/developer/debug/facts
	DebugFacts(ctx context.Context) (DebugFactsRes, error)
	// DeleteAdminApplication implements deleteAdminApplication operation.
	//
	// Delete an application.
	//
	// DELETE /api/admin/applications/{id}
	DeleteAdminApplication(ctx context.Context, params DeleteAdminApplicationParams) (*DeleteAdminApplicationOK, error)
	// DeleteAdminModel implements deleteAdminModel operation.
	//
	// Delete a model.
	//
	// DELETE /api/admin/models/{id}
	DeleteAdminModel(ctx context.Context, params DeleteAdminModelParams) (*DeleteAdminModelOK, error)
	// DeleteAdminRevision implements deleteAdminRevision operation.
	//
	// Delete a revision.
	//
	// DELETE /api/admin/revisions/{id}
	DeleteAdminRevision(ctx context.Context, params DeleteAdminRevisionParams) (*DeleteAdminRevisionOK, error)
	// DeleteAdminUser implements deleteAdminUser operation.
	//
	// Removes the application row and the identity-provider account. Deleting your own account is
	// refused: it is not undoable from inside the product, and for the sole platform admin it would
	// leave nobody able to administer users at all. Another administrator can do it.
	//
	// DELETE /api/admin/users/{id}
	DeleteAdminUser(ctx context.Context, params DeleteAdminUserParams) (DeleteAdminUserRes, error)
	// DeleteAiDocument implements deleteAiDocument operation.
	//
	// Delete a document from a session.
	//
	// DELETE /api/ai/sessions/{id}/documents/{docId}
	DeleteAiDocument(ctx context.Context, params DeleteAiDocumentParams) (DeleteAiDocumentRes, error)
	// DeleteAiSession implements deleteAiSession operation.
	//
	// Delete a session (and its messages/documents/proposals).
	//
	// DELETE /api/ai/sessions/{id}
	DeleteAiSession(ctx context.Context, params DeleteAiSessionParams) (DeleteAiSessionRes, error)
	// DeleteAutomationRule implements deleteAutomationRule operation.
	//
	// Delete an automation rule.
	//
	// DELETE /api/automation/rules/{id}
	DeleteAutomationRule(ctx context.Context, params DeleteAutomationRuleParams) (*DeleteAutomationRuleOK, error)
	// DeleteBARole implements deleteBARole operation.
	//
	// Delete a business role.
	//
	// DELETE /api/business-admin/roles/{id}
	DeleteBARole(ctx context.Context, params DeleteBARoleParams) (*DeleteBARoleOK, error)
	// DeleteDashboard implements deleteDashboard operation.
	//
	// Delete a dashboard.
	//
	// DELETE /api/developer/dashboards/{id}
	DeleteDashboard(ctx context.Context, params DeleteDashboardParams) (*DeleteDashboardOK, error)
	// DeleteDashboardWidget implements deleteDashboardWidget operation.
	//
	// Delete a dashboard widget.
	//
	// DELETE /api/developer/dashboards/{id}/widgets/{widgetId}
	DeleteDashboardWidget(ctx context.Context, params DeleteDashboardWidgetParams) (*DeleteDashboardWidgetOK, error)
	// DeleteDimension implements deleteDimension operation.
	//
	// Delete a dimension.
	//
	// DELETE /api/developer/dimensions/{dimId}
	DeleteDimension(ctx context.Context, params DeleteDimensionParams) (*DeleteDimensionOK, error)
	// DeleteDimensionMember implements deleteDimensionMember operation.
	//
	// Delete a dimension member.
	//
	// DELETE /api/developer/dimensions/{dimId}/members/{memberId}
	DeleteDimensionMember(ctx context.Context, params DeleteDimensionMemberParams) (*DeleteDimensionMemberOK, error)
	// DeleteDimensionProperty implements deleteDimensionProperty operation.
	//
	// Delete a dimension property.
	//
	// DELETE /api/developer/dimensions/{dimId}/properties/{propId}
	DeleteDimensionProperty(ctx context.Context, params DeleteDimensionPropertyParams) (*DeleteDimensionPropertyOK, error)
	// DeleteFolder implements deleteFolder operation.
	//
	// Delete a dashboard folder.
	//
	// DELETE /api/developer/folders/{id}
	DeleteFolder(ctx context.Context, params DeleteFolderParams) (*DeleteFolderOK, error)
	// DeleteForm implements deleteForm operation.
	//
	// Delete a form.
	//
	// DELETE /api/forms/{id}
	DeleteForm(ctx context.Context, params DeleteFormParams) (*DeleteFormOK, error)
	// DeleteFormMapping implements deleteFormMapping operation.
	//
	// Delete a form-to-metric mapping.
	//
	// DELETE /api/developer/form-integrations/{id}
	DeleteFormMapping(ctx context.Context, params DeleteFormMappingParams) (*DeleteFormMappingOK, error)
	// DeleteFormRecord implements deleteFormRecord operation.
	//
	// Delete a form record.
	//
	// DELETE /api/records/{id}
	DeleteFormRecord(ctx context.Context, params DeleteFormRecordParams) (DeleteFormRecordRes, error)
	// DeleteGoogleConnection implements deleteGoogleConnection operation.
	//
	// Forget the tenant's Google service account; private sheets become unreachable again (developers
	// and administrators).
	//
	// DELETE /api/developer/integrations/google-service-account
	DeleteGoogleConnection(ctx context.Context) (DeleteGoogleConnectionRes, error)
	// DeleteGrid implements deleteGrid operation.
	//
	// Delete a grid.
	//
	// DELETE /api/developer/grids/{id}
	DeleteGrid(ctx context.Context, params DeleteGridParams) (*DeleteGridOK, error)
	// DeleteImportJob implements deleteImportJob operation.
	//
	// Delete an import job record.
	//
	// DELETE /api/import/jobs/{id}
	DeleteImportJob(ctx context.Context, params DeleteImportJobParams) (DeleteImportJobRes, error)
	// DeleteIntegration implements deleteIntegration operation.
	//
	// Delete an integration definition.
	//
	// DELETE /api/developer/integrations/{id}
	DeleteIntegration(ctx context.Context, params DeleteIntegrationParams) (*DeleteIntegrationOK, error)
	// DeleteIntegrationConnection implements deleteIntegrationConnection operation.
	//
	// Delete a connection (refused while any integration references it).
	//
	// DELETE /api/developer/integration-connections/{id}
	DeleteIntegrationConnection(ctx context.Context, params DeleteIntegrationConnectionParams) (DeleteIntegrationConnectionRes, error)
	// DeleteMetric implements deleteMetric operation.
	//
	// Delete a metric definition.
	//
	// DELETE /api/developer/metrics/{id}
	DeleteMetric(ctx context.Context, params DeleteMetricParams) (*DeleteMetricOK, error)
	// DeleteRevision implements deleteRevision operation.
	//
	// Delete a revision (rejected if it is the model's active revision).
	//
	// DELETE /api/developer/revisions/{id}
	DeleteRevision(ctx context.Context, params DeleteRevisionParams) (DeleteRevisionRes, error)
	// DeleteTenant implements deleteTenant operation.
	//
	// Delete a tenant and cascade-delete its applications (platform_admin only).
	//
	// DELETE /api/admin/tenants/{id}
	DeleteTenant(ctx context.Context, params DeleteTenantParams) (DeleteTenantRes, error)
	// DeleteWorkflow implements deleteWorkflow operation.
	//
	// Delete a workflow definition.
	//
	// DELETE /api/developer/workflows/{id}
	DeleteWorkflow(ctx context.Context, params DeleteWorkflowParams) (DeleteWorkflowRes, error)
	// DiscardAiDraft implements discardAiDraft operation.
	//
	// Delete the session's isolated draft revision and clear the session's draft, in one server-side
	// action.
	//
	// POST /api/ai/sessions/{id}/discard-draft
	DiscardAiDraft(ctx context.Context, params DiscardAiDraftParams) (DiscardAiDraftRes, error)
	// DisconnectIntegrationOAuth implements disconnectIntegrationOAuth operation.
	//
	// Forget the connection's tokens, keeping the client so it can be connected again.
	//
	// POST /api/developer/integration-connections/{id}/oauth/disconnect
	DisconnectIntegrationOAuth(ctx context.Context, params DisconnectIntegrationOAuthParams) (DisconnectIntegrationOAuthRes, error)
	// DuplicateIntegration implements duplicateIntegration operation.
	//
	// Duplicate a rest_api integration (test state cleared, schedule copied disabled, no run history).
	//
	// POST /api/developer/integrations/{id}/duplicate
	DuplicateIntegration(ctx context.Context, params DuplicateIntegrationParams) (DuplicateIntegrationRes, error)
	// DuplicateWorkflow implements duplicateWorkflow operation.
	//
	// Duplicate a workflow definition as a new draft.
	//
	// POST /api/developer/workflows/{id}/duplicate
	DuplicateWorkflow(ctx context.Context, req OptDuplicateWorkflowRequest, params DuplicateWorkflowParams) (*WorkflowDefFull, error)
	// ExportAudit implements exportAudit operation.
	//
	// Stream the caller's audit events, oldest first, as a CSV download or JSON Lines for a collector;
	// the same tenant scope as the listing (administrators; enterprise feature audit_export).
	//
	// GET /api/admin/audit/export
	ExportAudit(ctx context.Context, params ExportAuditParams) (ExportAuditRes, error)
	// ExportFormRecords implements exportFormRecords operation.
	//
	// Export a form's records as CSV or XLSX.
	//
	// GET /api/forms/{id}/export
	ExportFormRecords(ctx context.Context, params ExportFormRecordsParams) (ExportFormRecordsRes, error)
	// ExportGrid implements exportGrid operation.
	//
	// Export a grid's raw input-metric values as CSV or XLSX (one row per dimension-member combination;
	// round-trips through POST /api/import/upload).
	//
	// GET /api/grid/export
	ExportGrid(ctx context.Context, params ExportGridParams) (ExportGridRes, error)
	// ExportModel implements exportModel operation.
	//
	// Export a model revision as a self-contained transfer package (tenant admins for their own tenant,
	// platform admins for any).
	//
	// GET /api/admin/models/{id}/export
	ExportModel(ctx context.Context, params ExportModelParams) (ExportModelRes, error)
	// ExportModelPackage implements exportModelPackage operation.
	//
	// Download a standalone deployment package for a model revision — a tar.gz containing the entity
	// graph (package.json), the complete database migrations, a provenance manifest, and an infra-only
	// docker-compose (tenant admins for their own tenant, platform admins for any).
	//
	// GET /api/admin/models/{id}/export/package
	ExportModelPackage(ctx context.Context, params ExportModelPackageParams) (ExportModelPackageRes, error)
	// ExtractFormulaRefs implements extractFormulaRefs operation.
	//
	// Parse a formula string and return the metric/dimension names it references.
	//
	// POST /api/formula/refs
	ExtractFormulaRefs(ctx context.Context, req *FormulaRefsRequest) (*ExtractFormulaRefsOK, error)
	// GenerateDimensionPeriods implements generateDimensionPeriods operation.
	//
	// Bulk-generate a time dimension's periods between two dates (same validation and chronological
	// indexing as single members; time dimensions only).
	//
	// POST /api/developer/dimensions/{dimId}/members/generate
	GenerateDimensionPeriods(ctx context.Context, req *GeneratePeriodsRequest, params GenerateDimensionPeriodsParams) (GenerateDimensionPeriodsRes, error)
	// GenerateMigration implements generateMigration operation.
	//
	// Generate (but do not apply) the next schema migration for a model's current definition.
	//
	// POST /api/developer/migration/generate
	GenerateMigration(ctx context.Context) (*GenerateMigrationOK, error)
	// GetAdminBranding implements getAdminBranding operation.
	//
	// This tenant's branding (administrators; feature white_label).
	//
	// GET /api/admin/branding
	GetAdminBranding(ctx context.Context) (GetAdminBrandingRes, error)
	// GetAdminMe implements getAdminMe operation.
	//
	// Get the current actor's admin identity.
	//
	// GET /api/admin/me
	GetAdminMe(ctx context.Context) (*GetAdminMeOK, error)
	// GetAiSession implements getAiSession operation.
	//
	// Get a session with its full message and document history.
	//
	// GET /api/ai/sessions/{id}
	GetAiSession(ctx context.Context, params GetAiSessionParams) (GetAiSessionRes, error)
	// GetAiSettings implements getAiSettings operation.
	//
	// Get the caller's saved LLM provider settings.
	//
	// GET /api/ai/settings
	GetAiSettings(ctx context.Context) (*AiLLMSettings, error)
	// GetAuditSettings implements getAuditSettings operation.
	//
	// The audit retention policy (administrators; enterprise).
	//
	// GET /api/admin/audit/settings
	GetAuditSettings(ctx context.Context) (GetAuditSettingsRes, error)
	// GetBranding implements getBranding operation.
	//
	// The brand to apply — a signed-in caller's tenant, else the tenant registered for the request's
	// host, else the platform's own (public).
	//
	// GET /api/branding
	GetBranding(ctx context.Context) (*BrandView, error)
	// GetBusinessDashboard implements getBusinessDashboard operation.
	//
	// Get a dashboard's widgets, if the caller may access it.
	//
	// GET /api/dashboards/{id}
	GetBusinessDashboard(ctx context.Context, params GetBusinessDashboardParams) (GetBusinessDashboardRes, error)
	// GetCellHistory implements getCellHistory operation.
	//
	// Every value one intersection held, newest first, including rows later deleted and why (any user
	// who can see the cell; enterprise feature cell_history).
	//
	// GET /api/cells/history
	GetCellHistory(ctx context.Context, params GetCellHistoryParams) (GetCellHistoryRes, error)
	// GetChartData implements getChartData operation.
	//
	// Evaluate a chart widget's live data against a grid's facts and calculated values.
	//
	// POST /api/dashboard-widgets/{id}/chart-data
	GetChartData(ctx context.Context, req OptChartRuntimeRequest, params GetChartDataParams) (GetChartDataRes, error)
	// GetDemo implements getDemo operation.
	//
	// Get demo context (model, revision, actor for current persona).
	//
	// GET /api/demo
	GetDemo(ctx context.Context) (GetDemoRes, error)
	// GetDeveloperModel implements getDeveloperModel operation.
	//
	// Get full model definition with metrics and dependencies.
	//
	// GET /api/developer/model
	GetDeveloperModel(ctx context.Context, params GetDeveloperModelParams) (*GetDeveloperModelOK, error)
	// GetGoogleConnection implements getGoogleConnection operation.
	//
	// The tenant's Google service account, public half only — the address to share sheets with
	// (developers and administrators; the tenant of the application in X-App-Id).
	//
	// GET /api/developer/integrations/google-service-account
	GetGoogleConnection(ctx context.Context) (GetGoogleConnectionRes, error)
	// GetGrid implements getGrid operation.
	//
	// Get planning grid for a revision.
	//
	// GET /api/grid
	GetGrid(ctx context.Context, params GetGridParams) (GetGridRes, error)
	// GetIntegration implements getIntegration operation.
	//
	// One integration; rest_api returns the typed definition + schedule + tested flag.
	//
	// GET /api/developer/integrations/{id}
	GetIntegration(ctx context.Context, params GetIntegrationParams) (GetIntegrationRes, error)
	// GetIntegrationRun implements getIntegrationRun operation.
	//
	// One run's full state (poll while queued/running).
	//
	// GET /api/developer/integration-runs/{runId}
	GetIntegrationRun(ctx context.Context, params GetIntegrationRunParams) (GetIntegrationRunRes, error)
	// GetLegalInfo implements getLegalInfo operation.
	//
	// The operator's identity and the documents it publishes, for the terms of service and privacy
	// notice a visitor reads before signing up (public; see internal/gateway/legal.go).
	//
	// GET /api/legal
	GetLegalInfo(ctx context.Context) (*LegalInfo, error)
	// GetLicense implements getLicense operation.
	//
	// Report the edition in force, the features it unlocks and the full gated-feature catalog (any
	// signed-in user; see pkg/license).
	//
	// GET /api/license
	GetLicense(ctx context.Context) (GetLicenseRes, error)
	// GetMe implements getMe operation.
	//
	// Get the resolved actor for the current identity (no model/app context required).
	//
	// GET /api/me
	GetMe(ctx context.Context) (GetMeRes, error)
	// GetMyWorkflowHistory implements getMyWorkflowHistory operation.
	//
	// List the 50 most recent workflow instances where the caller started the instance or was assigned a
	// step.
	//
	// GET /api/workflow/my-history
	GetMyWorkflowHistory(ctx context.Context) ([]WorkflowInstance, error)
	// GetNotificationSettings implements getNotificationSettings operation.
	//
	// Outbound notification settings for this tenant — which channels deliver, and whether overdue
	// tasks are reminded (administrators).
	//
	// GET /api/notifications/settings
	GetNotificationSettings(ctx context.Context) (GetNotificationSettingsRes, error)
	// GetSignupOptions implements getSignupOptions operation.
	//
	// Whether public self-service sign-up is open on this deployment and on what terms (public; see
	// internal/gateway/signup.go).
	//
	// GET /api/signup/options
	GetSignupOptions(ctx context.Context) (*SignupOptions, error)
	// GetSsoSettings implements getSsoSettings operation.
	//
	// This tenant's single sign-on provider (administrators; enterprise feature sso).
	//
	// GET /api/admin/sso
	GetSsoSettings(ctx context.Context) (GetSsoSettingsRes, error)
	// GetTenantAISettings implements getTenantAISettings operation.
	//
	// The tenant-level AI provider key for this tenant (administrators; enterprise feature
	// tenant_ai_keys).
	//
	// GET /api/admin/ai-settings
	GetTenantAISettings(ctx context.Context) (GetTenantAISettingsRes, error)
	// GetUsage implements getUsage operation.
	//
	// Per-tenant usage — every tenant for a platform admin, their own for a tenant admin
	// (administrators; enterprise feature usage_analytics).
	//
	// GET /api/admin/usage
	GetUsage(ctx context.Context, params GetUsageParams) (GetUsageRes, error)
	// GetWorkflow implements getWorkflow operation.
	//
	// Get a workflow definition, including its full step configuration.
	//
	// GET /api/developer/workflows/{id}
	GetWorkflow(ctx context.Context, params GetWorkflowParams) (GetWorkflowRes, error)
	// GetWorkflowHistory implements getWorkflowHistory operation.
	//
	// List the 50 most recent workflow instances across the whole platform (business_admin only).
	//
	// GET /api/workflow/history
	GetWorkflowHistory(ctx context.Context) ([]WorkflowInstance, error)
	// GetWorkflowInstances implements getWorkflowInstances operation.
	//
	// List the most recent 20 executions started from a workflow definition.
	//
	// GET /api/developer/workflows/{id}/instances
	GetWorkflowInstances(ctx context.Context, params GetWorkflowInstancesParams) ([]WorkflowInstanceSummary, error)
	// GetWorkflowUsage implements getWorkflowUsage operation.
	//
	// List the automation rules that reference a workflow definition.
	//
	// GET /api/developer/workflows/{id}/usage
	GetWorkflowUsage(ctx context.Context, params GetWorkflowUsageParams) ([]WorkflowDefUsage, error)
	// GrantAdminUserAppAccess implements grantAdminUserAppAccess operation.
	//
	// Requires platform_admin or tenant_admin. A developer may administer users but not decide who
	// reaches which application.
	//
	// POST /api/admin/users/{id}/access/apps/{appId}
	GrantAdminUserAppAccess(ctx context.Context, params GrantAdminUserAppAccessParams) (GrantAdminUserAppAccessRes, error)
	// GrantAdminUserModelAccess implements grantAdminUserModelAccess operation.
	//
	// Requires platform_admin or tenant_admin. A developer may administer users but not decide who
	// reaches which model.
	//
	// POST /api/admin/users/{id}/access/models/{modelId}
	GrantAdminUserModelAccess(ctx context.Context, params GrantAdminUserModelAccessParams) (GrantAdminUserModelAccessRes, error)
	// Healthz implements healthz operation.
	//
	// Health check.
	//
	// GET /healthz
	Healthz(ctx context.Context) (*HealthzOK, error)
	// ImportDimensionMembers implements importDimensionMembers operation.
	//
	// One-off dimension member import (code/label/parent_code/property:<name> columns; codes
	// auto-generated from labels when absent).
	//
	// POST /api/import/dimension-members
	ImportDimensionMembers(ctx context.Context, req *ImportDimensionMembersReq) (ImportDimensionMembersRes, error)
	// ImportFormRecords implements importFormRecords operation.
	//
	// Bulk-create form records from an uploaded CSV or XLSX (atomic — any row failing validation
	// rejects the whole file).
	//
	// POST /api/forms/{id}/import
	ImportFormRecords(ctx context.Context, req *FormImportRequest, params ImportFormRecordsParams) (ImportFormRecordsRes, error)
	// ImportModel implements importModel operation.
	//
	// Import a model export package into an application, creating a new model and revision (tenant
	// admins for their own tenant, platform admins for any).
	//
	// POST /api/admin/models/import
	ImportModel(ctx context.Context, req *ModelImportRequest) (ImportModelRes, error)
	// ImportSheetFetch implements importSheetFetch operation.
	//
	// Fetch a link-shared Google Sheet as CSV text (server-side — Google's export endpoint sends no
	// CORS headers; only docs.google.com exports for the parsed spreadsheet ID are ever requested).
	//
	// POST /api/import/sheets/fetch
	ImportSheetFetch(ctx context.Context, req *ImportSheetFetchReq) (ImportSheetFetchRes, error)
	// ImportUpload implements importUpload operation.
	//
	// Import facts from a CSV or XLSX file (atomic — any row failing validation rejects the whole file).
	//
	// POST /api/import/upload
	ImportUpload(ctx context.Context, req *ImportUploadRequest) (ImportUploadRes, error)
	// IntegrationOAuthCallback implements integrationOAuthCallback operation.
	//
	// Where the provider sends the browser after consent (public: the person arrives with the state
	// only). Exchanges the code, seals the tokens into the connection, and redirects to the console with
	// ?oauth=connected or ?oauth=error&oauth_error=….
	//
	// GET /api/integrations/oauth/callback
	IntegrationOAuthCallback(ctx context.Context, params IntegrationOAuthCallbackParams) error
	// ListAdminApplications implements listAdminApplications operation.
	//
	// List the applications in the caller's scope — every tenant's for a platform admin, their own
	// tenant's for a tenant admin.
	//
	// GET /api/admin/applications
	ListAdminApplications(ctx context.Context) ([]AdminApplicationItem, error)
	// ListAdminTenants implements listAdminTenants operation.
	//
	// List all tenants with app/model/revision hierarchy.
	//
	// GET /api/admin/tenants
	ListAdminTenants(ctx context.Context) ([]AdminTenant, error)
	// ListAdminUsers implements listAdminUsers operation.
	//
	// Available to platform_admin, tenant_admin, and developer roles. Platform admins see all users;
	// tenant admins and developers are scoped to reachable tenant/workspace/app/model access.
	//
	// GET /api/admin/users
	ListAdminUsers(ctx context.Context) ([]AdminUser, error)
	// ListAdminWorkspaces implements listAdminWorkspaces operation.
	//
	// Available to platform_admin, tenant_admin, and developer roles. Results are scoped to the acting
	// admin's reachable tenant/workspace scope.
	//
	// GET /api/admin/workspaces
	ListAdminWorkspaces(ctx context.Context) ([]AdminWorkspace, error)
	// ListAiProposals implements listAiProposals operation.
	//
	// List every proposal ever made in a session, most recent first (not just pending ones) — the
	// Activity panel's data source.
	//
	// GET /api/ai/sessions/{id}/proposals
	ListAiProposals(ctx context.Context, params ListAiProposalsParams) (ListAiProposalsRes, error)
	// ListAiSessions implements listAiSessions operation.
	//
	// List the caller's 20 most recent AI assistant sessions for the current application.
	//
	// GET /api/ai/sessions
	ListAiSessions(ctx context.Context) ([]AiSession, error)
	// ListApplicationsForDeveloper implements listApplicationsForDeveloper operation.
	//
	// Same underlying handler as GET /api/admin/tenants; reachable by developer, platform_admin, or
	// tenant_admin. A developer's results are additionally scoped to their reachable workspace/app/model
	// access grants.
	//
	// GET /api/developer/applications
	ListApplicationsForDeveloper(ctx context.Context) ([]AdminTenant, error)
	// ListAuditEvents implements listAuditEvents operation.
	//
	// Takes no query parameters. A Platform Admin sees the most recent 200 events across all tenants; a
	// Tenant Admin sees only events attributable to their own customers — those whose application
	// belongs to one, plus application-less events (user/tenant administration) performed by one of
	// their users.
	//
	// GET /api/admin/audit
	ListAuditEvents(ctx context.Context) (ListAuditEventsRes, error)
	// ListAutomationExecutions implements listAutomationExecutions operation.
	//
	// List the 50 most recent automation rule executions for the current application.
	//
	// GET /api/automation/executions
	ListAutomationExecutions(ctx context.Context) ([]AutomationExecution, error)
	// ListAutomationRules implements listAutomationRules operation.
	//
	// List automation rules for the current application/revision.
	//
	// GET /api/automation/rules
	ListAutomationRules(ctx context.Context) ([]AutomationRule, error)
	// ListBAAvailable implements listBAAvailable operation.
	//
	// List dashboards, metrics, dimensions, or dimension members available for role/access configuration.
	//
	// GET /api/business-admin/available
	ListBAAvailable(ctx context.Context, params ListBAAvailableParams) (ListBAAvailableRes, error)
	// ListBARoleDashboards implements listBARoleDashboards operation.
	//
	// List the dashboard IDs assigned to a business role.
	//
	// GET /api/business-admin/roles/{id}/dashboards
	ListBARoleDashboards(ctx context.Context, params ListBARoleDashboardsParams) ([]uuid.UUID, error)
	// ListBARoleMembers implements listBARoleMembers operation.
	//
	// List the users assigned to a business role.
	//
	// GET /api/business-admin/roles/{id}/members
	ListBARoleMembers(ctx context.Context, params ListBARoleMembersParams) ([]BARoleMember, error)
	// ListBARoles implements listBARoles operation.
	//
	// List business roles in the caller's workspace.
	//
	// GET /api/business-admin/roles
	ListBARoles(ctx context.Context) ([]BARole, error)
	// ListBAUsers implements listBAUsers operation.
	//
	// List business_user-role members of the caller's workspace.
	//
	// GET /api/business-admin/users
	ListBAUsers(ctx context.Context) ([]BAUser, error)
	// ListBusinessDashboards implements listBusinessDashboards operation.
	//
	// Scoped by business-role dashboard assignment: a dashboard is visible if the caller has a business
	// role it's assigned to, or if the dashboard's workspace defines no business roles at all (dev/demo
	// fallback).
	//
	// GET /api/dashboards
	ListBusinessDashboards(ctx context.Context) ([]BusinessDashboardSummary, error)
	// ListBusinessFolders implements listBusinessFolders operation.
	//
	// List dashboard folders for a model (read-only, any authenticated user).
	//
	// GET /api/folders
	ListBusinessFolders(ctx context.Context, params ListBusinessFoldersParams) (ListBusinessFoldersRes, error)
	// ListBusinessIntegrations implements listBusinessIntegrations operation.
	//
	// List integrations visible to business users (e.g. for run-button labels).
	//
	// GET /api/integrations
	ListBusinessIntegrations(ctx context.Context, params ListBusinessIntegrationsParams) (ListBusinessIntegrationsRes, error)
	// ListDashboards implements listDashboards operation.
	//
	// List dashboards (with widgets) for a model, defaulting to its active revision.
	//
	// GET /api/developer/dashboards
	ListDashboards(ctx context.Context, params ListDashboardsParams) ([]DashboardDef, error)
	// ListDevPersonas implements listDevPersonas operation.
	//
	// List every user in the database as a switchable dev persona (dev mode only — 404s in production).
	//
	// GET /api/dev/personas
	ListDevPersonas(ctx context.Context) (ListDevPersonasRes, error)
	// ListDeveloperFolders implements listDeveloperFolders operation.
	//
	// List dashboard folders for a model.
	//
	// GET /api/developer/folders
	ListDeveloperFolders(ctx context.Context, params ListDeveloperFoldersParams) (ListDeveloperFoldersRes, error)
	// ListDeveloperIntegrations implements listDeveloperIntegrations operation.
	//
	// List integration definitions for a model.
	//
	// GET /api/developer/integrations
	ListDeveloperIntegrations(ctx context.Context, params ListDeveloperIntegrationsParams) (ListDeveloperIntegrationsRes, error)
	// ListDimensionProperties implements listDimensionProperties operation.
	//
	// List typed properties defined on a dimension.
	//
	// GET /api/developer/dimensions/{dimId}/properties
	ListDimensionProperties(ctx context.Context, params ListDimensionPropertiesParams) ([]DimensionProperty, error)
	// ListDimensions implements listDimensions operation.
	//
	// List dimensions with members.
	//
	// GET /api/developer/dimensions
	ListDimensions(ctx context.Context, params ListDimensionsParams) ([]Dimension, error)
	// ListFormMappings implements listFormMappings operation.
	//
	// List form-to-metric mappings for a model.
	//
	// GET /api/developer/form-integrations
	ListFormMappings(ctx context.Context, params ListFormMappingsParams) (ListFormMappingsRes, error)
	// ListFormRecords implements listFormRecords operation.
	//
	// List the 100 most recent records submitted to a form.
	//
	// GET /api/forms/{id}/records
	ListFormRecords(ctx context.Context, params ListFormRecordsParams) ([]FormRecord, error)
	// ListForms implements listForms operation.
	//
	// List CRUD forms for the current model's revision.
	//
	// GET /api/forms
	ListForms(ctx context.Context, params ListFormsParams) (ListFormsRes, error)
	// ListGrids implements listGrids operation.
	//
	// List grid definitions for a model.
	//
	// GET /api/developer/grids
	ListGrids(ctx context.Context, params ListGridsParams) (ListGridsRes, error)
	// ListImportJobs implements listImportJobs operation.
	//
	// List the 20 most recent import jobs for the model.
	//
	// GET /api/import/jobs
	ListImportJobs(ctx context.Context) ([]ImportJob, error)
	// ListIntegrationConnections implements listIntegrationConnections operation.
	//
	// List reusable credential connections (public metadata + has_secret only — secrets are write-only).
	//
	// GET /api/developer/integration-connections
	ListIntegrationConnections(ctx context.Context) ([]ListIntegrationConnectionsOKItem, error)
	// ListIntegrationRuns implements listIntegrationRuns operation.
	//
	// Run history of one saved integration (most recent first, max 50).
	//
	// GET /api/developer/integrations/{id}/runs
	ListIntegrationRuns(ctx context.Context, params ListIntegrationRunsParams) (ListIntegrationRunsRes, error)
	// ListMetrics implements listMetrics operation.
	//
	// List all metrics for the demo model.
	//
	// GET /api/metrics
	ListMetrics(ctx context.Context) (ListMetricsRes, error)
	// ListNotifications implements listNotifications operation.
	//
	// List the 50 most recent notifications for the current user.
	//
	// GET /api/notifications
	ListNotifications(ctx context.Context) ([]Notification, error)
	// ListPlans implements listPlans operation.
	//
	// The plan catalog in display order (platform_admin and tenant_admin; internal/plan).
	//
	// GET /api/admin/plans
	ListPlans(ctx context.Context) (ListPlansRes, error)
	// ListPublicDimensions implements listPublicDimensions operation.
	//
	// List all dimensions with members for the current model (any authenticated user).
	//
	// GET /api/dimensions
	ListPublicDimensions(ctx context.Context, params ListPublicDimensionsParams) (ListPublicDimensionsRes, error)
	// ListRevisions implements listRevisions operation.
	//
	// List revisions for a model.
	//
	// GET /api/developer/revisions
	ListRevisions(ctx context.Context, params ListRevisionsParams) ([]DevRevision, error)
	// ListScimTokens implements listScimTokens operation.
	//
	// This tenant's SCIM tokens, revoked ones included, never the secret (administrators; enterprise
	// feature scim).
	//
	// GET /api/admin/scim/tokens
	ListScimTokens(ctx context.Context) (ListScimTokensRes, error)
	// ListTasks implements listTasks operation.
	//
	// List pending workflow tasks for the current user.
	//
	// GET /api/tasks
	ListTasks(ctx context.Context) ([]Task, error)
	// ListUserAccessRules implements listUserAccessRules operation.
	//
	// List a user's dimension/metric access rules.
	//
	// GET /api/business-admin/users/{id}/access-rules
	ListUserAccessRules(ctx context.Context, params ListUserAccessRulesParams) ([]UserAccessRule, error)
	// ListUserApps implements listUserApps operation.
	//
	// List applications accessible to the current user, scoped by tenant/workspace membership and
	// app/model access grants.
	//
	// GET /api/apps
	ListUserApps(ctx context.Context) ([]UserApp, error)
	// ListWorkflowDefinitions implements listWorkflowDefinitions operation.
	//
	// Published workflow definitions of the caller's application, with context schemas — what the
	// Planning workspace renders its start-workflow dialog from.
	//
	// GET /api/workflow/definitions
	ListWorkflowDefinitions(ctx context.Context) (ListWorkflowDefinitionsRes, error)
	// ListWorkflowRoles implements listWorkflowRoles operation.
	//
	// List business roles in the application's workspace, selectable as a workflow step's
	// approver/assignee.
	//
	// GET /api/developer/workflow-roles
	ListWorkflowRoles(ctx context.Context, params ListWorkflowRolesParams) (ListWorkflowRolesRes, error)
	// ListWorkflowTriggerEvents implements listWorkflowTriggerEvents operation.
	//
	// List the catalog of events (system, form-submit, integration-import) that can trigger a workflow.
	//
	// GET /api/developer/workflow-trigger-events
	ListWorkflowTriggerEvents(ctx context.Context, params ListWorkflowTriggerEventsParams) ([]TriggerEventCatalogItem, error)
	// ListWorkflows implements listWorkflows operation.
	//
	// List workflow definitions for an application.
	//
	// GET /api/developer/workflows
	ListWorkflows(ctx context.Context, params ListWorkflowsParams) (ListWorkflowsRes, error)
	// MarkNotificationRead implements markNotificationRead operation.
	//
	// Mark one or more of the caller's own notifications as read.
	//
	// POST /api/notifications/mark-read
	MarkNotificationRead(ctx context.Context, req *MarkNotificationReadRequest) (*MarkNotificationReadOK, error)
	// PreviewFormMapping implements previewFormMapping operation.
	//
	// Preview the fact rows a mapping would currently produce, without writing them.
	//
	// GET /api/developer/form-integrations/{id}/preview
	PreviewFormMapping(ctx context.Context, params PreviewFormMappingParams) ([]PreviewFormMappingOKItem, error)
	// PromoteAiDraft implements promoteAiDraft operation.
	//
	// Make the session's isolated draft revision the model's active revision, then clear the session's
	// draft.
	//
	// POST /api/ai/sessions/{id}/promote-draft
	PromoteAiDraft(ctx context.Context, params PromoteAiDraftParams) (PromoteAiDraftRes, error)
	// PublishWorkflow implements publishWorkflow operation.
	//
	// Publish a workflow definition (rejected if it fails validation).
	//
	// POST /api/developer/workflows/{id}/publish
	PublishWorkflow(ctx context.Context, params PublishWorkflowParams) (PublishWorkflowRes, error)
	// PutGoogleConnection implements putGoogleConnection operation.
	//
	// Store a Google service-account key file for this tenant — the JSON Google Cloud downloaded; only
	// the address and the private key are kept, sealed (developers and administrators).
	//
	// PUT /api/developer/integrations/google-service-account
	PutGoogleConnection(ctx context.Context, req *PutGoogleConnectionReq) (PutGoogleConnectionRes, error)
	// RejectAiProposal implements rejectAiProposal operation.
	//
	// Reject a pending proposal without executing it.
	//
	// POST /api/ai/sessions/{id}/proposals/{pid}/reject
	RejectAiProposal(ctx context.Context, params RejectAiProposalParams) (RejectAiProposalRes, error)
	// RemoveAdminUserRole implements removeAdminUserRole operation.
	//
	// Mirrors the grant tier check. Additionally refused when the actor is revoking their own last grant
	// of developer, tenant_admin or platform_admin — the roles that gate these endpoints — since
	// nothing in the product could give it back.
	//
	// DELETE /api/admin/users/{id}/roles/{role}
	RemoveAdminUserRole(ctx context.Context, params RemoveAdminUserRoleParams) (RemoveAdminUserRoleRes, error)
	// RemoveBARoleMember implements removeBARoleMember operation.
	//
	// Remove a user from a business role.
	//
	// DELETE /api/business-admin/roles/{id}/members/{userId}
	RemoveBARoleMember(ctx context.Context, params RemoveBARoleMemberParams) (*RemoveBARoleMemberOK, error)
	// RemoveBranding implements removeBranding operation.
	//
	// Return the tenant to the platform's own look (administrators; feature white_label).
	//
	// DELETE /api/admin/branding
	RemoveBranding(ctx context.Context) (RemoveBrandingRes, error)
	// RemoveGridDimension implements removeGridDimension operation.
	//
	// Remove a dimension from a grid.
	//
	// DELETE /api/developer/grids/{id}/dimensions/{dimId}
	RemoveGridDimension(ctx context.Context, params RemoveGridDimensionParams) (*RemoveGridDimensionOK, error)
	// RemoveGridMetric implements removeGridMetric operation.
	//
	// Remove a metric from a grid.
	//
	// DELETE /api/developer/grids/{id}/metrics/{metricId}
	RemoveGridMetric(ctx context.Context, params RemoveGridMetricParams) (*RemoveGridMetricOK, error)
	// RemoveSso implements removeSso operation.
	//
	// Remove the tenant's identity provider from Keycloak and clear the settings (administrators;
	// enterprise).
	//
	// DELETE /api/admin/sso
	RemoveSso(ctx context.Context) (RemoveSsoRes, error)
	// RenameAiSession implements renameAiSession operation.
	//
	// Rename a session (an explicit rename always wins over auto-naming).
	//
	// PATCH /api/ai/sessions/{id}
	RenameAiSession(ctx context.Context, req *RenameAiSessionReq, params RenameAiSessionParams) (RenameAiSessionRes, error)
	// ResendAdminUserInvitation implements resendAdminUserInvitation operation.
	//
	// Invitations expire and mail gets lost; without this the only recovery is deleting and re-creating
	// the user, which discards their roles and access grants. Returns 409 for users created before
	// identity-provider provisioning existed — they carry a synthetic subject and have no account to
	// invite.
	//
	// POST /api/admin/users/{id}/invite
	ResendAdminUserInvitation(ctx context.Context, params ResendAdminUserInvitationParams) (ResendAdminUserInvitationRes, error)
	// RestoreWorkflow implements restoreWorkflow operation.
	//
	// Restore an archived workflow definition to draft.
	//
	// POST /api/developer/workflows/{id}/restore
	RestoreWorkflow(ctx context.Context, params RestoreWorkflowParams) (RestoreWorkflowRes, error)
	// RevokeAdminUserAppAccess implements revokeAdminUserAppAccess operation.
	//
	// Requires platform_admin or tenant_admin. See grantAdminUserAppAccess.
	//
	// DELETE /api/admin/users/{id}/access/apps/{appId}
	RevokeAdminUserAppAccess(ctx context.Context, params RevokeAdminUserAppAccessParams) (RevokeAdminUserAppAccessRes, error)
	// RevokeAdminUserModelAccess implements revokeAdminUserModelAccess operation.
	//
	// Requires platform_admin or tenant_admin. See grantAdminUserModelAccess.
	//
	// DELETE /api/admin/users/{id}/access/models/{modelId}
	RevokeAdminUserModelAccess(ctx context.Context, params RevokeAdminUserModelAccessParams) (RevokeAdminUserModelAccessRes, error)
	// RevokeScimToken implements revokeScimToken operation.
	//
	// Revoke a SCIM token (administrators; enterprise).
	//
	// DELETE /api/admin/scim/tokens/{id}
	RevokeScimToken(ctx context.Context, params RevokeScimTokenParams) (RevokeScimTokenRes, error)
	// RunIntegration implements runIntegration operation.
	//
	// Execute a saved integration against an uploaded CSV (target is a form, dimension, or grid, per the
	// integration's target_type).
	//
	// POST /api/integrations/{id}/run
	RunIntegration(ctx context.Context, req *IntegrationRunRequest, params RunIntegrationParams) (RunIntegrationRes, error)
	// SaveAiSettings implements saveAiSettings operation.
	//
	// Save the caller's LLM provider settings.
	//
	// PUT /api/ai/settings
	SaveAiSettings(ctx context.Context, req *AiSaveSettingsRequest) (*SaveAiSettingsOK, error)
	// ScimCreateGroup implements scimCreateGroup operation.
	//
	// Create a business role with members (SCIM bearer token).
	//
	// POST /api/scim/v2/Groups
	ScimCreateGroup(ctx context.Context, req ScimResource) (ScimCreateGroupRes, error)
	// ScimCreateUser implements scimCreateUser operation.
	//
	// Create a user exactly as the console's Users screen would (SCIM bearer token).
	//
	// POST /api/scim/v2/Users
	ScimCreateUser(ctx context.Context, req ScimResource) (ScimCreateUserRes, error)
	// ScimDeleteGroup implements scimDeleteGroup operation.
	//
	// Delete the business role (SCIM bearer token).
	//
	// DELETE /api/scim/v2/Groups/{id}
	ScimDeleteGroup(ctx context.Context, params ScimDeleteGroupParams) (ScimDeleteGroupRes, error)
	// ScimDeleteUser implements scimDeleteUser operation.
	//
	// Delete the user and their identity-provider account (SCIM bearer token).
	//
	// DELETE /api/scim/v2/Users/{id}
	ScimDeleteUser(ctx context.Context, params ScimDeleteUserParams) (ScimDeleteUserRes, error)
	// ScimGetGroup implements scimGetGroup operation.
	//
	// One group (SCIM bearer token).
	//
	// GET /api/scim/v2/Groups/{id}
	ScimGetGroup(ctx context.Context, params ScimGetGroupParams) (ScimGetGroupRes, error)
	// ScimGetUser implements scimGetUser operation.
	//
	// One user (SCIM bearer token).
	//
	// GET /api/scim/v2/Users/{id}
	ScimGetUser(ctx context.Context, params ScimGetUserParams) (ScimGetUserRes, error)
	// ScimListGroups implements scimListGroups operation.
	//
	// List or filter this tenant's business roles as SCIM groups (SCIM bearer token).
	//
	// GET /api/scim/v2/Groups
	ScimListGroups(ctx context.Context, params ScimListGroupsParams) (ScimListGroupsRes, error)
	// ScimListUsers implements scimListUsers operation.
	//
	// List or filter this tenant's users as SCIM resources (SCIM bearer token); filter supports attr eq
	// "value" joined by and.
	//
	// GET /api/scim/v2/Users
	ScimListUsers(ctx context.Context, params ScimListUsersParams) (ScimListUsersRes, error)
	// ScimPatchGroup implements scimPatchGroup operation.
	//
	// Add or remove members, rename (SCIM bearer token).
	//
	// PATCH /api/scim/v2/Groups/{id}
	ScimPatchGroup(ctx context.Context, req ScimResource, params ScimPatchGroupParams) (ScimPatchGroupRes, error)
	// ScimPatchUser implements scimPatchUser operation.
	//
	// Apply PatchOp operations to a user; active=false deactivates sign-in immediately (SCIM bearer
	// token).
	//
	// PATCH /api/scim/v2/Users/{id}
	ScimPatchUser(ctx context.Context, req ScimResource, params ScimPatchUserParams) (ScimPatchUserRes, error)
	// ScimReplaceGroup implements scimReplaceGroup operation.
	//
	// Replace a group's name and members (SCIM bearer token).
	//
	// PUT /api/scim/v2/Groups/{id}
	ScimReplaceGroup(ctx context.Context, req ScimResource, params ScimReplaceGroupParams) (ScimReplaceGroupRes, error)
	// ScimReplaceUser implements scimReplaceUser operation.
	//
	// Replace a user's attributes (SCIM bearer token).
	//
	// PUT /api/scim/v2/Users/{id}
	ScimReplaceUser(ctx context.Context, req ScimResource, params ScimReplaceUserParams) (ScimReplaceUserRes, error)
	// ScimResourceTypes implements scimResourceTypes operation.
	//
	// SCIM 2.0 resource types (SCIM bearer token).
	//
	// GET /api/scim/v2/ResourceTypes
	ScimResourceTypes(ctx context.Context) (ScimResourceTypesRes, error)
	// ScimSchemas implements scimSchemas operation.
	//
	// SCIM 2.0 schemas (SCIM bearer token).
	//
	// GET /api/scim/v2/Schemas
	ScimSchemas(ctx context.Context) (ScimSchemasRes, error)
	// ScimServiceProviderConfig implements scimServiceProviderConfig operation.
	//
	// SCIM 2.0 service provider configuration (SCIM bearer token).
	//
	// GET /api/scim/v2/ServiceProviderConfig
	ScimServiceProviderConfig(ctx context.Context) (ScimServiceProviderConfigRes, error)
	// SendAiMessage implements sendAiMessage operation.
	//
	// Response is text/event-stream, not JSON — ogen/generated clients cannot consume this operation
	// and callers should use a raw fetch/ EventSource instead. Named events: "delta" ({content}) for
	// each streamed token; "tool_status" ({tool}) before executing a read tool; "proposal" ({proposal:
	// AiProposal, messages, session}) when the model calls a write tool and a proposal is created
	// instead of executing immediately; "error" ({error}) on any failure (rate limit, provider error,
	// invalid proposal); "done" ({reply: AiChatMessage, messages, session}) on normal completion.
	// Rate-limited to 50 LLM calls per session and 200 per user per day (429 if exceeded before any
	// streaming has started — after streaming begins, limit hits are only reported via an "error"
	// event since the HTTP status is already sent).
	//
	// POST /api/ai/sessions/{id}/messages
	SendAiMessage(ctx context.Context, req *AiSendMessageRequest, params SendAiMessageParams) (SendAiMessageRes, error)
	// SendNotificationTestMail implements sendNotificationTestMail operation.
	//
	// Send the calling administrator a test e-mail through the deployment's relay, synchronously — the
	// relay's verdict comes back as the response (administrators).
	//
	// POST /api/notifications/settings/test
	SendNotificationTestMail(ctx context.Context) (SendNotificationTestMailRes, error)
	// SetActiveRevision implements setActiveRevision operation.
	//
	// Set a model's active revision by name.
	//
	// PUT /api/admin/models/{id}/active-revision
	SetActiveRevision(ctx context.Context, req *ActiveRevisionRequest, params SetActiveRevisionParams) (SetActiveRevisionRes, error)
	// SetBARoleDashboards implements setBARoleDashboards operation.
	//
	// Replace the full set of dashboards assigned to a business role.
	//
	// PUT /api/business-admin/roles/{id}/dashboards
	SetBARoleDashboards(ctx context.Context, req *SetRoleDashboardsRequest, params SetBARoleDashboardsParams) (SetBARoleDashboardsRes, error)
	// SetDefaultModel implements setDefaultModel operation.
	//
	// Make this model its application's business default (what business consoles resolve).
	//
	// POST /api/developer/models/{id}/set-default
	SetDefaultModel(ctx context.Context, params SetDefaultModelParams) (SetDefaultModelRes, error)
	// SetUserAccessRules implements setUserAccessRules operation.
	//
	// Replace the full set of a user's dimension/metric access rules.
	//
	// PUT /api/business-admin/users/{id}/access-rules
	SetUserAccessRules(ctx context.Context, req *SetUserAccessRulesRequest, params SetUserAccessRulesParams) (SetUserAccessRulesRes, error)
	// Signup implements signup operation.
	//
	// Register a tenant from the public sign-up page — the tenant on the self-service plan, its first
	// administrator/developer, an application with the starter model, and an invitation to set a
	// password (public, rate-limited per address).
	//
	// POST /api/signup
	Signup(ctx context.Context, req *SignupRequest) (SignupRes, error)
	// SsoDiscover implements ssoDiscover operation.
	//
	// Before sign-in, whether single sign-on exists and which provider an e-mail belongs to (public,
	// rate-limited; answers nothing about e-mails it does not know).
	//
	// GET /api/sso/discover
	SsoDiscover(ctx context.Context, params SsoDiscoverParams) (SsoDiscoverRes, error)
	// StartIntegrationOAuth implements startIntegrationOAuth operation.
	//
	// Begin the OAuth 2.0 authorization-code consent for a connection of that auth type: records the
	// pending authorisation (PKCE) and answers the provider URL to open; the provider returns the
	// browser to /api/integrations/oauth/callback.
	//
	// POST /api/developer/integration-connections/{id}/oauth/start
	StartIntegrationOAuth(ctx context.Context, req OptStartIntegrationOAuthReq, params StartIntegrationOAuthParams) (StartIntegrationOAuthRes, error)
	// StartWorkflowInstance implements startWorkflowInstance operation.
	//
	// Start a workflow instance from a published workflow definition.
	//
	// POST /api/workflow/instances
	StartWorkflowInstance(ctx context.Context, req *StartWorkflowInstanceRequest) (StartWorkflowInstanceRes, error)
	// SubmitBudget implements submitBudget operation.
	//
	// Submit a budget for approval (starts the model's workflow).
	//
	// POST /api/workflow/submit
	SubmitBudget(ctx context.Context, req *SubmitBudgetRequest) (SubmitBudgetRes, error)
	// SyncFormMappings implements syncFormMappings operation.
	//
	// Re-apply every live form-metric mapping against all of a form's existing records.
	//
	// POST /api/forms/{id}/sync
	SyncFormMappings(ctx context.Context, params SyncFormMappingsParams) (*SyncFormMappingsOK, error)
	// TestAiSettings implements testAiSettings operation.
	//
	// Always responds 200 with {ok, ...} — even on failure — so the frontend can render the result
	// inline rather than as a transport error.
	//
	// POST /api/ai/settings/test
	TestAiSettings(ctx context.Context, req OptAiTestSettingsRequest) (*TestAiSettingsOK, error)
	// TestGoogleConnection implements testGoogleConnection operation.
	//
	// Prove the stored key by obtaining an access token from Google; nothing is read (developers and
	// administrators).
	//
	// POST /api/developer/integrations/google-service-account/test
	TestGoogleConnection(ctx context.Context) (TestGoogleConnectionRes, error)
	// TestIntegration implements testIntegration operation.
	//
	// Enqueue a test (or dry_run=1) execution — 202 + run id; the worker executes it, never the
	// gateway. Mutation methods require acknowledge_side_effects=1.
	//
	// POST /api/developer/integrations/{id}/test
	TestIntegration(ctx context.Context, params TestIntegrationParams) (TestIntegrationRes, error)
	// TestIntegrationConnection implements testIntegrationConnection operation.
	//
	// Verify the stored credential decrypts and matches its auth type's required fields (no network call
	// — full round-trips go through an integration's own /test run).
	//
	// POST /api/developer/integration-connections/{id}/test
	TestIntegrationConnection(ctx context.Context, params TestIntegrationConnectionParams) (TestIntegrationConnectionRes, error)
	// TestRunWorkflow implements testRunWorkflow operation.
	//
	// Test mode is a property of the instance (workflow_instance.test_run), not a context flag. The run
	// advances through the graph exactly like a real one — routing, conditions and auto-steps all
	// execute — but every durable side effect is suppressed: no notifications are sent and no
	// on_approve fact copies are written.
	//
	// POST /api/developer/workflows/{id}/test-run
	TestRunWorkflow(ctx context.Context, req OptTestRunWorkflowRequest, params TestRunWorkflowParams) (*TestRunWorkflowOK, error)
	// TestSsoProvider implements testSsoProvider operation.
	//
	// Read the provider's discovery or metadata document without registering it (administrators;
	// enterprise).
	//
	// POST /api/admin/sso/test
	TestSsoProvider(ctx context.Context, req *SsoSettings) (TestSsoProviderRes, error)
	// TestTenantAISettings implements testTenantAISettings operation.
	//
	// Verify the tenant key with a live tool-calling probe before enforcing it (administrators;
	// enterprise).
	//
	// POST /api/admin/ai-settings/test
	TestTenantAISettings(ctx context.Context, req OptTenantAISettings) (TestTenantAISettingsRes, error)
	// TriggerAutomationRule implements triggerAutomationRule operation.
	//
	// Manually trigger an automation rule, starting its workflow instance.
	//
	// POST /api/automation/trigger/{id}
	TriggerAutomationRule(ctx context.Context, req OptTriggerAutomationRequest, params TriggerAutomationRuleParams) (TriggerAutomationRuleRes, error)
	// UpdateAdminApplication implements updateAdminApplication operation.
	//
	// Rename an application.
	//
	// PATCH /api/admin/applications/{id}
	UpdateAdminApplication(ctx context.Context, req *UpdateApplicationRequest, params UpdateAdminApplicationParams) (*UpdateAdminApplicationOK, error)
	// UpdateAdminRevision implements updateAdminRevision operation.
	//
	// Rename or redescribe a revision.
	//
	// PATCH /api/admin/revisions/{id}
	UpdateAdminRevision(ctx context.Context, req *UpdateAdminRevisionRequest, params UpdateAdminRevisionParams) (*UpdateAdminRevisionOK, error)
	// UpdateAdminUser implements updateAdminUser operation.
	//
	// Only display_name is mutable. The email address is the sign-in identity in the identity provider,
	// and this endpoint writes only the application's copy — changing it here would leave the account
	// signing in under the old address while the console showed the new one. Sending an email that
	// differs from the stored one is rejected; to move someone to a new address, delete them and invite
	// them again.
	//
	// PATCH /api/admin/users/{id}
	UpdateAdminUser(ctx context.Context, req *UpdateAdminUserRequest, params UpdateAdminUserParams) (UpdateAdminUserRes, error)
	// UpdateAuditSettings implements updateAuditSettings operation.
	//
	// Set how long audit events are kept; 0 forever, otherwise at least 30 days (administrators;
	// enterprise).
	//
	// PUT /api/admin/audit/settings
	UpdateAuditSettings(ctx context.Context, req *AuditSettings) (UpdateAuditSettingsRes, error)
	// UpdateAutomationRule implements updateAutomationRule operation.
	//
	// Update an automation rule.
	//
	// PATCH /api/automation/rules/{id}
	UpdateAutomationRule(ctx context.Context, req *AutomationRuleRequest, params UpdateAutomationRuleParams) (UpdateAutomationRuleRes, error)
	// UpdateBARole implements updateBARole operation.
	//
	// Rename a business role.
	//
	// PATCH /api/business-admin/roles/{id}
	UpdateBARole(ctx context.Context, req *BARoleRequest, params UpdateBARoleParams) (UpdateBARoleRes, error)
	// UpdateBranding implements updateBranding operation.
	//
	// Set the tenant's name, tagline, logo, favicon, colour, e-mail sender name and custom domain
	// (administrators; feature white_label).
	//
	// PUT /api/admin/branding
	UpdateBranding(ctx context.Context, req *Branding) (UpdateBrandingRes, error)
	// UpdateDashboard implements updateDashboard operation.
	//
	// Rename, retag, or move a dashboard between folders.
	//
	// PATCH /api/developer/dashboards/{id}
	UpdateDashboard(ctx context.Context, req *UpdateDashboardRequest, params UpdateDashboardParams) (UpdateDashboardRes, error)
	// UpdateDashboardWidget implements updateDashboardWidget operation.
	//
	// Update a dashboard widget's position, size, or content.
	//
	// PATCH /api/developer/dashboards/{id}/widgets/{widgetId}
	UpdateDashboardWidget(ctx context.Context, req *UpdateWidgetRequest, params UpdateDashboardWidgetParams) (UpdateDashboardWidgetRes, error)
	// UpdateDimension implements updateDimension operation.
	//
	// Update a dimension (rejects cycles in the parent-dimension hierarchy).
	//
	// PATCH /api/developer/dimensions/{dimId}
	UpdateDimension(ctx context.Context, req *UpdateDimensionRequest, params UpdateDimensionParams) (UpdateDimensionRes, error)
	// UpdateDimensionMember implements updateDimensionMember operation.
	//
	// Update a dimension member (rejects cycles in the parent-member hierarchy).
	//
	// PATCH /api/developer/dimensions/{dimId}/members/{memberId}
	UpdateDimensionMember(ctx context.Context, req *MemberRequest, params UpdateDimensionMemberParams) (UpdateDimensionMemberRes, error)
	// UpdateDimensionProperty implements updateDimensionProperty operation.
	//
	// Update a dimension property.
	//
	// PATCH /api/developer/dimensions/{dimId}/properties/{propId}
	UpdateDimensionProperty(ctx context.Context, req *PropertyRequest, params UpdateDimensionPropertyParams) (*UpdateDimensionPropertyOK, error)
	// UpdateFolder implements updateFolder operation.
	//
	// Rename or reparent a dashboard folder.
	//
	// PATCH /api/developer/folders/{id}
	UpdateFolder(ctx context.Context, req *FolderRequest, params UpdateFolderParams) (UpdateFolderRes, error)
	// UpdateForm implements updateForm operation.
	//
	// Update a form's name, label, or fields.
	//
	// PATCH /api/forms/{id}
	UpdateForm(ctx context.Context, req *CreateFormRequest, params UpdateFormParams) (UpdateFormRes, error)
	// UpdateFormMapping implements updateFormMapping operation.
	//
	// Update a form-to-metric mapping (immediately re-applies it to already-submitted records).
	//
	// PATCH /api/developer/form-integrations/{id}
	UpdateFormMapping(ctx context.Context, req *UpdateFormMappingRequest, params UpdateFormMappingParams) (UpdateFormMappingRes, error)
	// UpdateFormRecord implements updateFormRecord operation.
	//
	// Update a form record's data and/or status (dispatches form_submit/form_approval automation rules
	// on status transitions).
	//
	// PUT /api/records/{id}
	UpdateFormRecord(ctx context.Context, req *UpdateRecordRequest, params UpdateFormRecordParams) (UpdateFormRecordRes, error)
	// UpdateGrid implements updateGrid operation.
	//
	// Rename a grid.
	//
	// PATCH /api/developer/grids/{id}
	UpdateGrid(ctx context.Context, req *UpdateGridRequest, params UpdateGridParams) (UpdateGridRes, error)
	// UpdateGridDimension implements updateGridDimension operation.
	//
	// Set the display level for a grid's dimension.
	//
	// PATCH /api/developer/grids/{id}/dimensions/{dimId}
	UpdateGridDimension(ctx context.Context, req *GridDimensionRequest, params UpdateGridDimensionParams) (*UpdateGridDimensionOK, error)
	// UpdateIntegration implements updateIntegration operation.
	//
	// Rename or retarget an integration definition.
	//
	// PATCH /api/developer/integrations/{id}
	UpdateIntegration(ctx context.Context, req *UpdateIntegrationRequest, params UpdateIntegrationParams) (UpdateIntegrationRes, error)
	// UpdateIntegrationConfig implements updateIntegrationConfig operation.
	//
	// Replace an integration's type-specific config blob.
	//
	// PATCH /api/developer/integrations/{id}/config
	UpdateIntegrationConfig(ctx context.Context, req *UpdateIntegrationConfigRequest, params UpdateIntegrationConfigParams) (UpdateIntegrationConfigRes, error)
	// UpdateIntegrationConnection implements updateIntegrationConnection operation.
	//
	// Update a connection. Secret semantics: field absent = keep, null = remove, object = replace.
	//
	// PATCH /api/developer/integration-connections/{id}
	UpdateIntegrationConnection(ctx context.Context, req *UpdateIntegrationConnectionReq, params UpdateIntegrationConnectionParams) (UpdateIntegrationConnectionRes, error)
	// UpdateMetric implements updateMetric operation.
	//
	// Update a metric definition (re-wires formula dependencies and recalculates affected revisions).
	//
	// PATCH /api/developer/metrics/{id}
	UpdateMetric(ctx context.Context, req *UpdateMetricRequest, params UpdateMetricParams) (UpdateMetricRes, error)
	// UpdateNotificationSettings implements updateNotificationSettings operation.
	//
	// Update the outbound notification settings (administrators).
	//
	// PUT /api/notifications/settings
	UpdateNotificationSettings(ctx context.Context, req *NotificationSettings) (UpdateNotificationSettingsRes, error)
	// UpdateSsoSettings implements updateSsoSettings operation.
	//
	// Register or update the tenant's identity provider in Keycloak and save the settings
	// (administrators; enterprise).
	//
	// PUT /api/admin/sso
	UpdateSsoSettings(ctx context.Context, req *SsoSettings) (UpdateSsoSettingsRes, error)
	// UpdateTenant implements updateTenant operation.
	//
	// Rename a tenant (tenant_admin scoped to their own tenant; platform_admin any).
	//
	// PATCH /api/admin/tenants/{id}
	UpdateTenant(ctx context.Context, req *UpdateTenantRequest, params UpdateTenantParams) (UpdateTenantRes, error)
	// UpdateTenantAISettings implements updateTenantAISettings operation.
	//
	// Set the tenant AI provider, model, key and whether it is enforced (administrators; enterprise).
	//
	// PUT /api/admin/ai-settings
	UpdateTenantAISettings(ctx context.Context, req *TenantAISettings) (UpdateTenantAISettingsRes, error)
	// UpdateWorkflow implements updateWorkflow operation.
	//
	// Update a workflow definition's steps or metadata.
	//
	// PATCH /api/developer/workflows/{id}
	UpdateWorkflow(ctx context.Context, req *UpdateWorkflowRequest, params UpdateWorkflowParams) (UpdateWorkflowRes, error)
	// UpdateWorkflowInstance implements updateWorkflowInstance operation.
	//
	// Admin override of a workflow instance's status (business_admin only).
	//
	// PATCH /api/workflow/instances/{id}
	UpdateWorkflowInstance(ctx context.Context, req *UpdateWorkflowInstanceRequest, params UpdateWorkflowInstanceParams) (UpdateWorkflowInstanceRes, error)
	// UploadAiDocument implements uploadAiDocument operation.
	//
	// Upload a document (pdf, xlsx, docx, csv, txt, md, json) into a session; extracted text is injected
	// into every subsequent chat call.
	//
	// POST /api/ai/sessions/{id}/documents
	UploadAiDocument(ctx context.Context, req *UploadAiDocumentReq, params UploadAiDocumentParams) (UploadAiDocumentRes, error)
	// UpsertPlan implements upsertPlan operation.
	//
	// Create or change a plan — name, self-service flag and limits (platform_admin; applies to every
	// tenant on the plan within a minute).
	//
	// PUT /api/admin/plans/{key}
	UpsertPlan(ctx context.Context, req *PlanInput, params UpsertPlanParams) (UpsertPlanRes, error)
	// ValidateIntegration implements validateIntegration operation.
	//
	// Validate a rest_api integration's configuration and target/connection ownership without saving.
	//
	// POST /api/developer/integrations/{id}/validate
	ValidateIntegration(ctx context.Context, params ValidateIntegrationParams) (ValidateIntegrationRes, error)
	// ValidateWorkflow implements validateWorkflow operation.
	//
	// Run structural validation on a workflow definition without publishing it.
	//
	// POST /api/developer/workflows/{id}/validate
	ValidateWorkflow(ctx context.Context, req OptValidateWorkflowReq, params ValidateWorkflowParams) (ValidateWorkflowRes, error)
	// Writeback implements writeback operation.
	//
	// Write a single cell value (triggers recalculation).
	//
	// POST /api/cells
	Writeback(ctx context.Context, req *WritebackRequest) (WritebackRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
