// Code generated by ogen, DO NOT EDIT.

package oas

// setDefaults set default value of fields.
func (s *AiSaveSettingsRequest) setDefaults() {
	{
		val := string("openai")
		s.Provider.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *AutomationRuleRequest) setDefaults() {
	{
		val := AutomationRuleRequestTriggerType("manual")
		s.TriggerType.SetTo(val)
	}
	{
		val := string("UTC")
		s.Timezone.SetTo(val)
	}
	{
		val := AutomationRuleRequestMisfirePolicy("skip")
		s.MisfirePolicy.SetTo(val)
	}
	{
		val := int(0)
		s.MaxRetries.SetTo(val)
	}
	{
		val := int(60)
		s.RetryBackoffSeconds.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateAdminModelRequest) setDefaults() {
	{
		val := string("oltp")
		s.StorageType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateApplicationRequest) setDefaults() {
	{
		val := CreateApplicationRequestMode("planning")
		s.Mode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateDimensionRequest) setDefaults() {
	{
		val := string("sum")
		s.AggRule.SetTo(val)
	}
	{
		val := CreateDimensionRequestDimensionType("standard")
		s.DimensionType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateFormMappingRequest) setDefaults() {
	{
		val := string("sum")
		s.Aggregation.SetTo(val)
	}
	{
		val := bool(true)
		s.LivePosting.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateIntegrationRequest) setDefaults() {
	{
		val := string("csv_import")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateMetricRequest) setDefaults() {
	{
		val := string("sum")
		s.AggRule.SetTo(val)
	}
	{
		val := string("number")
		s.Format.SetTo(val)
	}
	{
		val := string("$")
		s.FormatCurrency.SetTo(val)
	}
	{
		val := CreateMetricRequestTimeSummary("sum")
		s.TimeSummary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateTenantRequest) setDefaults() {
	{
		val := string("standard")
		s.Plan.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateWorkflowRequest) setDefaults() {
	{
		val := string("manual")
		s.TriggerEvent.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ImportUploadRequest) setDefaults() {
	{
		val := ImportUploadRequestImportMode("incremental")
		s.ImportMode.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MetricDef) setDefaults() {
	{
		val := MetricDefTimeSummary("sum")
		s.TimeSummary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PropertyRequest) setDefaults() {
	{
		val := string("text")
		s.DataType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateFormMappingRequest) setDefaults() {
	{
		val := bool(true)
		s.LivePosting.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateMetricRequest) setDefaults() {
	{
		val := UpdateMetricRequestTimeSummary("sum")
		s.TimeSummary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateRecordRequest) setDefaults() {
	{
		val := UpdateRecordRequestStatus("draft")
		s.Status.SetTo(val)
	}
}
