#!/usr/bin/env bash
# Generates a SealedSecret for one cluster. Writes to
# deploy/k8s/overlays/prod/sealed-secrets.yaml by default — a path this
# repository ignores, because a sealed secret describes one deployment and
# belongs in that deployment's own private repository. Override with OUT=.
#
# Sealed-secrets encrypts to ONE specific cluster's public key, so this can
# only run against the live cluster — which is why no encrypted file ships in
# this repo and why the prod overlay has no Secret until you run this.
#
# The OUTPUT is safe to commit. That is the whole point of sealed-secrets:
# only the controller in that cluster holds the private key, so the encrypted
# blob is useless to anyone who clones the repo. Do not gitignore it.
#
# Prerequisites:
#   - kubeseal on PATH            (brew install kubeseal)
#   - sealed-secrets controller installed in the cluster
#   - kubectl pointing at the RIGHT cluster (this script refuses to guess)
#
# Usage:
#   POSTGRES_PASSWORD=... MINIO_ROOT_PASSWORD=... JWT_SECRET=... \
#   KEYCLOAK_ADMIN_PASSWORD=... bash scripts/seal-secrets.sh
set -euo pipefail

OUT="${OUT:-deploy/k8s/overlays/prod/sealed-secrets.yaml}"
NS="mavericks"
NAME="mavericks-secrets"

command -v kubeseal >/dev/null || { echo "kubeseal not found on PATH" >&2; exit 1; }
command -v kubectl  >/dev/null || { echo "kubectl not found on PATH" >&2; exit 1; }

# Refuse to run against the wrong cluster by accident — this is the step that
# decides which cluster can decrypt the result.
ctx=$(kubectl config current-context)
echo "Sealing against context: ${ctx}"
read -r -p "Is that the production cluster? [y/N] " ok
[ "${ok:-n}" = "y" ] || { echo "aborted"; exit 1; }

require() {
  # Values are read from the environment, never from arguments: arguments are
  # visible to every process on the machine via ps.
  local name="$1"
  local value="${!name:-}"
  if [ -z "$value" ]; then
    echo "missing required env var: ${name}" >&2
    exit 1
  fi
  if [ "$value" = "changeme" ] || [ "$value" = "mavericks" ]; then
    echo "${name} is still a default placeholder value — refusing to seal it" >&2
    exit 1
  fi
}

require POSTGRES_PASSWORD
require MINIO_ROOT_PASSWORD
require JWT_SECRET
require KEYCLOAK_ADMIN_PASSWORD
# Generated by Keycloak, not by you: run scripts/keycloak-provisioning-setup.sh
# first, which creates the service account and prints its secret. Without it
# the gateway refuses to create users, because the accounts it made could not
# sign in.
require KEYCLOAK_ADMIN_CLIENT_SECRET

mkdir -p "$(dirname "$OUT")"

# --dry-run=client keeps the PLAINTEXT Secret from ever reaching the cluster or
# the shell history; it is piped straight into kubeseal and never written to
# disk.
kubectl create secret generic "$NAME" \
  --namespace "$NS" \
  --dry-run=client -o yaml \
  --from-literal=POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
  --from-literal=MINIO_ROOT_PASSWORD="$MINIO_ROOT_PASSWORD" \
  --from-literal=JWT_SECRET="$JWT_SECRET" \
  --from-literal=KEYCLOAK_ADMIN_PASSWORD="$KEYCLOAK_ADMIN_PASSWORD" \
  --from-literal=KEYCLOAK_ADMIN_CLIENT_SECRET="$KEYCLOAK_ADMIN_CLIENT_SECRET" \
| kubeseal --format yaml > "$OUT"

echo "wrote ${OUT}"
echo
echo "Next:"
echo "  1. Add '- sealed-secrets.yaml' to the resources list in"
echo "     your overlay's kustomization.yaml (once)."
echo "  2. Commit ${OUT} — it is encrypted and safe in git."
